src/XrdOuc/XrdOucCache.hh, src/XrdPosix/XrdPosixXrootd.cc
With this change method Unlink, Rmdir, Rename, and Truncate are propagated to cache from posix layer.
The request for this change was formed in #180.
=> Propagate remove call from Posix to Cache layer

src/XrdHttp/XrdHttpReq.cc
The nightly HC tests that include XrdHTTP degraded mid-December 2014 after upgrading to
Xrootd/XrdHTTP from EPEL-test in our stable testbed. Before it was running a head from October.
The symptom is thread looping after partial chunk requests under certain circumstances.
The consequence is the performance degrading to almost zero due to cpu consumption.
This pull request fixes this
=> XrdHTTP thread looping after partial chunk requests: critical bugfix. 

src/XrdFileCache/XrdFileCacheFactory.cc, src/XrdFileCache/XrdFileCacheInfo.cc
The PR contains two commits:
- fix crash in purge of file cache 
- replace statvs with XrdOssSys::StatVS to use XrdOssSys consistently for all output file operations
=> XrdFileCache:: fix crash in cache purge 

src/XrdFileCache/XrdFileCacheFactory.cc
The cache purge has not been called after the timeout because of wrong used of XrdOssDF::Opendir().
=> pfc: fix cache purge on timeout

src/XrdFileCache/XrdFileCacheInfo.cc, src/XrdFileCache/XrdFileCacheInfo.hh, src/XrdFileCache/XrdFileCachePrefetch.cc, src/XrdFileCache/XrdFileCachePrefetch.hh
- Use fsync before writing out cinfo file to make sure state file is consistent with data file contents on disk in case of forced shutdown.
- Use 0644 for cached files.
=> [pfc] Use fsync for cache consistency

src/XrdFileCache/XrdFileCacheFactory.hh
For a test I substitute pfc.cacehdir with oss.localroot parameter in configuration:
#pfc.cachedir /foo/home/alja/xrd/data1
oss.localroot /foo/home/alja/xrd/data1
=> pfc: Leave cachedir empty by the default.

src/XrdFileCache/XrdFileCacheFactory.cc, src/XrdFileCache/XrdFileCacheFactory.hh
By the default owner of the cached files is the same as the process owner.
=> Pfc:: set owner of cached files same as the process owner

src/XrdFileCache/XrdFileCacheFactory.cc, src/XrdFileCache/XrdFileCacheFactory.hh, src/XrdFileCache/XrdFileCacheInfo.hh
With this implementation file with the oldest close time are deleted.
Bug was reported by Anna Olson.
=> ProxyFileCache purge :: fix order of deletion, optimize sorting 

src/XrdCeph/XrdCephOssFile.cc, src/XrdCeph/XrdCephPosix.cc, src/XrdCeph/XrdCephPosix.hh
Contains :
- async API in the Ceph plugin
- Final fix on O_TRUNC support
=> Another set of fixes

src/XrdCeph.cmake
The interface concerning object listing has changed in Ceph between giant and hammer releases.
This commit allows to compile against both by keeping the old interface and disabling the deprecation warnings
=> Compatibility code for different versions of Ceph

src/XrdFileCache/XrdFileCacheInfo.cc
The bug manifested only in non-debug mode.
=> pfc: Fix bug in reading file close time from *cinfo file

src/XrdFileCache/XrdFileCachePrefetch.cc
This is a bugfix in a meta-data file manifested in case where the file is only opened in proxy, but not read.
=> pfc: write meta data info after its initialization

docs/man/pfc_print.8, docs/man/xrdpfc_print.8, src/XrdFileCache.cmake, src/XrdFileCache/XrdFileCacheFactory.cc, src/XrdFileCache/XrdFileCacheInfo.cc, src/XrdFileCache/XrdFileCacheInfo.hh, src/XrdFileCache/XrdFileCachePrefetch.cc, src/XrdFileCache/XrdFileCachePrint.cc, src/XrdFileCache/XrdFileCachePrint.hh
This is a new tool which prints XrdFileCache binary meta data.
Usage: **xrdpfc_print** [-c config_file] [-v] path
More information is in xrdpfc_print man page.
=> New xrdpfc_print command line tool to display XrdFileCache meta data

src/XrdFileCache/XrdFileCachePrefetch.cc
Add a check if chunkVec is empty before requesting direct vector reads.
=> pfc: Fix bug in vector reads manifested when all the data is cached

src/XrdFileCache/XrdFileCacheFactory.cc
Missing one argument in snprintf.
=> Pfc: Fix compilation error, visible with flag  -Werror=format-security

src/XrdCms/XrdCmsLogin.cc
Fix for compilation error on RHEL7 ppc64:
error: narrowing conversion of 'rblen' from 'int' to 'kXR_unt16 {aka short unsigned int}' inside { } is ill-formed in C++11
=> Fix narrowing conversion error on RHEL7 ppc64

src/XrdOfs/XrdOfsTPCAuth.cc
In case the address resolution fails then the authMutex is never
released and all subsequent TPC transfers will deadlock. Seen in
in the XRootD plugin in CASTOR with the following signature:
150706 19:25:54 10128 castor2ofs_TPC: alienmas.60723:19@aliendb9
Unable to open ....; Name or service not known
Example of deadlocked threads:
Thread 31 (Thread 0x7f1b7369c700 (LWP 10128)):
#0  0x000000369f40e264 in __lll_lock_wait () from /lib64/libpthread.so.0
#1  0x000000369f409508 in _L_lock_854 () from /lib64/libpthread.so.0
#2  0x000000369f4093d7 in pthread_mutex_lock () from /lib64/libpthread.so.0
#3  0x00000036a046ccf8 in XrdOfsTPCAuth::Del() () from /usr/lib64/libXrdServer.so.2
#4  0x00000036a045f252 in XrdOfsFile::close() () from /usr/lib64/libXrdServer.so.2
#5  0x00007f1b72a11d1e in …
=> TPC: Fix deadlock in case of error in the TPC authentication

src/XrdFileCache/XrdFileCacheIOEntireFile.cc, src/XrdFileCache/XrdFileCacheIOFileBlock.cc
Resolve problem reported in #249:
Calling cat command on virtual mount. The command does 64k reads possibly exceeding file size.
=> pfc: Protect from reads exceeding file size

src/XrdCl/XrdClStream.cc
OnReadTimeout will call OnError with the Stream's lock held.
This causes OnError to invoke the user's callback with the
Stream lock held, possibly causing a lock ordering issue.
This fixes an observed deadlock within CMSSW over the following
objects (originally reported by Chris Jones):
```
Thread 1
FileStateHandler::VectorRead takes FileStateHandler lock
Stream::Send tries to take Stream lock
Thread 5
FileTimer::Run takes FileTimer lock
FileStateHandler::Tick tries to take FileStateHandler
Thread 6
Stream::OnReadTimeout takes Stream lock
DelayedClose::HandleResponseWithHosts  (this is callback code in CMSSW); this deletes a File object, which eventually calls
FileTimer::UnRegisterFileObject tries to take FileTimer lock
```
=> Release Stream lock before invoking callbacks. #216

src/XrdFileCache/XrdFileCachePrefetch.cc
=> pfc: Fix bug in read when opening of local file fails

src/XrdCl/XrdClDefaultEnv.cc, src/XrdCl/XrdClPostMaster.cc
In case several threads start doing transfers in parallel some can
fail with the following error: [FATAL] Initialization error
because the post master object is created but not initialized.
This only happens in the beginning when the PostMaster is not set up. The initial idea was probably to make the GetPostMaster code as efficient as possible by not taking the lock on the most frequent case. But this leads to a situation where a thread creates the sPostMaster object but does not get to initialize it, and another thread picks it up as the object exists and tries to use it.
=> XrdCl: Fix race condition in PostMaster initialization

src/XrdCl/XrdClDefaultEnv.cc
This uses the built-in atomic functions. The test program is:
```c++
#include "XrdSys/XrdSysAtomics.hh"
int a;
void val_set(int v) {  AtomicCAS(a, a, v); }
int val_get() { return AtomicGet(a); }
```
The assembler code for x86_64 is as expected:
```asm
_Z7val_seti:
.cfi_startproc
movl    %edi, a(%rip)
ret
.cfi_endproc
_Z7val_getv:
.cfi_startproc
movl    a(%rip), %eax
ret
.cfi_endproc
```
While for ARM it looks like this:
```asm
_Z7val_seti:
.fnstart
.LFB0:
@ args = 0, pretend = 0, frame = 0
@ frame_needed = 0, uses_anonymous_args = 0
@ link register save eliminated.
ldr     r3, .L2
str     r0, [r3, #0]
bx      lr
.L3:
.align  2
.L2:
.word   .LANCHOR0
.cantunwind
.fnend
_Z7val_getv:
.fnstart
.LFB1:
@ args = 0, pretend = 0, frame = 0
@ frame_needed = 0, uses_anonymous_args = 0
@ link …
```
=> XrdCl: Provide atomicity for PostMaster value using built-in functions

src/XrdSsi/XrdSsiFileReq.cc
Clang reports a problem with the variable being used to calculate the
size of the string buffer in XrdSsiFileReq::Alloc -
XrdSsiFileReq.cc:142:33: error: invalid use of member 'rID' in static member
The fix is to use sizeof() on the same variable that is receiving the string.
With this change xrootd compiles this branch on OS X with clang. This is important as this branch is already in use at LSST.
=> Use correct snprintf sizeof variable

src/XrdPss/XrdPss.cc
This may cause the proxy to respond with 'file not found', causing
upstream redirectors to believe the file is not present behind
the proxy at all - even if it's just 'not found' because the only
source was excluded.
=> Do not forward the 'tried=' CGI within the proxy interface.

packaging/rhel/xrootd.spec.in, src/XrdFileCache.cmake, src/XrdFileCache/XrdFileCacheBlacklistDecision.cc, src/XrdFileCache/XrdFileCacheDecision.hh, src/XrdFileCache/XrdFileCacheFactory.cc
The current release does very little with the decision plugin architecture - we ship source code for a trivial plugin (which always returns true) but we don't appear to build it or ship it (of course, why would we?).
This pull request adds a new plugin, "blacklist decision", which can be enabled with the following configuration line:
```
pfc.decisionlib libXrdBlacklistDecision.so /etc/xrootd/blacklist-cache.cfg
```
where /etc/xrootd/blacklist-cache.cfg is a list of globs.  For example:
```
/bar/baz/foo
/foo/*/some_file
/foo/*/.*
```
This is shipped as part of the xrootd-server-libs RPM.
@alja @osschar
=> Implement blacklisting in a FileCache decision plugin.

src/XrdOuc/XrdOuca2x.cc
Replace strtoll() witth strtod() in  XrdOuca2x::a2sz.
This change is useful in XrdFileCache configuration parsing, to be able to specify diskusage limits in decimals, e.g.
pfc.diskuage 1T 1.5T
=> Allow conversion of decimal numbers in  XrdOuca2x::a2sz()

src/XrdFileCache/README, src/XrdFileCache/XrdFileCacheFactory.cc, src/XrdFileCache/XrdFileCacheFactory.hh
This feature was requested by Hinori Ito and Lincoln Bryant.
The parameter can be now specified absolute or relative. For example:
pfc.diskuage 1.5T 10T
pfc.diskuage 0.7 0.95
=> pfc: add possibility to specify disk usage parameters in .. G, T units using XrdOuca2x::a2sz()

src/XrdFileCache/XrdFileCacheIOEntireFile.cc, src/XrdFileCache/XrdFileCacheIOFileBlock.cc
Detect bad offsets in read requests.
=> Pfc offset fix

src/XrdSys/XrdSysLinuxSemaphore.hh
Change the order of some statements when registering pthread clean-up functions.
Fixes #310 and #313.
=> Order pthread cleanup statements

src/XrdFileCache/XrdFileCacheFactory.cc, src/XrdFileCache/XrdFileCacheInfo.hh
* use bytes instead of blocks when planning purge operation;
* fallback to stat.mtime when access time can not be determined from cinfo file.
=> Fix several issues with cache purging

bindings/python/src/AsyncResponseHandler.hh, bindings/python/src/PyXRootDFile.cc, bindings/python/src/PyXRootDFileSystem.cc
When synchronous operations are performed, the python GIL should be
dropped using the `async` macro.  Otherwise, the following deadlock
can occur:
a) A python thread, holding the GIL, may call out to a XrdCl::File
object, which takes an XRootD-related lock.
b) A XrdCl callback thread, holding an XRootD-related lock, tries
to invoke a python callback and tries to acquire the GIL.
Since the python GIL is not needed to invoke an XrdCl operation,
this patch drops it for case (a), avoiding the deadlock.
=> Fix deadlock due to lock inversion in python bindings.

src/XrdSys/XrdSysDNS.cc
```
/builddir/build/BUILD/xrootd-4.2.3/src/XrdSys/XrdSysDNS.cc: In static member function 'static int XrdSysDNS::getAddrName(const char*, int, char**, char**, char**)':
/builddir/build/BUILD/xrootd-4.2.3/src/XrdSys/XrdSysDNS.cc:187:51: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
int hn = getHostName((struct sockaddr &)ip[i], names, 1, errtxt);
^
/builddir/build/BUILD/xrootd-4.2.3/src/XrdSys/XrdSysDNS.cc: In static member function 'static int XrdSysDNS::Host2Dest(const char*, sockaddr&, char**)':
/builddir/build/BUILD/xrootd-4.2.3/src/XrdSys/XrdSysDNS.cc:522:47: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
if (!getHostAddr(hbuff, (struct sockaddr &)InetAddr, errtxt)) return 0; …
```
=> Fix strict aliasing issues

src/XrdSys/XrdSysPthread.hh, src/XrdSys/XrdSysXSLock.cc
Throwing exceptions in a destructor causes warnings with gcc 6, and since -Werror is used this becomes an error:
XrdSys/XrdSysPthread.hh: In destructor 'XrdSysSemaphore::~XrdSysSemaphore()':
XrdSys/XrdSysPthread.hh:356:31: error: throw will always call terminate() [-Werror=terminate]
XrdSys/XrdSysPthread.hh:356:31: note: in C++11 destructors default to noexcept
There are two destructors in the code that does this. This pull request comments out these lines of code.
=> Don't throw exceptions in destructors

src/XrdSecgsi/XrdSecProtocolgsi.cc
We recently enabled GSI authentication with xrootd 4.2.3. It appears each GSI authentication causes about 6kB of memory to be leaked.
Toward the beginning of XrdSecProtocolgsi::Authenticate(), memory may be
allocated for the Entity with strdup():
https://github.com/xrootd/xrootd/blob/a76eccc1f2/src/XrdSecgsi/XrdSecProtocolgsi.cc#L1873
Later in the same function, the Entity may be replaced with an entry from the
cache:
https://github.com/xrootd/xrootd/blob/a76eccc1f2/src/XrdSecgsi/XrdSecProtocolgsi.cc#L1951
However, the memory allocated with strdup() is not free()d. This patch calls FreeEntity()
before replacing Entity with a copy from the cache.
Regards,
John
valgrind output for the largest lost block after 20 GSI authentications (xrootd 4.2.3):
```
==10420== 120,760 bytes in 20 blocks …
```
=> With GSI auth, free Entity variable before replacing it from the cache

src/XrdFileCache/XrdFileCache.cc, src/XrdFileCache/XrdFileCache.hh, src/XrdFileCache/XrdFileCacheConfiguration.cc, src/XrdFileCache/XrdFileCacheFile.cc, src/XrdFileCache/XrdFileCacheIO.hh, src/XrdFileCache/XrdFileCacheIOEntireFile.cc, src/XrdFileCache/XrdFileCacheIOEntireFile.hh, src/XrdFileCache/XrdFileCacheInfo.cc, src/XrdFileCache/XrdFileCacheInfo.hh
This pull reguest has the following changes:
* Recycle File object during delayed destruction
* configuration: define RAM to use in human friendly format ( e.g. using [g] suffix)
* reject version 0 of *cinfo files, since they don't contain file size information
=> pfc-V2: Recycle File object during delayed destruction

src/XrdFileCache/README, src/XrdFileCache/XrdFileCache.cc, src/XrdFileCache/XrdFileCache.hh, src/XrdFileCache/XrdFileCacheConfiguration.cc
Two changes in thos PR:
* pfc.ram a required parameter
* specifiy prefetch level as pfc.prefetch <n>
* update readme
=> pfc-V2: Set RAM usage required parameter

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/xrootd-http.cf
namely SLC5, rawhide and some flavors of MacOS
=> XtdHTTP: work around compilation issues in platforms with old versions of OpenSSL

src/XrdFileCache/XrdFileCacheFile.cc
From the stack trace looked like Sync() function was called from the scheduler at the time the object was partially destroyed.
With this change, the Sync is waited to be executed (indirectly checked by ioActive call).
=> pfc-V2: Fix crash File destructor

cmake/FindOpenSSL.cmake, cmake/XRootDSystemCheck.cmake, src/XrdHttp.cmake, src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/xrootd-http.cf
This version of the openssl method detection works for me on slc5 and rawhide.
=> Use cmake to determine the existence of openssl funcs. Ignore the openssl constants

src/XrdCl/XrdClXRootDMsgHandler.cc
Hi Andy, 
I put this as a pull request so that we can discuss if I misunderstood something related to the desired behaviour of the client. 
**The problem**: the parameters included in the opaque part of a URL that deal with authentication (i.e. xrd.wantprot, xrd.krb5ccname etc) are not properly forwarded when redirections are followed. 
The assumption I made is that if a client requests a certain type of authentication then this should be enforced with respect to all parties that it contacts during the transfer.
First of all, there is a clear inconsistency between the behaviour when the XrdSecPROTOCOL is used and when the `xrd.wantproto` is added to the URL. This comes from the fact that in https://github.com/xrootd/xrootd/blob/master/src/XrdSec/XrdSecPManager.cc#L153 the process env …
=> XrdCl: Forward xrd.* parameters from the original to the redirection URL

packaging/rhel/xrootd.functions
According to Fedora packaging guidelines stopping an already stopped service should be considered succesful see:
http://fedoraproject.org/wiki/EPEL:SysVInitScript#Exit_Codes_for_non-Status_Actions
Now an already stopped service returns 0:
```
[1448] root@uclhctest /etc/init.d# service xrootd stop
Shutting down xrootd (xrootd, rdr): xrootd-rdr not running
Shutting down xrootd (xrootd, srv): xrootd-srv not running
Shutting down xrootd (xrootd, atlas_proxy): xrootd-atlas_proxy not running
Shutting down xrootd (xrootd, cms_proxy): xrootd-cms_proxy not running
[1448] root@uclhctest /etc/init.d# echo $?
0
```
=> Stopping the service if already stop should be succesfull now

src/XrdHttp/XrdHttpReq.cc
Repeated slashes would not cause any malfunction to XrdHttp per se. When used in an html rendering they would confuse the browser, though, which is not desirable.
Partially fixes #368 (which contains two issues apparently)
=> XrdHttp: Sanitize the resource string, removing double slashes

src/XrdFileCache/XrdFileCache.cc, src/XrdFileCache/XrdFileCache.hh, src/XrdFileCache/XrdFileCacheFile.cc, src/XrdFileCache/XrdFileCacheFile.hh, src/XrdFileCache/XrdFileCacheIO.hh, src/XrdFileCache/XrdFileCacheIOEntireFile.cc, src/XrdFileCache/XrdFileCacheIOFileBlock.cc, src/XrdFileCache/XrdFileCacheIOFileBlock.hh, src/XrdFileCache/XrdFileCacheVRead.cc
* include file block offset in case of hdfs healing mode
* required changes in delayed destroy
=> pfc-V2: transition of hdfs healing code from V1 to V2 

packaging/common/cmsd@.service, packaging/common/frm_purged@.service, packaging/common/frm_xfrd@.service, packaging/common/xrootd@.service
@zvada noted that max open files is not being set in RHEL7 for the xrootd service.
This request updates the systemd config, increasing the limits to 65k to match the RHEL6 init script.
https://github.com/xrootd/xrootd/blob/c786d75c00/packaging/rhel/xrootd.functions#L108
=> Set max open files limit to 65k for systemd services

src/XrdFileCache/XrdFileCacheFile.cc, src/XrdFileCache/XrdFileCacheIOEntireFile.cc, src/XrdFileCache/XrdFileCachePurge.cc
The PR fixes crash in File destructor when info file open fails.
I also added errno info in the log messages.
=> pfc-V2: Additional file open checks and error messages 

src/XrdFileCache/XrdFileCacheFile.cc, src/XrdFileCache/XrdFileCacheIOEntireFile.cc, src/XrdFileCache/XrdFileCacheIOEntireFile.hh, src/XrdFileCache/XrdFileCacheIOFileBlock.cc, src/XrdFileCache/XrdFileCacheVRead.cc
Previously access statistics was saved in block units. Now it is saved with exact number of bytes read from disk, directly from client and from ram.
=> pfc-V2 Save and print access statistics in bytes

src/XrdFileCache/XrdFileCache.cc, src/XrdFileCache/XrdFileCacheIO.hh, src/XrdFileCache/XrdFileCacheIOFileBlock.cc, src/XrdFileCache/XrdFileCacheIOFileBlock.hh
Create info file for the path in order to get file size without client.
=> pfc-V2 Implement deferred open for file block mode

src/XrdCeph/XrdCephOss.cc, src/XrdCeph/XrdCephOss.hh, src/XrdCeph/XrdCephPosix.cc
Allowed to use mutiple ceph objects in parallel when talking to ceph to workaround the limitation that a single threas is dealing with async answers per object.
In order to use this features, one has to add a line to the xrootd config file :
ceph.nbconnections <n>
By default, only one object will be used.
=> [XrdCeph] Implemented pools of ceph objects

packaging/rhel/xrootd.spec.in, src/XrdApps.cmake
The xrdacctest programme is available in the source but is not currently packaged. At Rutherford Appleton Laboratory, we would like to use the xrdacctest with the GridFTP Ceph plugin and so would like it packaged. This change accomplishes just that.
=> Package xrdacctest in xrootd-server RPM.

src/XrdPlugins.cmake
Without this the build fails on a Mac because of unresolved symbols.
=> XrdUtils library is needed for libXrdSsi on OS X

src/XrdCl/XrdClAsyncSocketHandler.cc, src/XrdCl/XrdClDefaultEnv.cc, src/XrdCl/XrdClLog.cc, src/XrdCl/XrdClLog.hh
needed to that the XrdClLog class can be used by any client plugin
implementation.
In the process of achieving this, we also moved the following methods
from the header file to the source file of XrdClLog: Dump, Debug, Info,
Warnining, Error.
=> XrdCl: Move the XrdClOptimizers.hh inside the source files where it's

src/XrdHttp/XrdHttpProtocol.cc
A proper secXtractor will accept good Grid proxy certificates and deny fraudulent ones
=> XrdHTTP: Deny access if the secXtractor fails

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpSecXtractor.hh
Fix some minor memory leaks
Change the secxtractor interface to use the new lib and initialize it properly
=> Make Xrdhttp secure by default, by rejecting proxy cert in the absence of a proper SecXtractor plugin

src/XrdXrootd/XrdXrootdConfig.cc, src/XrdXrootd/XrdXrootdProtocol.cc, src/XrdXrootd/XrdXrootdProtocol.hh, src/XrdXrootd/XrdXrootdXeq.cc
CMS saw a fairly effective DoS attack on our infrastructure when a user accidentally issued billions of prepare requests.
This patch is what we did in response - simply put a hard limit on the number of prepare requests allowed per client connection.
For example, to allow 40 prepare requests per client connection, one would add the following to the configuration file:
```
xrootd.limit noerror prepare 40
```
`noerror` controls whether an explicit error message is returned to the client or the request is silently ignored.  For the CMS use case, `noerror` is set.
=> Add limits for prepare requests

packaging/common/xrootd-filecache-clustered.cfg, packaging/common/xrootd-filecache-standalone.cfg, packaging/rhel/xrootd.spec.in
Changes:
2 new xrootd server config files packaging/common
include them in server's rpm (change in xrootd.spec.in )
=> Add example of proxy file cache configuration in xrootd server rpm

src/XrdClient/XrdClient.cc, src/XrdSecpwd/XrdSecProtocolpwd.cc
Here are two issues I found while extracting the gcc 7 fixes from git.
1) The compilation fails where logical not is used instead if bitwise not in XrdClient.cc
2) In XrdSecProtocolpwd.cc the if statements added to replace the fall though doesn't actually fall through.
=> Gcc7 issues

src/XrdSecgsi/XrdSecProtocolgsi.cc
Hi!
After uploading xrootd 4.6.0 to Fedora and EPEL I got some feedback that authentication failed with many sites, see:
https://bodhi.fedoraproject.org/updates/FEDORA-2017-0eca8dbb12
I could reproduce the problem, and this is my proposed fix.
This issue was not caused by the changes to support openssl 1.1.0, but was introduced with the improvements to the CRL handling that was part of the 4.6.0 release.
=> Fix CRL verification bug

src/XrdSec/XrdSecProtect.cc
Apple deprecated openssl on OSX a while back, and stopped shipping the headers at all on release 10.11 (El Capitan).  This patch uses the Apple-preferred CommonCrypto/CommonDigest.h instead when compiling on OSX.  Fixes #439
=> Use CommonCrypto header instead of openssl for SHA on OSX

src/XrdFileCache/XrdFileCacheConfiguration.cc
When old-style configuration directives are encountered errors are printed in
the log.
When pfc.ram is not given a default of 8 GB is used.
=> XrdFileCache - accept old configuration directives (part of #470)

src/XrdFileCache/XrdFileCacheConfiguration.cc
Without explicitly ignoring the argument value, we trigger an assert to make sure all arguments have been processed - even if it is otherwise ignored.
Assert failure looked like:
```
170301 22:44:17 2410886 XrdFileCache_Config: pfc.nramread is deprecated, please use pfc.ram instead. Ignoring this directive.
xrootd: /home/cse496/bbockelm/projects/xrootd/src/XrdFileCache/XrdFileCacheConfiguration.cc:413: bool XrdFileCache::Cache::ConfigParameters(std::string, XrdOucStream&, XrdFileCache::TmpConfiguration&): Assertion `config.GetWord() == 0 && "Cache::ConfigParameters() lost argument"' failed.
```
triggered by the presence of `pfc.nramread 4`.
=> Ignore unnecessary parameter.

src/XrdVersionPlugin.hh
Require version checking on the XrdHttpGetSecXtractor
Remove useless plugin rule
=> Require version checking on the XrdHttpGetSecXtractor

src/XrdFileCache/XrdFileCacheFile.cc
Lock m_is_open  in File::ioActive().
Fixes crash  in the following scenario:
a) Client logs in and opens a file.
b) Starts reading.
c) The base file is either created or already exists from a previous open but there is no cinfo file as of yet.
d) Client crashes (I/O may or may not be active as of yet but likely is).
e) XRootD closes the file and close call IOActive() to see if the file can be closed.
f) The FileCache code goes through it's pending block chain to see which need to be removed. However, the data structure is still in the process of being built and it encounters a partially completed entry and crashes on that one.
=> pfc: Handle client disconnect at the startup time

src/XrdCeph/XrdCephPosix.cc
The bug manifested itself only 2 times when the xrootd server attempted to read back a file written out of order (to compute the checksum).
The 'improvements' are actually about dropping way too many messages in the absence of a proper mechanism to classify them as debug level. @sponce, what do you think?
=> Fix ability to read back a file written with O_RDWR flags + improvements in the logs

packaging/rhel/xrootd.spec.in, src/XrdApps.cmake, src/XrdApps/XrdClProxyPlugin/ProxyPrefixFile.cc, src/XrdApps/XrdClProxyPlugin/ProxyPrefixFile.hh, src/XrdApps/XrdClProxyPlugin/ProxyPrefixPlugin.cc, src/XrdApps/XrdClProxyPlugin/ProxyPrefixPlugin.hh, src/XrdApps/XrdClProxyPlugin/README.md
I've added as a .so library since it's not a shared library but a module which is loaded dynamically.
=> XrdApp: Add XrdClProxyPlugin implementation

src/XrdFileCache/XrdFileCacheIOEntireFile.cc, src/XrdFileCache/XrdFileCacheIOFileBlock.cc
When file is open and prefetching  the  IO::initLocalStat() reported an error called from the purge thread. This is not an error, since info file was still modifying. This is the reason I moved the severity from error to debug mode.
=> pfc: Change severity IO::initLocalStat() log message

packaging/rhel/xrootd.spec.in, src/XrdCl/XrdClDefaultEnv.cc, src/XrdSecgsi.cmake, src/XrdSecgsi/XrdSecgsiGMAPFunLDAP.cc, src/XrdVersionPlugin.hh
The way the LDAP query is implemented may represent a security threat.
Any related building and packaging reference is removed.
The code is left in place (for the time being) to remind its functionality
in the case a sanitized version is required.
=> secgsi: do not build/package libXrdSecgsiGMAPLDAP-4.so

src/XrdFileCache/XrdFileCache.cc, src/XrdFileCache/XrdFileCache.hh, src/XrdFileCache/XrdFileCacheFile.cc, src/XrdFileCache/XrdFileCacheFile.hh, src/XrdFileCache/XrdFileCacheIO.hh, src/XrdFileCache/XrdFileCacheIOEntireFile.cc, src/XrdFileCache/XrdFileCacheIOEntireFile.hh, src/XrdFileCache/XrdFileCacheIOFileBlock.cc, src/XrdFileCache/XrdFileCacheIOFileBlock.hh, src/XrdFileCache/XrdFileCacheInfo.cc
File ref-counts are made from CacheIO objects and from sync tasks. This common management of usage somewhat simplifies the destruction of CacheIO and File objects.
There is a bunch of white-space changes I couldn't refrain myself from doing while reviewing the code.
=> [XrdFileCache] Use ref-counts on File objects

src/XrdFfs/README, src/XrdFfs/XrdFfsXrootdfs.cc
Motivation:
This prevented mounting if user_allow_other is not set in fuse.conf
So a user with no root access could not use xrootdfs and could not change this argument without recompiling.
Change:
Don't pass allow_other to fuse by default.
Result:
Now xrootdfs works if user_allow_other is disabled, and allow_other argument can be passed when mounting if it is needed.
=> xrootdfs: remove default fuse argument "allow_other" as it is impossible to unset

src/XrdFfs/XrdFfsXrootdfs.cc
Motivation:
In general, a create operation is nice to have.
Especially useful for a dcache xrootd door.
When FUSE has to use mknod, it results in an empty file being created, closed, then opened again for writing.
In dcache this does not work and needs an explicit check to allow overwriting the empty file.
Just appending to the empty file is not possible in dcache, and FUSE does not set the DELETE flag, as it does not expect it to be needed to append to an empty file.
Implementing a create operation makes copying onto dcache faster, as it does not require creating the file twice.
Change:
Implement xrootdfs_create that works as xrootdfs_mknod, except:
- it opens the file over a numbered link, instead of unnumbered, using the same link numbering process as xrootdfs_open
- it creates the …
=> xrootdfs: implement xrootdfs_create

src/XrdSys/XrdSysIOEvents.hh
Fixes the following warning:
```
/Users/gbitzes/xrootd/src/XrdSys/XrdSysIOEvents.cc:557:22: warning: implicit conversion from 'int' to 'char' changes value from 255 to -1 [-Wconstant-conversion]
tmoMask         = 255;
~ ^~~
```
=> Make tmoMask unsigned

src/XrdCns/XrdCnsSsi.cc, src/XrdXrootd/XrdXrootdJob.cc
* src/XrdXrootd/XrdXrootdJob.cc, src/XrdCns/XrdCnsSsi.cc: gcc 7.1+
complains about verClient() [XrdXrootdJob] (-Werror=array-bounds) and
Updt() [XrdCnsSsi] (-Werror=nonnull), make it "happy".
Signed-off-by: Vladimir Lomov <lomov.vl@gmail.com>
=> Fixes for XrdXrootdJob and XrdCnsSsi

packaging/rhel/xrootd.spec.in
If Ceph is in the compile environment - but not explicitly enabled, then the RPM build may fail (installed but unpackaged files).
Thus, we should explicitly disable the Ceph build in cmake when Ceph is disabled in the RPM (and vice-versa).
=> Disable Ceph build unless enabled.

.travis.yml
I've tweaked the configuration after #502 so that XRootD now [builds and installs](https://travis-ci.org/alexpearce/xrootd/builds/233557963), and the tests are run in the build directory with the command:
```shell
$ ./tests/common/text-runner ./tests/XrdClTests/libXrdClTests.so 'All Tests'
```
This returns exit code 0, but the tests [actually fail](https://travis-ci.org/alexpearce/xrootd/jobs/233557965#L1507):
```
........F..terminate called after throwing an instance of 'CppUnit::Exception'
terminate called recursively
terminate called recursively
/home/travis/.travis/job_stages: line 54:  6746 Aborted                 (core dumped) ./tests/common/text-runner ./tests/XrdClTests/libXrdClTests.so 'All Tests'
```
Is this due to the way I'm running the tests, or is this failure 'expected' …
=> Add working Travis CI

src/Xrd/XrdLink.cc
Fixes handling of the offset used in further sendfile calls if the first one transmitted only part of the request size.
sendfile doesn't guarantee that all requested bytes are send. Only a fraction might have been send, one would then continue from the new offset and transfer the remain bytes (bytesleft). sendfile will set the offset variable (off_t *offset, myOffset in the xrootd code) to the offset of the byte following the last byte that was read and return the number of bytes read (into retc). By adding retc to myOffset, the offset gets moved away from the byte following the last byte that was read to a (false) position further forward in the file.
=> Fix handling of sendfile offset argument

src/XrdThrottle/XrdThrottle.hh, src/XrdThrottle/XrdThrottleFileSystem.cc
All the missing passthroughs for the throttle code should now be there.
=> Add missing XrdSfsFileSystem virtual overrides.

src/XrdCeph/XrdCephPosix.cc
Ceph version 12 removed some previously deprecated classes. This adapts the xrootd code accordingly. It still compiles with version 10. (I didn't check earlier versions than that.)
=> Adapt to ceph version 12

src/XrdCeph/XrdCephPosix.cc
The extended logs have been used to pinpoint a case where a misconfiguration made the Ceph init calls fail, but they are hopefully helpful for others.
=> XrdCeph: added more logging when initialisation fails

src/Xrd/XrdBuffer.cc
If the total buffer count (totbuf) is incorrectly high, the request profile (bufprof) will also be disproportionately high: it's scaled by the buffer count. The buffer pool is not reshaped, with too many buffers being held.
This patch decrements the total buffer count as buffers are deleted, matching the behavior of XrdBuffXL.
=> XrdBuffer: Decrement total buffer count when freeing buffers

src/Xrd/XrdBuffer.cc, src/Xrd/XrdConfig.cc
xlBuff was being defined in two separate compilation units,
thus violating C++'s one-definition-rule. The linker did not
complain, since the two symbols were defined in two different
libraries loaded at runtime.
Caught by ASan:
==10109==ERROR: AddressSanitizer: odr-violation (0x00000144a5e0):
[1] size=80 'XrdGlobal::xlBuff' /home/gbitzes/xrootd/src/Xrd/XrdConfig.cc:94:11
[2] size=80 'XrdGlobal::xlBuff' /home/gbitzes/xrootd/src/Xrd/XrdBuffer.cc:73:11
These globals were registered at these points:
[1]:
#0 0x435b40 (/home/gbitzes/xrootd/build-asan-clang/install/bin/xrootd+0x435b40)
#1 0x51eee9 (/home/gbitzes/xrootd/build-asan-clang/install/bin/xrootd+0x51eee9)
[2]:
#0 0x435b40 (/home/gbitzes/xrootd/build-asan-clang/install/bin/xrootd+0x435b40)
#1 0x7f7a70ceb41b …
=> Make xlBuff static to fix ODR violation

src/Xrd/XrdLink.cc
Under some workloads, there's a timing issue that can show up in XrdLink and the reference count. XrdLink uses a semaphore (IOSemaphore) to block XrdLink::Close() until all the threads associated with a link are complete. In some cases, two threads are waiting for the semaphore, but only a single signal is eventually given. This leaves a stuck thread and an open XrdLink object. Here's a backtrace of a stuck thread:
```
Thread 504 (Thread 0x7fe3254dc700 (LWP 964972)):
#0  0x00007fe60927d79b in futex_abstimed_wait (cancel=true, private=<optimized out>, abstime=0x0, expected=0, futex=0x7fe50c018c40) at ../nptl/sysdeps/unix/sysv/linux/sem_waitcommon.c:43
#1  do_futex_wait (sem=sem@entry=0x7fe50c018c40, abstime=0x0) at ../nptl/sysdeps/unix/sysv/linux/sem_waitcommon.c:223
#2  0x00007fe60927d82f …
```
=> XrdLink: Increment the IOSemaphore once for each waiting thread

src/XrdHeaders.cmake, src/XrdHttp/XrdHttpExtHandler.cc, src/XrdHttp/XrdHttpExtHandler.hh, src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, src/XrdHttp/XrdHttpReq.cc, src/XrdVersionPlugin.hh
This improves the HTTP external handler environment and interface to have richer semantics.
- Pass down the `XrdOucEnv` object when the object is initialized; necessary to initialize other parts of Xrootd.
- Allow one to access the `XrdSecEntity` object associated with a request.
- Allow filtering based on HTTP verb in `MatchesPath`.
- Make this a public plug-in interface and declare ABI compatibility.
@ffurano - this is meant to fix #585
=> Make HTTP external handlers more flexible

src/XrdSsi/XrdSsiShMat.hh
On systems where char by default is unsigned compilation fails with:
```
/builddir/build/BUILD/xrootd-4.7.0/src/XrdSsi/XrdSsiShMam.cc: In member function 'virtual bool XrdSsiShMam::Resize(XrdSsiShMat::CRZParms&)':
/builddir/build/BUILD/xrootd-4.7.0/src/XrdSsi/XrdSsiShMam.cc:1128:22: error: comparison is always false due to limited range of data type [-Werror=type-limits]
if (parms.reUse < 0) parms.reUse   = reUse;
^
/builddir/build/BUILD/xrootd-4.7.0/src/XrdSsi/XrdSsiShMam.cc:1129:22: error: comparison is always false due to limited range of data type [-Werror=type-limits]
if (parms.multW < 0) parms.multW   = multW;
^
cc1plus: all warnings being treated as errors
make[2]: Leaving directory `/builddir/build/BUILD/xrootd-4.7.0/build'
make[2]: *** …
```
=> Fix comparison always false error

src/XrdOfs/XrdOfsConfig.cc, src/XrdOfs/XrdOfsFS.cc
When requesting the default filesystem, a statically-initialized singleton object is returned - but the `Configure` method of that singleton is invoked for each call to `XrdSfsGetDefaultFileSystem`.
Unfortunately, there are several pieces of the object's state that leak through after each `Configure` call (in the environment or in the `XrdOfs` object member variables).  This effectively limits us to a single invocation of `XrdSfsGetDefaultFileSystem`.
This PR resets the leaky pieces of state, allowing a valid OFS object to be returned each time.
=> Allow XrdSfsGetDefaultFileSystem to be called multiple times

src/XrdHttp/XrdHttpReq.cc
Postprocessing a kxr_close should finish gracefully the request (fix for the double sending)
In any case, make sure that any buffer is not sent twice
Some indentation fixes
=> Fix for Github #596

src/XrdHttp/XrdHttpReq.cc
This may solve a part of the leaks reported in #596
=> Correctly handle disconnections while sending short responses in Done()

src/XrdSecgsi/XrdSecProtocolgsi.cc
A check on the entry validity was misplaced.
Should fix issue #595 .
=> Fix for segfault in cache checking (issue #595)

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, src/XrdHttp/XrdHttpReq.cc
This allows multiple external handlers to be loaded by `XrdHttp`.  The first loaded handler that matches a given request will handle it.
By allowing multiple plugins, we can have one plugin handle authorization requests that come in via HTTP and a second implement alternate HTTP verbs (see #586, for example).
=> Allow multiple external handlers to be loaded by XrdHttp.

src/XrdCl/XrdClUtils.hh, src/XrdCl/XrdClXRootDTransport.cc
Previously, I was calling setfsuid(-1) to check if the
previous call had succeeded, since this syscall will
always return the current fsuid, whether the syscall
itself succeeded or not. There's no way to check
other than calling setfsuid again, since there's no
getfsuid.
The expectation was that setfsuid(-1) will always fail
and not affect the fsuid, effectively acting as getfsuid,
but it appears that on SLC6 it succeeds, setting the
fsuid to.. 4294967295. On Fedora 26 it fails as expected,
I have no idea why there's a difference.
Instead, let's use setfsuid(pFsUid) again, just to
check if the previous call succeeded.
=> [XrdCl] Fix error checking when setting sec.uid, sec.gid

src/XrdFileCache/XrdFileCacheInfo.cc
Access history in cache meta-data is fixed size now, make sure we do not read beyond the end.
The file purge checking code was reading beyond the end and could lead to random behavior or crashes once the number of times a file was accessed grew beyond the internal size limit (20).
Please merge this also into stable-4.7.x.
=> [pfc] Bugfix in reading of last access time for file purging.

src/XrdHttp/XrdHttpProtocol.cc
The test to see if there is an external plugin was inverted, meaning the wrong case in the conditional was always called.  This fixes the logic, avoiding a `SIGSEGV` I encountered while testing the improved `XrdHttp` code.
Additionally, this reverses the order of evaluation -- checking the (cheap, common) pointer value first, then invoking a function.
@ffurano
=> Correct external handling logic.

src/XrdHttp/XrdHttpReq.cc
HTTP PUT is supposed to be idempotent - i.e., it should be done many times.  Hence, we should be able to overwrite an existing file; this requires tweaking the existing flags used to open the file.
=> Allow overwrites to be done on PUT.

src/XrdSys/XrdSysIOEvents.cc
cP->dlType is being read outside of the lock. Diagnosed through the
following report from ThreadSanitizer:
WARNING: ThreadSanitizer: data race (pid=13166)
Write of size 1 at 0x7b28000100d0 by thread T29 (mutexes: write M0, write M0, write M1382, write M0, write M1385):
-0 XrdSys::IOEvents::Poller::TmoAdd(XrdSys::IOEvents::Channel*, int) /home/gbitzes/xrootd/src/XrdSys/XrdSysIOEvents.cc:1088 (libXrdUtils.so.2+0x0000000338f1)
-1 XrdSys::IOEvents::Channel::Enable(int, int, char const**) /home/gbitzes/xrootd/src/XrdSys/XrdSysIOEvents.cc:415 (libXrdUtils.so.2+0x0000000355b6)
-2 XrdCl::PollerBuiltIn::EnableWriteNotification(XrdCl::Socket*, bool, unsigned short) /home/gbitzes/xrootd/src/XrdCl/XrdClPollerBuiltIn.cc:481 (libXrdCl.so.2+0x000000063c50)
-3 XrdCl::AsyncSocketHandler::EnableUplink() …
=> [XrdSys] Fix data race on cP->dlType

src/XrdHttp/XrdHttpReq.cc
Originally, HTTP PUT could create but not overwrite.  While fixing
this, the flags were changed -- but it could overwrite and not create!
With this change, I have tested that both overwriting and creating
work.
We likely need additional follow-up because, with this change, a
user cannot perform HTTP PUT with the "create" authorization alone.
=> Another attempt at getting HTTP PUT flags right.  Fix #637

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh
If a HTTP verb (such as COPY) is encountered in an request, the
current code will try to parse subsequent headers as a HTTP status
line (mostly encountering garbage, but sometimes actually succeeding!).
We should instead note that a valid -- but unknown -- verb was encountered
and parse the remaining headers as headers.  This is useful because
external handlers might actually understand verbs (again, COPY) that the
built-in handlers do not.
=> Allow parsing of unknown HTTP verbs.

src/XrdSecpwd/XrdSecpwdPlatform.hh
With the update of glibc to version 2.27 crypt.h is not included recursively by some other include statement any longer but must be included explicitly.
=> Include crypt.h on Linux

cmake/FindReadline.cmake
readline.h uses the `FILE` datatype from stdio.h, without an #include for that system header. Upstream documents that it is the responsibility of any code using readline.h to include that other header itself, and relies on the fact that it is documented to declare that this is not a bug. Some distros patch their readline.h with this dependent #include, but for maximum portability the READLINE compile-test function should do it.
The xroot4 source files that use readline.h have includes for stdio.h (or cstdio) already.
=> readline.h requires stdio.h to be compileable

src/XrdOss/XrdOssRename.cc
=> XrdOss: implement proposed solution for better rename POSIX compliancy

.gitlab-ci.yml
The build is done in the other, specific repository, mirrored to CERN Gitlab
=> [CI] removing ceph plugin build from here

src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh
If a client requested a single byte range which was less than the filesize, then the file handle was never explicitly closed.
When the TCP connection was closed, all open file handles on the bridge are automatically closed too.  Hence, it seems like this is a moot point - a transient "leak".  However, we have observed some clients (particularly: CVMFS) that hold open TCP connections for hours or days, resulting in the "leak" of a file handle per read operation.  In some cases, the number of file handles leaked was in the tens-of-thousands.
In addition to the obvious memory issues, this was observable in the f-stream monitoring as the near-simultaneous closing of 10k file handles caused UDP buffer overflows and dropped monitoring packets.
=> Close file handle for simple HTTP reads.

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh
Previously, we just handed OpenSSL the underlying file descriptor.  This worked fine, protocol-wise.  However, this didn't interact well with the Xrootd framework itself as the idle counter was not update, nor were proper statistics recorded.
With this commit, we create a custom BIO object for OpenSSL to use; this object simply forwards the requests to an underlying `XrdLink`.
Fixes #675
=> Always have OpenSSL read/write data through the XrdLink object.

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh
Added the **http.cipherfilter** config directive to specify the cipherlist filter string. 
The provided cipherlist filter string will be used when initializing the SSL context.
If the config misses the cipher filter directive, the following default is assumed: "ALL:!LOW:!EXP:!MD5:!MD2"
If the config specifies the directive, but no string or an invalid string is provided, initialization fails with an error message.
The goal is to make it easier to modify the list of permitted ciphers used by the XrdHttp component.
=> Added XrdHttp cipherlist filter string config option

src/XrdFileCache/XrdFileCache.cc, src/XrdFileCache/XrdFileCacheBlacklistDecision.cc
Simplify user code required for implementation of a pfc decision plugin.
Brian and I don't know anybody using this functionality so the change should be safe. In worst case affected users will have to simplify their plugins and recompile them :)
=> [XrdPfc] Pass LFN, not url to PFC decision plugin.

src/XrdCrypto/XrdCryptosslRSA.cc, src/XrdCrypto/XrdCryptosslRSA.hh
This is a partial revert back of commit
https://github.com/xrootd/xrootd/commit/0421bc639e1f1e581e2f597264f445ffa3380660
fixing the problem in a different way, without breaking interfaces.
Should restore proper behaviour when XrdSecGSIDELEGPROXY is set to 2.
=> Fix signatures of XrdCryptosslRSA Export methods

src/XrdCrypto/XrdCryptoX509.cc, src/XrdCrypto/XrdCryptoX509.hh, src/XrdCrypto/XrdCryptosslX509.cc, src/XrdCrypto/XrdCryptosslX509.hh, src/XrdSecgsi/XrdSecProtocolgsi.cc
With this, if the CN doesn't follow the expected matching rules, then the client will iterate through the listed `subjectAltNames` to determine whether the certificate matches the current host.
This includes support for CNs and SANs with wildcards.
One thing I noticed when testing this branch is XRootD is internally still doing a reverse DNS lookup on the IP address it connects to when filling out the `XrdSecEntity` structure.  This is widely considered insecure despite the fact it was commonly done at the grid level until a few years ago.  I'd strongly suggest we remove the reverse DNS lookup on the client side once there's appropriate SAN support.
=> Allow XRootD client to accept subjectAltNames.

tests/common/CMakeLists.txt
Fixes a linking error on macOS when `ENABLE_TESTS` is `ON`:
```
Undefined symbols for architecture x86_64:
"XrdNetUtils::IPFormat(int, char*, int, int)", referenced from:
XrdClTests::Server::HandleConnections() in Server.cc.o
```
My environment is macOS 10.13.3 High Sierra, CMake 3.10.2, XCode 9.2.
This change should not interfere with the Linux build.
=> Fix compilation on Mac with ENABLE_TESTS=ON

src/XrdPosix/XrdPosixXrootdPath.cc
If `XrdPosixXrootdPath::P2L` made an early exit, the variable `relP` wasn't set to 0, triggering a crash in `LfnPath::~LfnPath`.
=> Fix potential crash in XrdPosixXrootdPath::P2L

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh
This change introduces a new method which translates from an Xrd error code into an appropriate HTTP 
status code.
It introduces 2 new private variables in XrdHttpReq: `httpStatusCode` & `httpStatusText`.
`httpStatusCode`: HTTP Status compliant code
`httpStatusText`: the Xrd error text, if present, or a minimal description otherwise
Default values are 500 and "Unrecognized error".
During the request post-processing, the branches which end in an error will send back the status code and text mentioned above.
This pull request addresses issue #713
=> XrdHttp: Xrd error code to HTTP status translation

src/XrdHttp/XrdHttpProtocol.cc
XrdHttp with the http.gridmap on results in a segmentation fault.
The array `bufname[64]` is passed with `127` as the array size to the DN2user translation function.
This eventually generates a segmentation fault as the DN2user function performs memset on the array and the received array size.
This change passes `sizeof(bufname)` for the array size.
Also, the size of the array is increased to 256.
=> XrdHttp: Prevent segmentation fault when using http.gridmap

src/XrdHttp/XrdHttpReq.cc
Hello,
In the following scenario, where the "Stat request" of a file returns a larger size than the actual "read request", the XrdHttp component would enter a loop.
To reproduce this, perform a GET request on a "script file". The stat on the script will return a fixed size (e.g 4096), but upon the read request, the actual output will be different. At this point, XrdHttp enters a loop trying to read the remaining bytes.
In my particular case, I am accessing the `/proc/whoami` script on an EOS system (logs attached).
This change prevents this scenario and abruptly interrupts the HTTP connection.
[xrdhttp.log](https://github.com/xrootd/xrootd/files/2098289/xrdhttp.log)
=> XrdHttp: Prevent loop in scenario where stat request provides larger size than the read request

src/XrdSecgsi/XrdSecProtocolgsi.cc, src/XrdSecgsi/XrdSecProtocolgsi.hh
Fixes #725.  @simonmichal - please test.
If the user provides a non-FQDN (such as `xrootd` instead of `xrootd.cern.ch`), this will detect the situation and use `getaddrinfo` to expand to the canonical name.
Note that the canonical name may be somewhat unexpected as it resolves CNAMEs all the way down to an A record.  For example, if you set your search domain to `unl.edu`, then the canonical name for `www` is not `www.unl.edu` but rather `unlcms-rs.autosplit.its-sys.unl.edu`.
This also allows the environment variable `XrdSecGSITrustDNS` to be set to 0; if it is, all DNS lookups are skipped.
=> Use DNS lookups to expand non-FQDNs

src/XrdCrypto/XrdCryptoAux.cc, src/XrdCrypto/XrdCryptoAux.hh, src/XrdCrypto/XrdCryptoX509.cc, src/XrdCrypto/XrdCryptoX509.hh, src/XrdCrypto/XrdCryptoX509Crl.cc, src/XrdCrypto/XrdCryptoX509Crl.hh, src/XrdCrypto/XrdCryptosslAux.cc, src/XrdCrypto/XrdCryptosslAux.hh, src/XrdCrypto/XrdCryptosslX509.cc, src/XrdCrypto/XrdCryptosslX509.hh, src/XrdCrypto/XrdCryptosslX509Crl.cc, src/XrdCrypto/XrdCryptosslX509Crl.hh, src/XrdSecgsi/XrdSecProtocolgsi.cc
Fixes a bug in processing certificates with dates beyond 2038.
And improves time checks when ca:1 .
=> Use consistently time_t in crypto and related 

src/XrdSecgsi/XrdSecProtocolgsi.cc, src/XrdSecgsi/XrdSecProtocolgsi.hh, src/XrdSut/XrdSutAux.cc
This patch re-organizes how proxy delegation is handled and controlled in GSI, and it adds the possibility to save the proxy in Entity.creds .
On the server side, the two switches controlling delegation have been 'cleaned': the first switch enables or disables delegation, the second determines where the delegated proxy will be saved. The new meanings are:
-dlgpxy:0              no delegated proxy [default]
1              ask the client to sign a delegated proxy request
-exppxy:none       delegated proxy available in memory (via a server calle to getCredentials)
:=creds    delegated proxy available in Entity.creds
:<file_template>  delegated proxy available in the indicated file which can include the
following customization tags: <host>, <vo>, <group>, <user>, <rtag>; e.g. …
=> Restructure GSI proxy delegation options

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh, src/XrdHttp/XrdHttpUtils.cc, src/XrdHttp/XrdHttpUtils.hh, src/XrdXrootd/XrdXrootdXeq.cc
DAVIX et al uses RFC3230 to implement checksumming over HTTP.
This PR implements the RFC to the point where a `gfal-copy` works with the ADLER32 checksum algorithm.
Note that this also contains a bugfix in XrdOfs that prevents checksums from working when the underlying filesystem doesn't support `fattr`s.
=> [XrdHTTP] Implement RFC3230 for providing resource digest

src/XrdTpc/XrdTpcConfigure.cc
Previously, the SFS symbol was loaded from the global namespace instead of the dlopen'd handle, meaning the correct SFS was not actually loaded.
=> Load the SFS symbol from the correct library.

src/XrdThrottle/XrdThrottleFile.cc
Make sure to always set the error member appropriately whenever something besides `SFS_OK` is returned.
Fixes #752
=> Update the throttle plugin to propogate underlying errors.

packaging/rhel/xrootd.spec.in, src/XrdMacaroons/XrdMacaroons.cc
Fixes the build requirements on older Fedora / RHEL and squashes a warning on the Fedora rawhide compiler.
=> [XrdMacaroons] Macaroon build fixes, attempt 2

packaging/rhel/xrootd.spec.in
Fix spelling error in macro from prior build attempt.
Sigh, that's an embarrassing bug!
=> [XrdMacaroons] Macaroons / GitLab build fixes, attempt 3

CMakeLists.txt, src/XrdApps.cmake, src/XrdCl/CMakeLists.txt, src/XrdClient.cmake, src/XrdCrypto.cmake, src/XrdDaemons.cmake, src/XrdHttp.cmake, src/XrdMacaroons.cmake, src/XrdPosix.cmake, src/XrdSec.cmake, src/XrdServer.cmake, src/XrdTpc.cmake, src/XrdUtils.cmake, tests/common/CMakeLists.txt
=> Replace 'dl' with ${CMAKE_DL_LIBS} to make it work on systems without libdl

src/XrdTpc/XrdTpcConfigure.cc
Add comments to prevent future confusion over how this line is parsed.
Prior to this, a `xrootd.fslib` line that specifies a plugin chain:
```
xrootd.fslib /usr/lib64/libXrdMultiuser.so default
```
would not actually create the base default plugin.
=> [XrdTpc] Fix order of chaining when parsing xrootd.fslib.

src/XrdThrottle/XrdThrottleFile.cc, src/XrdThrottle/XrdThrottleFileSystem.cc
This fixes a few cases where the presence of the `XrdThrottle` plugin subtly changes the semantics of how the error object is updated.
Most importantly, it fixes the `fctl` command for non-sendfile cases and properly chains the directory object.
=> [XrdThrottle] Improve chaining behavior of throttle plugin.

src/XrdHttp/XrdHttpExtHandler.cc, src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh
Additionally, if the client is making a HTTP/1.0 request, make sure
to disable keepalive by default.
Fix #809 
@ffurano
=> Obey the `Connection` request header.

src/XrdOfs/XrdOfsHandle.cc, src/XrdSys/XrdSysPthread.hh, src/XrdXrootd/XrdXrootdTransit.cc
=> Fix callback of protocol plugin after bridge delay

src/XrdHttp/XrdHttpReq.cc
The `filesize` member was not being reset between requests.  If it is non-zero, the `XrdHttpReq` object uses the size when parsing header to potentially reduce the total read size (preventing it from going past the EOF).
Unfortunately, since the `filesize` was set to the size of the *previous* file transfer, this could cause the total response size to be less than the request, resulting in a shorter-than-expected response to the client.
=> [XrdHttp] Reset filesize when the XrdHttpReq object is used.

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpReq.cc
This fixes two problems in the XrdHttp request state:
1.  The callback counter was incorrectly incremented when partial headers were received, meaning the state machine was invalid.
2.  The return code for `strcasecmp` was incorrectly checked, making the code often assume `sha1` was requested.
=> Fixes for XrdHttp request state issues

src/XrdHttp/XrdHttpExtHandler.cc, src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh, src/XrdOfs/XrdOfsHandle.cc, src/XrdSys/XrdSysPthread.hh, src/XrdXrootd/XrdXrootdTransit.cc
This is a backport of #811, #812, and #814; we see these as critical fixes for HTTP in support of our LIGO caches.
=> Backport HTTP fixes

src/XrdXrootd/XrdXrootdXeq.cc
This generates the correct error message and return code on the error case prior to deleting the file pointer object.  Avoids a SEGV observed in testing when the file close failed.
Fixes #818
=> Avoid SEGV when the close operation fails.

src/XrdHttp/XrdHttpProtocol.cc
I misinterpreted the return code of `XrdLink::Send`; this fixes the return code parsing and a copy/paste error.
@abh3 - would it be possible to get some inline documentation for the `XrdLink::Send` method?
=> Fix return code checks.

src/XrdFileCache/XrdFileCache.cc, src/XrdFileCache/XrdFileCache.hh, src/XrdFileCache/XrdFileCacheConfiguration.cc, src/XrdFileCache/XrdFileCachePurge.cc
* Make sure not to call XrdOucStream::GetWord() again after it returns 0.
* Fix logging initialization to survive log rotation.
* Fix logic for purging below nominal file usage when file usage limits are in force.
* Add traces to Purge() about files not removed due to activity protections.
=> [Pfc] Couple of fixes from extended testing

src/XrdHttp/XrdHttpProtocol.cc
If the server got incomplete headers (I was able to reliably trigger this with connection reuse), the `reqstate` variable was still incremented.
This resulted in the request state becoming inconsistent - notably, for master, we saw `HEAD` requests believed they always included a checksum.  There are likely other strange XrdHttp behaviors that could have been triggered due to the same bug, hence the request for backport to the stable branch.
(cherry picked from commit 88dad6ab1a1062749ba5e9ca5e0e9b98acbcddab; backport of relevant fix in #822)
=> Do not increment reqstate when headers are incomplete.

src/XrdFileCache/XrdFileCache.cc, src/XrdFileCache/XrdFileCache.hh, src/XrdFileCache/XrdFileCacheFile.cc, src/XrdFileCache/XrdFileCacheFile.hh, src/XrdFileCache/XrdFileCacheIO.hh, src/XrdFileCache/XrdFileCacheIOEntireFile.cc, src/XrdFileCache/XrdFileCacheIOEntireFile.hh, src/XrdFileCache/XrdFileCacheIOFileBlock.cc, src/XrdFileCache/XrdFileCacheIOFileBlock.hh, src/XrdFileCache/XrdFileCacheInfo.cc, src/XrdFileCache/XrdFileCacheInfo.hh, src/XrdFileCache/XrdFileCacheTrace.hh, src/XrdFileCache/XrdFileCacheVRead.cc
This is needed for n2n mapped files and for forwarding-mode
proxies.
Access stats are still collected on per file basis. If several IOs all
read from the same file at overlapping times, these will all be
reported as a single access. This can be improved if needed.
When a block fetch fails on certain IO, other IOs will reissue the
block request. The offending IO will get the error code result
associated with its request. When prefetching, the bad IO will be
removed from the prefetch IO map so it doesn't cause trouble again.
=> Support multiple IO objects working with the same file

src/XrdHeaders.cmake
Exporting the XrdSecsssID.hh header to allow usage of the XrdSecsss Registry from plugins.
=> [CMake] Add XrdSecsss/XrdSecsssID.hh to private headers

src/XrdSecgsi/XrdSecProtocolgsi.cc, src/XrdSecgsi/XrdSecProtocolgsi.hh
Whenever reverse DNS is trusted, this enables the "historical" configuration where the IP address of the connected socket is considered for reverse resolution (and the remote server's DN is compared against the resulting hostname).
IMHO, this is significantly more dangerous than "traditional' reliance on reverse DNS for non-Xrootd cases.  Any attacker that is performing a MITM is able to force the client to accept any valid host certificate.
So, if the attacker controlling DNS could force `foo.example.com` to resolve to attacker-controlled IP address `1.2.3.4` with reverse resolution of `badguy.io`, the client would accept the connection as long as `badguy.io` has a certificate from a valid authority.
Fix #841
=> Always fall back to reverse DNS if trusted

src/XrdTpc/XrdTpcTPC.cc
By default, libcurl uses signal handlers to implement timeouts for both DNS requests and data transfers.  This obviously does not work well within XRootD, but wasn't noticed until I put things under
additional load.
=> Request curl to not install its own signal handlers.

src/XrdTpc.cmake, src/XrdTpc/XrdTpcMultistream.cc, src/XrdTpc/XrdTpcState.cc, src/XrdTpc/XrdTpcState.hh, src/XrdTpc/XrdTpcStream.cc, src/XrdTpc/XrdTpcStream.hh, src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh
This allows more requests to be in-flight to the server than the number of concurrent TCP connections.
=> Utilize pipelining support in libcurl

src/XrdSecgsi/XrdSecProtocolgsi.cc, src/XrdSecgsi/XrdSecProtocolgsi.hh
=> support signing of server DH public parameters

src/XrdSys/XrdSysPthread.hh
Addresses issue https://github.com/xrootd/xrootd/issues/846
Note I have left the check on whether or not to use the fallback code based on whether or not `CLOCK_REALTIME` is defined. A possible alternative check would be on the system version, e.g.
```
#if __APPLE__ && __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ < 101200
...
#endif
```
Its not obvious to me which is better, so I have left it as per my original version.
Also, this PR is against the `stable-4.8.x` branch. Hope this is OK. You should be able to cherry pick it to `master` as well if required.
=> [XrdSys] Fix use of clock_gettime on pre OSX10.12 systems

src/XrdCrypto/XrdCryptosslgsiAux.cc, src/XrdSecgsi/XrdSecProtocolgsi.cc
restore the original using of X509_NAME_dup(X509_get_subject_name(xpi))
change the way X509_EXTENSION (stack) is freed
included Gerri Ganis's patch to clean up proxyChain.
=> more on memory leaks

src/XrdCrypto/XrdCryptoCipher.cc, src/XrdCrypto/XrdCryptoCipher.hh, src/XrdCrypto/XrdCryptoFactory.cc, src/XrdCrypto/XrdCryptoFactory.hh, src/XrdCrypto/XrdCryptosslCipher.cc, src/XrdCrypto/XrdCryptosslCipher.hh, src/XrdCrypto/XrdCryptosslFactory.cc, src/XrdCrypto/XrdCryptosslFactory.hh, src/XrdCrypto/XrdCryptosslRSA.cc, src/XrdSecgsi/XrdSecProtocolgsi.cc, src/XrdSecgsi/XrdSecProtocolgsi.hh
Support is is automatically detected (assuming the supports means openssl v >= 1.0.2), also when talking to old clients/servers
=> Add padding support in ciphers

src/XrdHttp/XrdHttpReq.cc
According to the HTTP spec, the response from a "Range" request should have a
"content-range" header in the form of "range_begin-range_end/doc_length". But
xrootd currently returns the length of the range intead of the range of the whole
file. Pass in the length of the file and additionally change the printf string since the
file size is stored in a long long
=> Return correct content-range header

src/XrdHttp/XrdHttpExtHandler.cc, src/XrdHttp/XrdHttpExtHandler.hh, src/XrdVersionPlugin.hh
I integrated XrdHttp into EOS/MGM, but I missed access to the query CGI in the external handler. Would be great to have this added to 4.9, otherwise this external handler is really sort of useless. Otherwise performance looks great!
=> xrdhttp: expose query string in external req handler

src/XrdCrypto/XrdCryptoCipher.cc, src/XrdCrypto/XrdCryptoCipher.hh, src/XrdCrypto/XrdCryptosslCipher.cc, src/XrdCrypto/XrdCryptosslCipher.hh, src/XrdSecgsi/XrdSecProtocolgsi.cc, src/XrdSecgsi/XrdSecProtocolgsi.hh
Enable use of a unique IV randomly generated instead of a zeroed one.
=> Enable use of an unique IV in enc/dec cipher operations

src/XrdHttp/XrdHttpProtocol.cc
Tell the bridge whether the connection came in using HTTPS or HTTP; this way, monitoring packets can differentiate the two protocol types.
=> Report the correct protocol name to the bridge.

src/XrdHttp/XrdHttpReq.cc
Intended to help us debug the source of some intermittent checksum errors.
=> [HTTP] Provide error messages when checksum calculations fail.

src/XrdHttp/XrdHttpExtHandler.cc
This is really sort of ugly, but there is no better way without breaking the ABI and if one cannot return data in portions, I cannot return files larger then few MB. I use two non existing HTTP codes to do this (0 = StartResponse 1=SendData) . If you have a better idea, let me know.
=> XrdHttp: allow to use StartSimpleResp and SendData without breaking ABI

src/XrdMacaroons/XrdMacaroonsHandler.cc, src/XrdMacaroons/XrdMacaroonsHandler.hh, src/XrdMacaroons/macaroon-init
This PR implements the OAuth 2.0 client credentials workflow for acquiring a macaroon.  This provides a more standards-based approach to token acquisition compared to the existing method developed by @paulmillar, which has served us well but is admittedly a bit more ad-hoc.  With this PR, both the old method and new method ought to work.
This approach was originally implemented in StoRM by @andreaceccanti.  I wanted to have a second server implementation prior to doing the client side changes for FTS.
This is NOT meant for 4.9.0.
=> OAuth2-based Macaroon acquisition

src/XrdTpc/XrdTpcMultistream.cc, src/XrdTpc/XrdTpcState.cc, src/XrdTpc/XrdTpcState.hh, src/XrdTpc/XrdTpcStream.cc, src/XrdTpc/XrdTpcStream.hh
Previously, the underlying OFS file handle was not closed until the destructor on the XrdTpcStream object was called - this occurs _after_ the response was sent to a client.
In this case, subsequent operations may be done while the file is still open for writing, which may mean data has not been written out from the client cache to the distributed file system.  If the subsequent operation (such as `stat`) is load-balanced to a different data server, then the second operation may observe an incomplete file.
The fix is to explicitly cause the file handle to be closed prior to sending the response to the client.  Then, as long as the filesystem has open-to-close consistency (which NFS and HDFS do have -- a much looser consistency requirement than POSIX), this should remove the possibility of …
=> [TPC] Ensure file is closed prior to sending response to client

src/XrdHttp/XrdHttpExtHandler.cc, src/XrdHttp/XrdHttpProtocol.hh
There is only a 'getter' function added to the header file and I am not sure, if this breaks ABI compatibility of the shared library. This could be postponed to version 5. It is important to know, if a call comes via a 'secure' connection or not in the plug-in.
=> XrdHttp: add the used protocol (https/http) as a special header i

src/XrdFileCache/XrdFileCacheConfiguration.cc
Also mention a mistake in oss.locaroot directive might be the culprit.
Please also include this for 4.9.x (for 4.9.0, if possible).
=> Check data space size during configuration processing.

src/XrdTpc/XrdTpcTPC.cc
We do not support any Credential header value except `none`.
Instead of ignoring this header altogether, we should fail the transfer if the client has requested a mode we do not support.
=> Handle the Credential header for COPY requests.

src/XrdHttp/XrdHttpReq.cc
=> Don't assume that a header "Depth: 1" means that the resource is a dir

src/XrdSecgsi/XrdSecProtocolgsi.cc
This PR contains mostly fixes to improve debugging (including the change requested by issue #909) and a fix affecting the option to save the delegated proxy to a file (which is not used by TPC, though).
It would probably make sense to port this to stable-4.9.x and include it in 4.9.1 .
=> Debug fixes for secgsi

src/XrdCl/CMakeLists.txt, src/XrdFileCache/XrdFileCachePrint.cc, src/XrdMacaroons/XrdMacaroonsHandler.cc, src/XrdOfs/XrdOfsTPC.hh
Compilation fails on 32 bit architectures:
```
/builddir/build/BUILD/xrootd-4.9.0/src/XrdMacaroons/XrdMacaroonsHandler.cc: In member function 'int Macaroons::Handler::GenerateMacaroonResponse(XrdHttpExtReq&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, ssize_t, bool)':
/builddir/build/BUILD/xrootd-4.9.0/src/XrdMacaroons/XrdMacaroonsHandler.cc:501:16: error: format '%lu' expects argument of type 'long unsigned int', but argument 2 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
printf("Returned macaroon_serialize code: %lu\n", size_hint);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~  ~~~~~~~~~
```
Compilation fails on architectures where "char" is unsigned by default (ppc64, ppc64le, arm, aarch64, s390x):
``` …
```
=> Fix compilation errors

src/XrdMacaroons/XrdMacaroonsHandler.cc, src/XrdMacaroons/XrdMacaroonsHandler.hh
Fixes #921 
With this, if the user specifies additional limitations (such as limits on activities) as part of the macaroon request, the corresponding log line is:
```
190314 13:02:46 133614 sysMacaroonGen: \
ID=893f6d10-4b91-4f00-8c5e-5fd0d9fcecf8, host=[<ipv6 address>], \
base_activities=activity:READ_METADATA, user_caveat=activity:READ, expires=2019-03-14T18:12:46Z
```
=> Log user caveats with macaroon generation.

src/XrdHttp/XrdHttpReq.cc
This fixes a potentially bad bug if pipelining is in use: in the callback for `PUT`, we write out ALL data present in the socket, regardless if it belongs to the current HTTP request - or is the beginning of the next pipelined request!
Things were handled correctly before if there was no pipelining (or the client didn't send too much data or the extra data the client sent happened to be split over multiple TCP packets).
Fixes #916
=> Do not accept more data than specified in the HTTP request.

src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh
This is the first step in fixing #915 - we should at least respond correctly when we don't support something!
=> XrdHttp does not support chunked encoding; respond appropriately.

src/XrdHttp/XrdHttpReq.cc
This takes the first checksum type that Xrootd recognizes and only calculates that.
It improves RFC compliance by allowing Xrootd to properly parse multiple checksum requests in a single `Want-Digest` header.
Before,
```
Want-Digest: md5,adler32
```
would result in Xrootd trying to calculate a checksum named `md5,adler32`.  After, given `md5` is a known checksum type, it will request a checksum for `md5`.
=> Handle clients that request multiple checksums.

src/XrdXrootd/XrdXrootdProtocol.cc
I've implemented async response on close in EOS but this doesn't work with 4.9.0 due to the wrong request ID being sent by the server in the final close response.
=> [Server] Save the proper ReqID for async responses on close

src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh
This adds support for clients who would like to PUT files via chunked encoding.
Fixes #915
=> XrdHTTP: Support chunked encoding for PUT

src/XrdTpc/XrdTpcTPC.cc
Ensure the opaque information is passed along with the resource name to the OFS.
Fixes #932.
=> Pass along opaque info for TPC.

src/XrdMacaroons/XrdMacaroonsHandler.cc, src/XrdMacaroons/XrdMacaroonsHandler.hh
The new OAuth2-style of macaroon requests caused incorrect caveats to be requested - permissions were broken up across multiple caveats instead of in a single request.
Further, it requested the macaroon for the wrong path (the OAuth2 token issuer path) and this is fixed too.
Relatively safe, should be backported to 4.9.1.
=> Create macaroon with proper caveats and path.

src/XrdHttp/XrdHttpProtocol.cc
We're seeing climbing xrootd memory usage on a local redirector. From some initial debugging, it seems due to XrdHttpProtocol buffers. This patch frees the 1MB buffer when the XrdHttpProtocol objects are idle.
The HTTP protocol handler keeps a stack of idle XrdHttpProtocol objects in ProtStack. The stack depth is limited to ConnMax/3, and ConnMax is set to RLIMIT_NOFILE. Each idle handler holds a 1MB buffer. When LimitNOFILE is increased to 65k for better concurrency, it's possible to have ~21k XrdHttpProtocol objects in ProtStack for a total of ~21GB RAM allocated to buffers. This seems unexpectedly high, especially for redirectors.
Rather than adding another configuration knob to limit the memory usage, we could free the 1MB buffer when the object is idle. With XrdBuffManager already …
=> XrdHttp: High memory usage apparently from cached XrdHttpProtocol objects

src/XrdTpc/XrdTpcState.cc
Curl's detection of low-speed transfers creates a flood of timeout calls which significantly slows large transfers and increases CPU usage. This is fixed in https://github.com/curl/curl/commit/cacdc27f52 which is unfortunately not present on EL7.
This PR checks the curl version and only enables the low-speed detection when libcurl is new enough to have the fix.
Trying this patch on a production EL7 xrootd server which handles TPC requests, there was a significant drop in xrootd CPU usage: from ~100% busy, down to ~5%.
To see if the system is likely being affected, look for the function `Curl_speedcheck` appearing frequently in the gstack output for `xrootd`.
=> [XrdTpc] Only use Curl's low-speed-limit with libcurl v7.38 and later

src/XrdMacaroons/XrdMacaroonsAuthz.cc, src/XrdMacaroons/XrdMacaroonsAuthz.hh, src/XrdMacaroons/XrdMacaroonsConfigure.cc, src/XrdMacaroons/XrdMacaroonsHandler.hh
With this, the admin can set a new `macaroons.onmissing` configuration flag to allow the authorization plugin to always allow in the case when no macaroon exists.
This is useful for EOS as EOS does not utilize the XRootD authorization system and will apply its own authorizations downstream of this plugin.
Additionally, this fixes a memory leak of the macaroon object that occurs on successful validation.
=> Allow admin to customize default macaroons authz.

src/XrdHttp/XrdHttpReq.cc
Apparently GCC only can handle the `fallthrough` comment (and skip a warning) if it is the last statement before the next case.
Fixes build failures due to #902 on GCC7+ platforms such as Fedora and latest Debian.
=> Fixup fallthrough statements.

src/XrdMacaroons/XrdMacaroonsAuthz.cc, src/XrdMacaroons/XrdMacaroonsHandler.cc
When testing 4.9.1-rc1, @jthiltges reported that `macaroons.onmissing` had undefined behavior if it was not set in the configuration file (unfortunately, the undefined behavior for my test platforms was the same as the expected behavior ... but not in production!).
Since I was hitting the codebase with valgrind, this PR also fixes two minor memory leaks and one uninitialized read.
@simonmichal - please backport for 4.9.1 final!
=> [XrdMacaroons] Fix default for `macaroons.onmissing`

src/XrdHttp/XrdHttpReq.cc
Testing 4.9.1-rc2, @matyasselmeci noted that HTTP output prepends a `\r\n` to the expected contents.
@bbockelm was able to isolate the issue and suggested the patch in this PR.
This would be helpful to have in RC3. @simonmichal
Example:
xrootd-4.9.1-0.1.rc1.osg34.el7.x86_64
```
$ curl -s -k -E /tmp/cert.pem 'https://xrootd.example.edu:1094/hello_world.txt' | hexdump -C
00000000  68 65 6c 6c 6f 20 77 6f  72 6c 64 21 0a           |hello world!.|
0000000d
```
xrootd-4.9.1-0.2.rc2.osg34.el7.x86_64
```
$ curl -s -k -E /tmp/cert.pem 'https://xrootd.example.edu:1094/hello_world.txt' | hexdump -C
00000000  0d 0a 68 65 6c 6c 6f 20  77 6f 72 6c 64           |..hello world|
0000000d
```
=> [XrdHttp] Don't add blank header if m_digest_header is empty

bindings/python/setup_standalone.py
This is useful in the case where there is already an xrootd install but
it does not include the python portion.  This happens e.g. if xrootd is
installed in a python2 context and the user wants also to use it for
python3.  One can simply download the source and run in this directory:
`python setup_standalone.py install`
This is more or less the same as `setup_pypi.py` but it uses whatever install location is given by `xrootd-config` output, and also is python3-compatible.  Let me know if you would prefer to just spruce up that file instead.
=> Add standalone pyxrootd setup script

src/XrdFileCache/XrdFileCache.cc, src/XrdFileCache/XrdFileCache.hh, src/XrdFileCache/XrdFileCacheConfiguration.cc
pfc.writequeue max-num-blocks-per-loop num-threads
Where:
- max-num-blocks-per-loop Number of blocks taken off the write queue and written to disk in a single iteration of the disk-writer loop.
- num-threads Number of threads that perform writing of cache blocks to disk.
Defaults:  pfc.writequeue 1 1
=> [XCache]  Implement write-queue number of blocks / threads config options. 

src/XrdCms/XrdCmsBaseFS.hh, src/XrdCms/XrdCmsConfig.cc
@abh3 I would like to test this as a temporary fix to avoid duplicating entries in a cache cluster. Can you please review this and think through if this is sufficient and not too dangerous?
I plan to combine it with a static redirect to federation on ENOENT.
=> Allow cms.dfs retries to be set to 0.

src/XrdTpc/XrdTpcTPC.cc
If we open a file using the SFS interface, the OFS plugin will, by default, only query for servers that support IPv6.  If a cluster only has IPv4 addresses, then this will always fail.
This changes the default to dual-stack: the transfer can be serviced by a server that speaks either IPv4 or IPv6 (or both!).  This is likely the best we can do as we have no indication of whether the source side is IPv4, IPv6, or dual stack itself.
Fixes #968
=> Always query dual stack for HTTP TPC.

src/XrdFileCache/XrdFileCacheFile.cc, src/XrdFileCache/XrdFileCacheInfo.hh
Check for errors during XrdOssFile::FSync - do not write cinfo file if it fails.
=> [XCache] Fix FSync error code checking

src/XrdHttp/XrdHttpExtHandler.cc, src/XrdHttp/XrdHttpReq.cc, src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh
If opaque information is given by the user as part of the URL (i.e., `GET /foo?bar=1`), then include this opaque information in the redirection string.
Previously, opaque information was dropped and only the resource was used.  This is problematic in cases where the opaque information contains important authorization details (think: signed URLs).
Additionally, the TPC handler is updated to perform correctly in this situation.
With this PR, if `http.header2cgi Authorization authz` is set in the configuration, the token will be moved from the headers to the opaque information _and_ now included in the redirect.  Thus, clients which drop the `Authorization:` header upon redirect (this includes the latest versions of `curl`!) will now work by default with an Xrootd cluster.
Fixes behavior …
=> Include provided opaque information in the redirection

.gitlab-ci.yml, packaging/debian_scripts/publish_debian_cern.sh
1. Refactors the Ubuntu build template to accept two parameters:
- DIST [string] -- the distribution name (e.g.: bionic)
- DEBUG [true or not] -- whether to publish debug packages as well
2. Introduces Ubuntu disco build to the CI pipeline.
=> Ubuntu disco CI build

.gitlab-ci.yml
Should fix invalid gitlab-ci.yaml syntax.
Changed occurrences of the word _true_ with the string "true".
Environment variables are expected to be strings, whereas _true_ is a dedicated boolean keyword in yaml, resulting in an invalid syntax.
=> Ubuntu disco CI Build - part 2

.gitlab-ci.yml
Perform a version compare on the dpkg package and include the  "--buildinfo-option" argument only if dpkg version >= 1.1.8.11 (first version which introduced "--buildinfo-option")
=> Ubuntu disco CI build - part 3

.gitlab-ci.yml
Previous commit failed because "dpkg --compare-versions" sets the exit code to 1 when the condition is not met. However, the CI environment exists on any non-zero exit code.
Exit code of "dpkg --compare-versions" should now be captured into the **rc** variable.
=> [CI] Capture exit code of "dpkg --compare-versions" into variable

src/XrdSecgsi/XrdSecProtocolgsi.cc
This aims at fixing #976.
@gganis : I think we can simply use `UsrProxy` as the tag used to query proxy cache. Alternatively, we could hash the proxy location and create a tag like `Proxy: + hash` (alternative version in the comments). Please let me know which one suits us better!
Michal
=> [XrdSecgsi] Make proxy cache path aware.

src/XrdFileCache/XrdFileCache.cc
This addresses #663.
Note that Write() calls in IO object were already failing with errno = ENOTSUP.
Write access into cache is not supported. If one really wants to open files with write access using the cache as the entry point, they should setup static redirect on write to a suitable location / service.
=> Deny write access to a file in initial Prepare() call.

src/XrdFileCache/XrdFileCache.cc, src/XrdFileCache/XrdFileCache.hh, src/XrdFileCache/XrdFileCacheCommand.cc, src/XrdFileCache/XrdFileCacheConfiguration.cc, src/XrdFileCache/XrdFileCacheFile.cc, src/XrdFileCache/XrdFileCacheFile.hh, src/XrdFileCache/XrdFileCacheIO.hh, src/XrdFileCache/XrdFileCacheIOEntireFile.cc, src/XrdFileCache/XrdFileCacheIOFileBlock.cc, src/XrdFileCache/XrdFileCacheInfo.cc, src/XrdFileCache/XrdFileCacheInfo.hh, src/XrdFileCache/XrdFileCachePrint.cc, src/XrdFileCache/XrdFileCachePurge.cc, src/XrdFileCache/XrdFileCacheTrace.hh, src/XrdFileCache/XrdFileCacheVRead.cc, src/XrdPosix/XrdPosixAdmin.cc, src/XrdPosix/XrdPosixFile.cc, src/XrdPosix/XrdPosixFileRH.cc, src/XrdPosix/XrdPosixMap.cc, src/XrdPosix/XrdPosixMap.hh, src/XrdPosix/XrdPosixPrepIO.cc, src/XrdPosix/XrdPosixXrootd.cc, src/XrdXrootd/XrdXrootdAio.cc
* [XCache] Implement Cache::Unlink(); use it for handling of FSync errors, too.
- Unlink removes specified data file and corresponding cinfo file.
- If a file is currently open, it is put into shutdown mode.
All new Read requests on File fail immediately with ENOENT error code.
* [POSIX] Correct inconsitent errno handling.
* [XCache] Review error handling and bring error codes in sync with POSIX changes.
=> Review and correct error handling in POSIX and XCache, implement XCache::Unlink()

utils/cms_monPerf
reduced all calls to awk and make measurements in parallel (so the time to measure is fixed to 1s)
=> utils/cms_monPerf : simplify and improve

src/XrdHttp/XrdHttpReq.cc
The allocated target buffer for base64 output is sometimes too short, leading to an overrun. (And I suspect it's causing memory corruption with eventual misbehavior and segfaults.)
A hex string may be the same length as the base64 representation. To allow for a terminating null on the base64 string, we need to allocate an additional byte.
```
string abcd
hex 61626364
base64 YWJjZA==
```
=> [XrdHttp] Fix one-byte overrun in Tobase64()

src/XrdMacaroons/XrdMacaroonsAuthz.cc
This PR fixes the macaroon configuration when using macros.  Without it, if the `all.sitename` line contained a macro substitution, then it would not be expanded in some circumstances, leading to failed authorization.
=> Fix macaroon authorization config

src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh
There were a few issues with redirection handling:
- Opaque data in the original URL was being added twice; once quoted and once unquoted.
- The second copy of opaque data duplicated the `?` character
- The `resourceplusopaque` member did not quote arguments in all cases.
=> Fix redirection handling

src/XrdSecgsi/XrdSecProtocolgsi.cc
Fixes following two problems:
1. XrdSecProtocolgsi::Encrypt returns wrong size of encrypted message if initialization vector is being used (the size of initialization vector which is being appended at the beginning of the output buffer is not taken into account)
2.  When initialization vector is being generated and set the sessionKey is being passed its own iv pointer, as a result the initialization vector is first deleted and only then used to set IV. In  more details:
- in here https://github.com/xrootd/xrootd/blob/7f2476ee739f38b34815a55acb1227aff1d4685f/src/XrdSecgsi/XrdSecProtocolgsi.cc#L1090-L1091 we are generating and setting the IV
- however in here: https://github.com/xrootd/xrootd/blob/7f2476ee739f38b34815a55acb1227aff1d4685f/src/XrdCrypto/XrdCryptosslCipher.cc#L984-L1012 we can …
=> [XrdSecgsi] XrdSecProtocolgsi::Encrypt multiple problems

src/XrdTpc/XrdTpcTPC.cc
We were seeing growing memory usage from curl_easy_init() calls in ProcessPullReq() and ProcessPushReq() on a local redirector.
This patch adds curl_easy_cleanup() calls to a few cases where it was needed, especially before RedirectTransfer().
=> [XrdTpc] Add curl handle cleanup on redirections or errors

ups/eupspkg.cfg.sh
Also remove perl bindings option since that option no longer exists.
Disable python bindings because we do not use them and currently they do not work on macOS because clang is used to compile the C++ files and Apple Clang no longer allows that.
=> DM-18697: Disable python bindings

src/XrdPlugins.cmake
Building the latest RC failed on macOS with the error listed below. This is fixed by this patch.
You can see the result of building with/without this patch in the last two builds of: https://github.com/conda-forge/xrootd-feedstock/pull/11
```
[ 10%] Linking CXX shared module libXrdCmsRedirectLocal-4.so
ld: warning: -pie being ignored. It is only used when linking a main executable
Undefined symbols for architecture x86_64:
"XrdNetAddr::Set(char const*, int)", referenced from:
XrdCmsRedirLocal::Locate(XrdOucErrInfo&, char const*, int, XrdOucEnv*) in XrdCmsRedirLocal.cc.o
"XrdNetAddr::XrdNetAddr(int)", referenced from:
XrdCmsRedirLocal::Locate(XrdOucErrInfo&, char const*, int, XrdOucEnv*) in XrdCmsRedirLocal.cc.o
"XrdOucStream::GetFirstWord(int)", referenced from: …
```
=> Fix linking for libXrdCmsRedirectLocal-4.so on macOS

bindings/python/src/PyXRootDFile.cc
If the `XrdCl::File::Read()` call fails, `bytesRead` is not initialized. This leads to a segfault when the buffer is passed to Python `PyBytes_FromStringAndSize()`
Valgrind output for xrootd-4.10.0-1.osg34.el7.x86_64:
```
2019-10-03 19:00:56 ==31606== Conditional jump or move depends on uninitialised value(s)
2019-10-03 19:00:56 ==31606==    at 0x4EC9D64: PyString_FromStringAndSize (in /usr/lib64/libpython2.7.so.1.0)
2019-10-03 19:00:56 ==31606==    by 0x117C57B8: PyXRootD::File::Read(PyXRootD::File*, _object*, _object*) (PyXRootDFile.cc:198)
2019-10-03 19:00:56 ==31606==    by 0x4F1BD3F: PyEval_EvalFrameEx (in /usr/lib64/libpython2.7.so.1.0)
```
=> [Python] Initialize bytesRead in Read() calls

src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpUtils.cc
Urlencode the opaque info that is propagated into a redirection response
=> Extend the urlencoding function to /r and /n

packaging/common/xrootd-standalone.cfg
Including the default `all.export /tmp` interferes with other packages that drop cfg files under `/etc/xrootd/config.d` to set `all.export` paths.
By commenting out the default `all.export /tmp`, the default behavior will be the same, but other packages will be able to install config.d files to specify other `all.export` paths, without automatically including the default `/tmp`.
(The same is true for the other config files, but for now we are mainly interested in the standalone config.)
=> drop default 'all.export /tmp' in standalone cfg

cmake/FindLibUuid.cmake, src/XrdCl/CMakeLists.txt
Libuuid doesn't require a shared library on macOS as the functions are provided by the kernel. Using the shared library [has caused issues on conda-forge](https://github.com/conda-forge/root-feedstock/pull/62#issuecomment-550070120) for ROOT as the `uuid/uuid.h` header provided by `libuuid` conflicts with the one used by the macOS SDK and causes the graphics (cocoa) code to not compile.
Based partly on: https://github.com/cern-fts/davix/pull/27
=> libuuid.${SHEXT} isn't needed on macOS

src/XrdCl/CMakeLists.txt, src/XrdUtils.cmake, src/api_test/CMakeLists.txt
This PR resolves for me compilation issues with OpenSSL 1.1 on MacOS.
=> Use discovered OpenSSL linker libraries

src/XrdHeaders.cmake
When trying to build the xrootd-hdfs plugin (https://github.com/opensciencegrid/xrootd-hdfs) we got the following error[1], we saw that the the file: XrdSfs/XrdSfsGPFile.hh is not installed with the xrootd-server-devel package as one would expect. I think the file is missing in the XrdHeaders.cmake file
[1]
`usr/bin/c++   -std=gnu++11 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -Wall -Werror -O2 -g -DNDEBUG  -Wl,--no-undefined CMakeFiles/xrootd_hdfs_envcheck.dir/src/XrdHdfsEnvCheck.cc.o  -o xrootd_hdfs_envcheck -rdynamic 
In file included from /builddir/build/BUILD/xrootd-hdfs-2.1.7/src/XrdHdfsChecksumCalc.cc:10:0:
/usr/include/xrootd/XrdSfs/XrdSfsInterface.hh:42:34: fatal error: …
=> adding XrdSfsGPFile.hh to XrdHeaders.cmake

src/XrdHttp/XrdHttpUtils.hh, src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh
The `quote` function was copy-pasted into the standalone xrootd-http-tpc package before that package was integrated back into the mainline `xrootd` source code.  Now that XrdTpc is in the same source repo, there's no need for this duplicate function.
Remove it!
@ffurano
=> Remove duplicate version of `quote` function.

src/XrdMacaroons/XrdMacaroonsHandler.cc
This PR aligns the usage of uuid.h header in the [XrdMacaroonsHandler.cc](https://github.com/xrootd/xrootd/blob/master/src/XrdMacaroons/XrdMacaroonsHandler.cc#L7) with [XrdClFileStateHandler.cc](https://github.com/xrootd/xrootd/blob/master/src/XrdCl/XrdClFileStateHandler.cc#L45). I believe the libuuid version should be used in both cases.
Cheers,
Nikola
=> Use uuid.h from libuuid for Macaroons

src/XrdHttp/XrdHttpProtocol.cc
If a gridmap file has been configured, XrdHttp now prefers the already mapped username to the non-mapped one that's coming from a security extractor plugin
=> XrdHttp now prefers the already mapped username to the non-mapped one

src/XrdCms/XrdCmsCluster.cc
error: 'selR.XrdCmsSelector::needSpace' may be used uninitialized in
this function [-Werror=maybe-uninitialized]
=> Fix error with GCC 10 on s390x:

bindings/python/setup.py.in
This commit https://github.com/xrootd/xrootd/commit/fca51b27e2989b033b3ce889929e3d06b5258206 makes it very difficult to relocate the client.
That PR should allow it by specifying an RPATH relative to the python module
=> Python: make rpath relative to the module

src/XrdTpc/XrdTpcState.cc
Curl speed limit is defined directly in KB/s (not total size transferred divided by seconds in time windows).
=> Fix curl speed limit to be really around 10KB/s

src/XrdHttp/XrdHttpProtocol.cc
ECC support is automatically enabled in OpenSSL 1.1+, but must be initialized in 1.0.
From quick testing on CentOS 7, this seems to resolve #1149 for me. Results from HTTPS connections to various versions:
* 4.11.2:
* Protocol  : TLSv1.2
* Cipher    : AES256-GCM-SHA384
* 4.11.3rc1:
* Client: `SSL routines:ssl3_read_bytes:sslv3 alert handshake failure:ssl/record/rec_layer_s3.c:1543:SSL alert number 40`
* Server: `SSL routines:ssl3_get_client_hello:no shared cipher:s3_srvr.c:1435`
* 4.11.3rc1 with this PR:
* Protocol  : TLSv1.2
* Cipher    : ECDHE-RSA-AES256-GCM-SHA384
=> [XrdHttp] Enable elliptic-curve support for OpenSSL 1.0.2+

src/XrdTpc/XrdTpcState.cc, src/XrdTpc/XrdTpcState.hh, src/XrdTpc/XrdTpcStream.cc, src/XrdTpc/XrdTpcStream.hh, src/XrdTpc/XrdTpcTPC.cc
Importantly, if the passive endpoint provides a reasonable error messages, this is now passed along to the TPC client.
=> Improve HTTP-TPC error messages.

src/XrdTpc/XrdTpcMultistream.cc, src/XrdTpc/XrdTpcState.cc, src/XrdTpc/XrdTpcState.hh, src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh
This will provide the TPC monitoring with information about whether IPv4 and/or IPv6 are being used.
Example perf marker including connection info:
```
Perf Marker\n
Timestamp: 1537788010\n
Stripe Index: 0\n
Stripe Bytes Transferred: 238745\n
Total Stripe Count: 1\n
RemoteConnections: tcp:129.93.3.4:1234,tcp:[2600:900:6:1301:268a:7ff:fef6:a590]:2345\n
End\n
```
=> Include a list of connections in the HTTP-TPC performance marker.

src/XrdTpc/XrdTpcConfigure.cc, src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh
The XRootD framework now exports the global SFS object to the environment (which is available to the HTTP-TPC plugin).  This switches HTTP-TPC to use that object instead of loading a separate copy of the filesystem.
=> Have HTTP-TPC reuse the SFS from the environment.

src/XrdTpc/XrdTpcConfigure.cc, src/XrdTpc/XrdTpcMultistream.cc, src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh
Try to consistently give a machine-readable format that is friendly to tools like `grep`.
Example messages (split over lines for human readability):
```
200315 14:21:06 1875839 TPC_PullRequest: event=PULL_START, \
local=/home/bbockelm/hello_world_copy.txt, \
remote=http://example.com:8000/hello_world_copy.txt, \
user=(anonymous); Starting a push request
200315 14:21:06 1875839 TPC_PullRequest: event=OPEN_FAIL, \
local=/home/bbockelm/hello_world_copy.txt, \
remote=http://example.com:8000/hello_world_copy.txt, \
user=(anonymous), streams=2, status=401; \
Unable to create /hello_world_copy.txt; permission denied
```
Fixes #1049
=> Overhaul logging approach for TPC

src/XrdHttp/XrdHttpReq.cc
Per the WebDAV spec, the correct MKCOL response for when a collection already exists is 405.
Without this fix, `gfal-mkdir` interprets the `EEXISTS` response to `MKCOL` as a file-not-found.  This causes the client to attempt to make the parent directory.
This fixes a race condition in FTS that we've been triggering on occasion with this pattern:
```
- Client 1 does a stat on path `/foo/bar`; file-not-found is returned
- Client 2 does a stat on path `/foo/bar`; file-not-found is returned
- Client 1 does a mkdir on path `/foo/bar`; successful!
- Client 2 does a mkdir on path `/foo/bar`; file-not-found is returned (due to this bug).
- Client 2 does a mkdir on path `/foo`; permission denied is returned.
- Client 2 tells the user the permission is denied.
```
So client 2 returns a permission …
=> Fix MKCOL response when we have an EEXIST.

src/XrdMacaroons/XrdMacaroons.cc, src/XrdMacaroons/export-lib-symbols
@esindril - I think this would work for EOS, at least for Xrootd5.
=> When possible, use the built-in chaining featured in Xrootd 5.

src/XrdHttp/XrdHttpProtocol.cc
From XRootD-4 to XRootD-5 a piece of the code was removed, and that makes the http protocol to think that the role of a node is “Manager” when in reality is “Server” which makes a GET request to look like an error and the code fails in this particular line:
https://github.com/xrootd/xrootd/blob/master/src/XrdHttp/XrdHttpReq.cc#L2082
=> bring old removed code back to set myRole correctly for the http protocol

src/XrdAcc/XrdAccEntity.hh
When one `vorg` is provided and no groups are provided, the `grup` data memeber may be uninitialized on use.  This has resulted in periodic segfaults on the SciTokens ACC provider; I'm guessing that `grup` quite often has an initial value of `nullptr`, even when uninitialized.
I suspect this hasn't been observed for the VOMS provider because all VOMS server implementations create at least one group; hence this case is never hit.
=> Initialize the XrdAccEntityInfo structure.

bindings/python/setup.py.in, bindings/python/src/PyXRootDModule.cc
Conda-forge is current adding support for [PyPy](https://www.pypy.org/features.html) to as many packages as it can. As I work on some projects where PyPy might be useful I took a look at fixing the XRootD build and it turned out to be very simple. This PR includes the necessary patch.
See also: https://github.com/conda-forge/xrootd-feedstock/pull/19
=> Support PyPy

src/XrdHttp/XrdHttpProtocol.cc
The session cache breaks the built-in X509 client authentication; disable it until we have the time to implement a real cache.
Doing this as a one-off against the stable branch as master has significantly diverged in how it handles the `SSL_CTX`.
Builds fine on CentOS 6; from some sleuthing, it seems this API was present in OpenSSL 1.0.2.
=> Disable session cache (stable)

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh
This is a backport of #1183 (plus some `#ifdef`'s so it can compile on SL6).
This uses a per-SSL-object certificate store (shared via ref counts) in order to provide verification functions.  A helper task periodically loads a fresh copy of the cert store.
=> Periodically reload verify cert store (stable)

docs/man/xrdmapc.1, src/XrdApps/XrdMapCluster.cc
The short option for --list is -l, not -1. The code that defines the
option is src/XrdApps/XrdMapCluster.cc line 481:
{OPT_TYPE "list",      1, 0, (int)'l'},
$ xrdmapc -1
xrdmapc: Invalid option, '-1'.
$ xrdmapc -l
xrdmapc: '-l' argument missing.
Add a zero-width space (\&) before 'all' at the start of the line, so
that the apostrophe at the start of the line is not interpreted as a
macro.
Fixes rpmlint warning:
$ rpmlint xrootd-client
xrootd-client.x86_64: W: manual-page-warning /usr/share/man/man1/xrdmapc.1.gz 21: warning: macro `all'' not defined
1 packages and 0 specfiles checked; 0 errors, 1 warnings.
Also fixes broken rendering of the man page where the line with the
unknown macro is ignored.
Original:
OPTIONS
-1 | --list [all|m|s]
-q | --quiet
Does not print error messages to cerr; …
=> Make the xrdmapc help text and manpage match the code.

src/XrdCl/CMakeLists.txt, utils/xrootd-config
cc: @bbockelm 
(seen in https://github.com/bbockelm/xrdcl-authz-plugin)
```
[ 75%] Building CXX object CMakeFiles/XrdClAuthzPlugin-.dir/src/XrdClAuthzPlugin.cc.o
In file included from /home/oksana/CERN_sources/xrdcl-authz-plugin/src/XrdClAuthzPlugin.cc:4:
/home/oksana/CERN/xrootd-HEAD/include/xrootd/XrdCl/XrdClPlugInInterface.hh:30:10: fatal error: XrdCl/XrdClOptional.hh: No such file or directory
30 | #include "XrdCl/XrdClOptional.hh"
```
=> Install missing in installation directory header file XrdCl/XrdClOptional.hh

docs/man/libXrdVoms.1
- replace libXrdSecgsiVOMS with libXrdVoms in the man page text
- end all .nf (no fill) sections with .fi (fill)
- correct the header file names in the FILES section
- use __VERSION__ in .TH as in other man pages
=> Updates to the libXrdVoms.1 man page:

src/XrdPfc/XrdPfc.cc, src/XrdPfc/XrdPfc.hh, src/XrdPfc/XrdPfcConfiguration.cc, src/XrdPfc/XrdPfcFile.cc, src/XrdPfc/XrdPfcFile.hh, src/XrdPfc/XrdPfcIOFileBlock.cc, src/XrdPfc/XrdPfcIOFileBlock.hh, src/XrdPfc/XrdPfcInfo.cc, src/XrdPfc/XrdPfcInfo.hh, src/XrdPfc/XrdPfcPurge.cc, src/XrdPfc/XrdPfcStats.hh, src/XrdPfc/XrdPfcVRead.cc
- Implement pfc g-stream file_close reporting.
- Align buffers to page size.
- Reuse 5% of ram of buffers.
- Collect statistics of ram / write queue usage in bytes.
=> [pfc] g-stream file_close & write queue mem handling

packaging/common/xrootd-filecache-clustered.cfg, packaging/common/xrootd-filecache-standalone.cfg, packaging/common/xrootd-http.cfg, src/XrdHttp/xrootd-http-rdr.cf, src/XrdHttp/xrootd-http.cf
Don't use versioned plugin names in configuration.
Using libXrdXxxx-4.so doesn't make sense for xrootd 5.
Use "pss.cachelib default" in the filecache configuration files.
This way the config files can be used by both the xrootd 5 server and the xrootd 4 server provided by the xrootd-compat package.
=> No version in cfg

src/Xrd/XrdLink.cc, src/XrdCl/XrdClMetalinkRedirector.hh, src/XrdCl/XrdClSIDManager.cc, src/XrdCl/XrdClUtils.cc, src/XrdCl/XrdClXRootDResponses.cc, src/XrdSsi/XrdSsiClient.cc
Fix -Wmisleading-indentation warnings
Fix -Wpessimizing-move warnings
=> Compiler warnings

src/XrdPfc/XrdPfcInfo.cc
Avoid division by zero in cinfo access record merging when file is accessed over 20-times in a second.
=> [pfc] Safe score computation when merging cinfo access records

src/XrdHttp/XrdHttpProtocol.cc
Fixes #1176 
Thanks to Elvin for testing on eospps
Please consider backporting this commit and the previous ones to the current prod branch
=> Shutdown the connection in the case of an unrecognized HTTP first line

src/XrdCl/XrdClFileSystemOperations.hh
This PR fixes a bug in `XrdCl::StatFsImpl`  which is currently calling `RmDir` instead of `Stat`
=> [XrdCl] Fixed XrdCl::StatFsImpl

src/XrdCl/XrdClOperationHandlers.hh, tests/XrdClTests/OperationsWorkflowTest.cc
This PR fixes a bug in XrdCl::TaskWrapper template specialization which disallows creation of std::packaged_tasks for operations which do not require arguments.
Add the following code to the `tests/XrdClTests/OperationsWorkflowTest.cc` file:
```
void WorkflowTest::MkDirAsyncTest() {
using namespace XrdCl;
FileSystem fs{"/"};
std::packaged_task<void(XrdCl::XRootDStatus & st)> mkdirTask{
[](XrdCl::XRootDStatus &st) {
if (!st.IsOK())
throw XrdCl::PipelineException(st);
}};
auto &&t = Async(MkDir(fs, "MkDirAsyncTest", XrdCl::MkDirFlags::None,
XrdCl::Access::Mode::UR | XrdCl::Access::Mode::UW |
XrdCl::Access::Mode::UX | XrdCl::Access::Mode::GR |
XrdCl::Access::Mode::GW | XrdCl::Access::Mode::GX) >> mkdirTask);
CPPUNIT_ASSERT(t.get().status == stOK);
}
```
Compilation of this test fails with: …
=> Fixed TaskWrapper template specialization

src/XrdXrootd/XrdXrootdConfig.cc, src/XrdXrootd/XrdXrootdMonFile.cc, src/XrdXrootd/XrdXrootdMonFile.hh, src/XrdXrootd/XrdXrootdMonitor.cc, src/XrdXrootd/XrdXrootdMonitor.hh
@ddavila0 can you test this change since you already have a testbed setup.
=> Adding fbuff argument to monitoring to restrict maximum size of fstream packet

src/XrdTpc/XrdTpcTPC.cc
If name in the SecEntity is a nullptr,
we must not try to derefence it.
Fixes: #1249
=> [TPC] Fix potential null pointer dereference on Push.

packaging/rhel/xrootd.spec.in
The underscore is missing in frm_xfrd in the rpm scriptlets,
=> Fix typo in rpm scriptlet

src/XrdOuc/XrdOucUtils.cc, src/XrdXrootd/XrdXrootdTransit.cc, src/XrdXrootd/XrdXrootdXeq.cc
The method skips to the second character in the string after checking that it is not a -, without checking that it belongs to the allowed set of characters.
=> Fix XrdOucUtils::Sanitize not sanitizing the first character in the string

src/XrdApps/XrdClProxyPlugin/ProxyPrefixPlugin.cc
The XrdSysDNS is not in xrootd 5. The XrdSysDNS.cc is still in the source tree, but is not compiled so it is not available in any library, and the XrdSysDNS.hh header is not installed.
This PR removes the one remaining include of the header (outside of XrdClient which is also not part of xrootd 5).
The XrdSysDNS is not used here so the include can be removed without any other changes.
=> No XrdSysDNS in xrootd 5 - remove include

src/XrdCms/XrdCmsRedirLocal.cc, src/XrdCms/XrdCmsRedirLocal.hh, src/XrdHttp/XrdHttpReq.cc
With these changes, an HTTP-client can be redirected to the file://-protocol by the xrootd redirector employing the XrdCmsRedirLocal-plugin.
The plug-in must be configured to allow HTTP redirects to local filesystem via the xrdcmsredirlocal.httpredirect true option.
Otherwise, default redirect behaviour is used.
Only minimal changes to other sources than the plug-in necessary.
=> [Xrootd HTTP] Allow redirect to local filesystem when using HTTP

src/XrdTpc/XrdTpcState.hh
```
/builddir/build/BUILD/xrootd-5.0.0/src/XrdTpc/XrdTpcState.hh:18:7: error: type 'struct State' violates the C++ One Definition Rule [-Werror=odr]
18 | class State {
|       ^
/builddir/build/BUILD/xrootd-5.0.0/src/XrdTpc/XrdTpcState.hh:18:7: note: a different type is defined in another translation unit
18 | class State {
|       ^
/builddir/build/BUILD/xrootd-5.0.0/src/XrdTpc/XrdTpcState.hh:126:24: note: the first difference of corresponding definitions is field 'm_headers'
126 |     struct curl_slist *m_headers; // any headers we set as part of the libcurl request.
|                        ^
/builddir/build/BUILD/xrootd-5.0.0/src/XrdTpc/XrdTpcState.hh:126:24: note: a field of same name but different type is defined in another translation unit
126 |     struct curl_slist *m_headers; // …
```
=> Add forward declaration to fix one definition rule (ODR) violation

packaging/rhel/xrootd.spec.in, src/XrdOuc/XrdOucUtils.cc, src/XrdTpc/XrdTpcState.hh, src/XrdXrootd/XrdXrootdConfig.cc, src/XrdXrootd/XrdXrootdTransit.cc, src/XrdXrootd/XrdXrootdXeq.cc, utils/xrootd-config
Since there is a RC for 4.12.4, I think that a few fixes should be cherry picked from master.
Maybe there are more? This PR has the to me most obvious ones.
I'm not 100% sure of the first one (Correct userid sanitization code). The reason for adding it was mainly to have less conflicts when cherry picking the following one.
Let me know if it is not appropriate.
=> Cherrypick bugfixes from master

src/XrdPfc/XrdPfc.cc
/builddir/build/BUILD/xrootd-5.0.1/src/XrdPfc/XrdPfc.cc:649:50: error: format '%lu' expects argument of type 'long unsigned int', but argument 9 has type 'size_t' {aka 'unsigned int'} [-Werror=format=]
=> Fix 32 bit compilation

src/Xrd/XrdProtLoad.cc, src/Xrd/XrdProtLoad.hh
~~~~
/builddir/build/BUILD/xrootd-5.0.1/src/Xrd/XrdProtLoad.cc:172:16: error: comparison is always true due to limited range of data type [-Werror=type-limits]
172 |    while(*pVec != -2)
|          ~~~~~~^~~~~
/builddir/build/BUILD/xrootd-5.0.1/src/Xrd/XrdProtLoad.cc:173:20: error: comparison is always false due to limited range of data type [-Werror=type-limits]
173 |         {if (*pVec == -1)
|              ~~~~~~^~~~~
~~~~
=> Fix ARM, PPC and S390X compilation (char is unsigned by default)

src/XrdSecgsi/XrdSecProtocolgsi.cc
The if statement says "if (!bck)", but the code then dereferences bck.
It looks like the code was meant to say "if (bck)".
Issue found by the gcc maintainers in Fedora when trying out gcc 11,
which reports a new error diagnostic:
error: 'this' pointer null [-Werror=nonnull]
Full error message:
````
/builddir/build/BUILD/xrootd-5.0.1/src/XrdSecgsi/XrdSecProtocolgsi.cc: In member function 'XrdSecProtocolgsi::ServerDoSigpxy(XrdSutBuffer*, XrdSutBuffer**, XrdOucString&)':
/builddir/build/BUILD/xrootd-5.0.1/src/XrdSecgsi/XrdSecProtocolgsi.cc:3943:23: error: 'this' pointer null [-Werror=nonnull]
3943 |          bck->ToString(m);
|          ~~~~~~~~~~~~~^~~
In file included from /builddir/build/BUILD/xrootd-5.0.1/src/./XrdCrypto/XrdCryptoBasic.hh:40,
from …
```
=> Fix null pointer dereference

src/XrdHttp/XrdHttpProtocol.cc
XrdHttp: in http mode fail the read if any error comes from the socket, including timeout
=> XrdHttp: in http mode fail the read if any error comes from the socket, including timeout

src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh
Ensure that we URI-quote the outgoing opaque data when we redirect as part of a HTTP-TPC.
This matches the same quoting strategy for normal HTTP redirects.
Fixes: #1293
=> URI-quote outgoing opaque data for HTTP-TPC

CMakeLists.txt, genversion.sh, packaging/rhel/xrootd.spec.in
I tried building XRootD and passing a custom version number so that it's easier to deploy it locally. But this did not work as expected since the version value embedded in the libraries (that is used for comparing the version of the dynamically loaded plugins) is not the expected one - it still uses the timestamp and git hash value. This pull request fixes that - so not only the RPM name contains the specified version but also the version embedded in the libraries is what one would expect.
=> BUILD: Really pass the user version when building

src/XrdTpc/XrdTpcMultistream.cc, src/XrdTpc/XrdTpcState.cc, src/XrdTpc/XrdTpcState.hh, src/XrdTpc/XrdTpcStream.cc, src/XrdTpc/XrdTpcStream.hh, src/XrdTpc/XrdTpcTPC.cc
Currently, we take a write from `libcurl` and immediately push it down to the underlying filesystem layer.  `libcurl` will issue fairly small writes, especially if the underlying filesystem is actually a remote filesystem (meaning the small write may be performed synchronously instead of just going to the OS page cache).
This code aggregates writes in memory until there's a full 1MB available; the MB is then pushed to the filesystem layer.
Note: as a side-effect of this change, writes become aligned on MB boundaries.  This avoids an issue with `xrootd-ceph` which does not currently support unaligned writes for EC setups.
=> Add support for buffering even when single-stream TPC

src/XrdTpc/XrdTpcMultistream.cc, src/XrdTpc/XrdTpcState.cc, src/XrdTpc/XrdTpcState.hh, src/XrdTpc/XrdTpcStream.cc, src/XrdTpc/XrdTpcTPC.cc
This ensures that the underlying file handle is closed before a HTTP response is sent to the client.
It also improves the error message handling such that filesystem errors generate a unique failure message.
Fixes: #1314
=> XrdTpc: Close file handle before final HTTP response

src/XrdTpc/XrdTpcState.cc, src/XrdTpc/XrdTpcTPC.cc
Both are real bugs - but I suspect neither are pragmatically reachable bugs.
Fixes: #1307
=> XrdTpc: Fix minor bugs discovered by compiler warnings

src/XrdPfc/XrdPfcFile.cc
Last argument of pgWrite() is opts rather than a size. So in this patch I set the opts to 0. I don't think there's any advantage to specify Verify here, since the data are already available to a cache client by reading from RAM so it would be late to discover a mismatch.
The data almost certainly do match their checksums (if present) since they came from pgRead, so either XrdCl verified received checksums or they were generated based on data received over TLS. (I think XrdCl does always verify received checksums, but protocol spec says it only has to verify if the connection is not TLS. If client didn't verify they could conceivably mismatch if origin sent them mismatching).
=> [XCache] Fix options argument to pgwrite.

src/XrdPfc/XrdPfcConfiguration.cc, src/XrdPfc/XrdPfcPurge.cc
The plugin loader needs the .so suffix for libXrdOssCsi.so.
I saw a segfault during purge, I've also put one possible fix commit in this PR (see issue #1336).
=> Xcache: segfault during purge and plugin name

docs/PreReleaseNotes.txt, src/XrdOss/XrdOss.cc
Changes return code check on Ver32C return code in XrdOssDF::pgWrite.
=> Fix check on Ver32C return code

src/XrdOfs/XrdOfsTPCProg.cc
Fixed. XRDTPC_TPROT and XRDTPC_SPROT are now set independently of each other.
=> [Server] XRDTPC_TPROT is set to the value of XRDTPC_SPROT #1338

src/XrdPfc/XrdPfc.cc, src/XrdPfc/XrdPfc.hh, src/XrdPfc/XrdPfcCommand.cc, src/XrdPfc/XrdPfcConfiguration.cc, src/XrdPfc/XrdPfcFile.cc, src/XrdPfc/XrdPfcIOFileBlock.cc, src/XrdPfc/XrdPfcInfo.cc, src/XrdPfc/XrdPfcInfo.hh, src/XrdPfc/XrdPfcPrint.cc, src/XrdPfc/XrdPfcPurge.cc
- When wrong number of bytes is returned in a block read, assume
that initial file-size estimate was different than the current
remote file -- purge the file.
- Make two cinfo checksums: one for the core data and another for downloaded
state and for access statistics. The logic here is that if core part gets
corrupted, I could get nonsensical/wrong values for sizes of the following
arrays and thus I thought it's better to check that first.
- Add checks for corrupt / nonsensical access stats in previous cinfo file
versions.
- Remove support for cinfo file version 1.
- Do not allow enabling of hdfs mode during configuration parsing:
this functionality has not been supported for a while and there is
now a better way of potentially re-implementing it.
=> [XCache] Improve cinfo consistency, purge file on read size mismatch.

cmake/XRootDSystemCheck.cmake
This patch was required to cross-compile XRootD for arm64 macOS (from a x86_64 macOS system) in https://github.com/conda-forge/xrootd-feedstock/pull/36.
=> Fix cross-compilation

cmake/XRootDOSDefs.cmake
The -Wmisleading-indentation warnings were fixed in commit
d24f77c040b0e1ea170fa398ec21767c2ce1ad3a
The -Wpessimizing-move warnings warnings were fixed in commit
5cc51a08090b874d10180e019e6bceb0372e8445
The -Wno-error=address-of-packed-member warnings were false positives
issued by prerelease versions of gcc 9. The compiler has been fixed
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=88664
=> Remove obsolete warning overrides

src/XrdOuc/XrdOucPsx.cc
The fix for the gcc 11 compiler warning in commit
8f36753d46c183aa89058219e36e9a2980afd250 is incorrect.
Placing the sizeof statement in parenthesis does not correct the bug,
it just obfuscates the code so that the compiler doesn't see it.
The correct fix is to give the unnamed struct a name so that the
sizeof the struct can be used in the calculation.
=> Use correct size for struct

src/XrdTpc/XrdTpcTPC.cc
Fix case where stream_req is 0, which should be interpreted as a single stream. This fixes what is currently a typo in the ternary comparison.
=> Fix case where 0 streams is requested.

src/XrdSciTokens/src/XrdAccSciTokens.cc
The plugin interface expect XrdAccAuthorizeObjAdd function to
exist.
=> Rename XrdAccAuthorizeObjectAdd to XrdAccAuthorizeObjAdd

src/XrdSciTokens/src/XrdAccSciTokens.cc
0 issuers is ok for SciTokens.  No token will be authorized,
but it shouldn't be an error causing xrootd to not start.  A
log message is still reported when 0 issuers are detected.
=> Allow 0 issuers in SciTokens config

src/XrdSciTokens/configs/export-lib-symbols, src/XrdSciTokens/src/XrdAccSciTokens.cc
=> Adding ObjAdd to list of scitokens functions exported

src/XrdCms/XrdCmsRedirLocal.cc
The c_str() of a temporary std::string object is not valid after the
lifetime of the object expires. Consider:
```
$ cat temp.cpp
int main() {
const char* c1 = std::string("ABC").c_str();
const char* c2 = std::string("DEF").c_str();
std::cout << c1 << std::endl;
std::cout << c2 << std::endl;
}
$ g++ -O2 -o temp temp.cpp
$ ./temp
DEF
DEF
```
The memory used by the first temporary std::string is reused by the
second one, since the lifetime of the first has expired. So when the
saved c_str() of the first string is written out, it writes the second
string.
=> Don't save pointer to temporary

packaging/common/cmsd@.service, packaging/common/frm_purged@.service, packaging/common/frm_xfrd@.service, packaging/common/xrootd-clustered.cfg, packaging/common/xrootd-http.cfg, packaging/common/xrootd-standalone.cfg, packaging/common/xrootd@.service, packaging/rhel/xrootd.functions, packaging/rhel/xrootd.functions-slc4, packaging/rhel/xrootd.tmpfiles, src/XrdSciTokens/test/config/xrootd-http.cfg, src/XrdSciTokens/test/test_inside_docker.sh, utils/XrdCmsNotify.pm
/var/run is a symlink to /run, so the locations are the same.
However, if /var/run is used in systemd and tmpfiles.d configuration
files, the logs get full of warnings asking for it to be changed, e.g.
xrootd.conf:1: Line references path below legacy directory /var/run/, updating /var/run/xrootd → /run/xrootd; please update the tmpfiles.d/ drop-in file accordingly.
=> Use /run instead of /var/run

src/XrdSeckrb5/XrdSecProtocolkrb5.cc
The call to krbClientContext.Lock() was moved in commit 6e93d111c6
("krb5: fixes after later changes for memory leaks"), but the error
paths did not correctly UnLock().
=> krb5: Release lock if initialization fails

CMakeLists.txt, src/XrdCrypto.cmake, src/XrdSec.cmake, src/XrdSecgsi.cmake
Motivation:
Commands like 'xrdcp' and 'xrdfs' require plugins to provide some
functionality, perhaps most prominently when authenticating.  However,
the list of required plugins and the names of these plugin's targets
changes over time.
It would be convenient if the build system were to automate building a
useful subset of plugins (perhaps all plugins) by using a constant
(phony) target 'plugins'.  This would facilitate creating build-tree
binaries with a command like:
make plugins xrdcp xrdfs
Modification:
Add support for 'plugins' phony target to which plugins may add
themselves.
Add initial support for this 'plugins' target that builds XrdCryptossl,
XrdSecpwd, XrdSecsss, XrdSecunix, XrdSecgsi, XrdSecgsiGMAPDN and
XrdSecgsiAUTHZVO, and any dependencies thereof.
Result:
Is is easier to …
=> build: add 'plugins' phony target

src/XrdTpc/XrdTpcState.cc, src/XrdTpc/XrdTpcState.hh, src/XrdTpc/XrdTpcStream.cc, src/XrdTpc/XrdTpcStream.hh
Corrects an error conditional and fixes some missing returns.  This prevents a stack overflow due to recursion when the filesystem write fails.
Fixes #1384
=> Fix error handling on stream write errors

src/XrdHttp/XrdHttpReq.cc
If the remote client is trying to create an empty file, the state machine broke because it was waiting for more bytes from the bridge before advancing the query.
This short-circuits the wait and causes an immediate callback, allowing XrdHttp to immediately close the file.
Fixes #1365
=> XrdHttp: Fix empty PUT

src/XrdTpc/XrdTpcStream.cc, src/XrdTpc/XrdTpcStream.hh, src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh
This removes problematic recursive invocations of the stream writes and fixes some multistream errors that caused too-high concurrency.
The underlying cause of the multistream issue was allowing partial writes of the buffers.  The buffer occupancy is a feedback mechanism to the multistream code to not launch additional requests; the partial write optimization allowed a buffer to look empty when really there was more coming from the request.
Because we aren't allowing partial writes, this also had to allow partial accepts if the incoming curl buffer spanned two internal buffers.  With this, multistream stays megabyte aligned and should still work on RAL's Echo.
Finally, this adds some error messages on conditions considered internal logic errors -- should help with future debugging.
=> XrdTPC: Refactor stream writes

src/XrdTpc/XrdTpcConfigure.cc, src/XrdTpc/XrdTpcMultistream.cc, src/XrdTpc/XrdTpcState.hh, src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh
This does not enforce a minimum bandwidth (N MB/s) but rather
aborts the transfer if zero data has moved within a given timeframe.
By default, the transfer has 120 seconds to move the first byte of
data and it must transfer at least 1 byte every 60 seconds thereafter.
This purposely does not do bandwidth minimums as that's built into
future versions of `curl` and I'd prefer to not re-implement it.
The default timeouts can be overridden by setting:
```
tpc.timeout timeout_val [first_byte_timeout_val]
```
where the default is equivalent to:
```
tpc.timeout 60
```
If the `first_byte_timeout_val` is not set, it defaults to 2x the
`timeout_val`.
(Note: I am _not_ targeting the 5.1.0 release for this)
=> XrdTpc: Add a crude timeout mechanism.

src/XrdMacaroons/XrdMacaroonsAuthz.cc, src/XrdMacaroons/XrdMacaroonsHandler.cc, src/XrdMacaroons/XrdMacaroonsHandler.hh
For authorization purposes, there have been many requests to be more lenient about mismatches slashes (that is, macaroon was requested for `/foo//bar` but the user tries to access `/foo/bar`).  This normalizes the slashes when the macaroon is issued and when it is used for authorization.
=> XrdMacaroons: Normalize slashes when issuing and authorizing macaroons.

src/XrdTpc/XrdTpcTPC.cc
Confirmed the memory leak & fix with valgrind.
=> XrdTpc: When we fail the transfer, free the curl-related memory.

src/XrdMacaroons/XrdMacaroonsAuthz.cc
Replaces hack where the XrdSecEntity was const_cast.
=> XrdMacaroons: Switch to use extended attribute for mapping.

src/XrdXrootd/XrdXrootdAio.cc
This is a suggested patch for the situation described in issue #1407
=> [Server] Make sure each aio request has the minimum number of aio objects available

src/XrdTpc/XrdTpcStream.cc
When we saved the partial buffer, we were saving from the beginning instead of the offset bytes.
#1404
=> XrdTpc: Buffer starting at the right offset.

src/XrdHttp/XrdHttpReq.cc
This fixes a bug accidentally created by the fix for empty PUT's.
When the original PUT is given for a 100-continue transfer, the length is _supposed_ to be zero but we need to continue the transfer.
Fixes #1411
=> XrdHttp: Fix chunked transfer with 100-continue.

src/XrdPfc/XrdPfcConfiguration.cc
This printf statement looks like a left behind debug print-out. Especially because of the "GGGG" part.
=> Remove debug print-out

src/XrdPfc/XrdPfcFile.cc, src/XrdPfc/XrdPfcFile.hh, src/XrdPfc/XrdPfcVRead.cc
This was leading to accumulation of open files and sockets to origin servers.
=> [Pfc] Fix error handling in File::ReadV().

bindings/python/src/Conversions.hh
This should fix #1400. I added a delete after a chunk buffer is copied into a python string in the conversion function for `VectorReadInfo`, analogous to what is done here for `ChunkInfo`:
https://github.com/xrootd/xrootd/blob/551521ea7368e3b2a4c7964325e2e7e3fe7ce047/bindings/python/src/Conversions.hh#L248-L257
=> delete chunk buffer for VectorReadInfo after copying into python string

src/XrdOssCsi/XrdOssCsiFile.cc, src/XrdOssCsi/XrdOssCsiPages.cc, src/XrdOssCsi/XrdOssCsiTagstoreFile.cc
Fix some unintended conversion between ssize_t and int when used as return values; and correct meaning of return value of FetchRange & VerifyRange. I'm not aware of any errors being triggered because of these bugs.
=> [OssCsi] Fix some incorrect conversion of return values

src/XrdTls/XrdTlsTempCA.cc
- Free XrdCryptoX509Chain when finished
- Duplicate and close file descriptors to free memory
=> [XrdTls] Memory leak fixes in XrdTlsTempCA

src/XrdHttp/XrdHttpProtocol.cc
Memory for SecEntity.host is already allocated by `GetClientIPStr` at
https://github.com/xrootd/xrootd/blob/1578f628946f04c439321c4a342d26b6da9bc973/src/XrdHttp/XrdHttpProtocol.cc#L474-L477
=> Fix memleak in SecEntity.host

packaging/rhel/xrootd.spec.in, src/XrdCl/CMakeLists.txt, src/XrdCl/XrdClChannel.cc, src/XrdCl/XrdClCheckSumManager.cc, src/XrdCl/XrdClClassicCopyJob.cc, src/XrdCl/XrdClCopyProcess.cc, src/XrdCl/XrdClFileStateHandler.cc, src/XrdCl/XrdClSyncQueue.hh, src/XrdCl/XrdClThirdPartyCopyJob.cc, src/XrdCl/XrdClXRootDMsgHandler.cc, src/XrdHeaders.cmake
- Remove references to removed XrdClUglyHacks.hh and XrdSysLinuxSemaphore.hh in CMakeLists.txt files.
- Add #include "XrdSys/XrdSysPthread.hh" where classes from the file is used, and it was previously included recursively by a removed include of XrdClUglyHacks.hhl.
- Remove semaphore selection from spec file.
- Fix some alignments in variable declarations.
=> [XrdCl] Remove more ugly hack

src/XrdTpc/XrdTpcMultistream.cc, src/XrdTpc/XrdTpcState.hh, src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh
When `ProcessPushReq()` and `ProcessPullReq()` leave scope, `TPC::State::~State()` is called. The destructor modifies the curl handle, but the handle may already have been through `curl_easy_cleanup()`, and any further use may cause memory corruption.
Make the curl handle NULL after `curl_easy_cleanup()`.
<details>
<summary>Valgrind output from xrootd-5.1.2-0.experimental.2534824.4ca38eb6.el7.cern.x86_64 and curl-7.29.0-59.el7_9.1.x86_64</summary>
```
-bash-4.2$ valgrind --undef-value-errors=no /usr/bin/xrootd -l /var/log/xrootd/xrootd.log -c /etc/xrootd/xrootd-clustered.cfg -k fifo -s /var/run/xrootd/xrootd-clustered.pid -n clustered
==20804== Memcheck, a memory error detector
==20804== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==20804== Using Valgrind-3.15.0 and …
```
=> [XrdTpc] Do not modify curl handle after curl_easy_cleanup()

src/XrdSfs/XrdSfsInterface.cc
error: format '%ld' expects argument of type 'long int', but argument
4 has type 'ssize_t' {aka 'int'} [-Werror=format=]
=> Fix compilation failure on 32 bit (ix86/arm32)

src/XrdTls/XrdTlsSocket.cc
- Clear the OpenSSL error queue to avoid reporting errors from other SSL operations, such as reading CRLs
- Log queued OpenSSL errors if present
=> Clear OpenSSL error queue ahead of SSL_read/write/accept()

src/XrdCl/XrdClXRootDTransport.cc, src/XrdCrypto/XrdCryptosslAux.cc, src/XrdTls/XrdTlsSocket.cc
Regarding the OpenSSL `ERR_clear_error()` overhead introduced in #1464:
This PR should clear the OpenSSL error queue in `XrdCryptosslX509ParseBucket()`, along with reverting the `ERR_clear_error()` calls in `XrdTlsSocket`.
So far, I'm unable to reproduce the TLS error on our local xcache with this patch (on the latest experimental, xrootd-5.2.1-0.experimental.2679300.76d03f61). This certainly could use some thorough testing to confirm. @osschar
=> Clear the OpenSSL error queue in XrdCryptosslX509ParseBucket()

src/XrdOssCsi/XrdOssCsi.hh
This PR adds the XRDOSS_HASPGRW flag (in addition to previously set XRDOSS_HASFSCS) to the list of features that the stacked Oss will report in Features(). This is because OssCsi adds implementations of pgRead & pgWrite which are extended beyond the standard Oss versions of those methods.
=> [XrdOssCsi] Report XRDOSS_HASPGRW in Features()

src/XrdSecztn.cmake
It's not clear to me why this was commented but this fixes the issue in https://github.com/conda-forge/xrootd-feedstock/pull/45 where building with scitoken support for macOS fails with the below linker error (for both x86 and arm64).
```cpp
Undefined symbols for architecture arm64:
"XrdSysE2T(int)", referenced from:
XrdSecProtocolztn::readFail(XrdOucErrInfo*, char const*, int) in XrdSecProtocolztn.cc.o
"XrdOucString::find(char, int, bool)", referenced from:
XrdSecProtocolztn::findToken(XrdOucErrInfo*, std::__1::vector<XrdOucString, std::__1::allocator<XrdOucString> >&, bool&) in XrdSecProtocolztn.cc.o
"XrdOucString::endswith(char const*)", referenced from:
XrdSecProtocolztn::findToken(XrdOucErrInfo*, std::__1::vector<XrdOucString, std::__1::allocator<XrdOucString> >&, bool&) in …
```
=> Fix linking XrdSecztn when building for macOS

src/XrdCks/XrdCks.hh, src/XrdCks/XrdCksCalccrc32C.cc, src/XrdCks/XrdCksCalccrc32C.hh, src/XrdCks/XrdCksManager.cc, src/XrdCl/XrdClCheckSumManager.cc, src/XrdOuc/XrdOucCache.cc, src/XrdUtils.cmake
Implementation of a CRC-32C checksum using the XrdCksCalc class and library functions already provided within the repo.
=> CRC-32C Checksum

src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpUtils.cc, src/XrdHttp/XrdHttpUtils.hh
Workaround for "security" tests
=> Obfuscate paths hidden into error strings

bindings/python/libs/client/finalize.py
The finalize method in `bindings/python/libs/client/finalize.py` iterates over all references known to the garbage collector, even those not created by the xrootd bindings. This does not work correctly when the target of a weak reference has been already
collected.
This pr catches this exception, e.g.:
Traceback (most recent call last):
File
".../envs/topcoffea-env/lib/python3.8/site-packages/XRootD/client/finalize.py",
line 46, in finalize
if isinstance(obj, File) and obj.is_open():
ReferenceError: weakly-referenced object no longer exists
=> python bindings: catch ReferenceError error when finalizing File's

src/XrdServer.cmake
Link libXrdServer to libatomic on riscv64 to avoid undefined references:
```
/usr/bin/ld: libXrdServer.so.3.0.0: undefined reference to `__atomic_fetch_or_1'
/usr/bin/ld: libXrdServer.so.3.0.0: undefined reference to `__atomic_fetch_sub_1'
/usr/bin/ld: libXrdServer.so.3.0.0: undefined reference to `__atomic_fetch_and_1'
/usr/bin/ld: libXrdServer.so.3.0.0: undefined reference to `__atomic_fetch_add_1'
collect2: error: ld returned 1 exit status
```
=> Link libXrdServer to libatomic on riscv64 

src/XrdOss/XrdOss.cc, src/XrdOuc/XrdOucCache.cc
Changes XrdOssDF and XrdOucCacheIO pgRead to use the length returned by read when calculating the checksums, rather than the requested read size. Believed to fix issue #1507 (due to XrdOucCacheIO pgRead).
Also removes an alignment check which may have been inadvertently re-added to XrdOucCacheIO::pgRead during a rebase.
=> [Server] Use length returned by read and fix an alignment check in pgRead

src/XrdOssCsi/XrdOssCsiPages.hh
Compiling XrdOssCsiPages.hh was breaking builds on sl6, even when using when a compiler with c++14 support. This was reported by an lhc experiment. The cause was that in this build inttypes.h did not define macros such as PRIx64. On sl6, setting __STDC_FORMAT_MACROS before the include does cause it to define the macros; but the solution in this PR is to use the c++11 version of this header, cinttypes.
=> [Server] Fix an include in OssCsi

src/XrdPosix/XrdPosixAdmin.cc
The st_rdev field in struct stat (which is 32 bits) is not type dev_t (which is 64 bits)
```
/<<PKGBUILDDIR>>/src/XrdPosix/XrdPosixAdmin.cc:188:45: error: cannot convert ‘long unsigned int*’ to ‘dev_t*’ {aka ‘long long unsigned int*’}
188 |    Stat.st_mode   = XrdPosixMap::Flags2Mode(&Stat.st_rdev, sInfo->GetFlags());
|                                             ^~~~~~~~~~~~~
|                                             |
|                                             long unsigned int*
In file included from /<<PKGBUILDDIR>>/src/XrdPosix/XrdPosixAdmin.cc:38:
/<<PKGBUILDDIR>>/src/./XrdPosix/XrdPosixMap.hh:43:46: note:   initializing argument 1 of ‘static mode_t XrdPosixMap::Flags2Mode(dev_t*, uint32_t)’
43 | static mode_t              Flags2Mode(dev_t *rdv, uint32_t flags);
| …
```
=> Work around inconsistent type definitions on MIPS

cmake/XRootDSystemCheck.cmake, src/XrdApps.cmake, src/XrdCl/CMakeLists.txt, src/XrdCrypto.cmake, src/XrdDaemons.cmake, src/XrdFfs.cmake, src/XrdFrm.cmake, src/XrdHttp.cmake, src/XrdOssCsi.cmake, src/XrdPfc.cmake, src/XrdPlugins.cmake, src/XrdPosix.cmake, src/XrdSciTokens.cmake, src/XrdSec.cmake, src/XrdSecgsi.cmake, src/XrdServer.cmake, src/XrdSsi.cmake, src/XrdTpc.cmake, src/XrdUtils.cmake, src/XrdXml.cmake, tests/XrdCephTests/CMakeLists.txt, tests/XrdClTests/CMakeLists.txt, tests/XrdClTests/tls/CMakeLists.txt, tests/common/CMakeLists.txt
This is a follow-up to the discussion in #1506.
Using ${CMAKE_THREAD_LIBS_INIT} everywhere is more consistent than doing a one-off for the one place where it is strictly necessary.
This also avoids that things break elsewhere in the future if some other part of the code starts using new parts of std::atomic that need libatomic.
=> Use -pthread

src/XrdCrypto/XrdCryptoLite_bf32.cc, src/XrdCrypto/XrdCryptoX509Chain.cc, src/XrdCrypto/XrdCryptosslAux.cc, src/XrdCrypto/XrdCryptosslCipher.cc, src/XrdCrypto/XrdCryptosslCipher.hh, src/XrdCrypto/XrdCryptosslRSA.cc, src/XrdCrypto/XrdCryptosslX509.cc, src/XrdCrypto/XrdCryptosslgsiAux.cc, src/XrdHttp/XrdHttpUtils.cc, src/XrdSec/XrdSecProtect.cc, src/XrdTls/XrdTlsContext.cc
Still compiles on RHEL/CentOS 7 with openssl 1.0.2k
Fixes: #1516
This is a big change that requires testing.
=> Fix compilation on Fedora 36 with openssl 3.0.0

src/XrdHttp/XrdHttpProtocol.cc
This improves the behaviour of BuffGetData when the parm wait is set to false. Now a plugin can read data without knowing the size in advance (e.g. for parsing a line between chunks)
=> BuffGetData: better handle the case of wait=false

src/XrdPosix/XrdPosixMap.cc
The error numbers defined on Linux can not be reused on other systems
since this causes clashes.
On Linux ECHRNG is 44, but defining ECHRNG to be 44 on systems that do
not define ECHRNG is not appropriate. On e.g. kFreeBSD this will clash
with ESOCKTNOSUPPORT, which is defined as 44 on that system.
=> Do not hardcode error numbers

src/XrdCl/XrdClFileStateHandler.cc
error: parameter declared 'auto'
=> Be nice to older (less clever) compiler versions

src/XrdSys/XrdSysTrace.hh
~~~
/builddir/build/BUILD/xrootd-5.3.2/src/XrdSys/XrdSysTrace.cc:177:22: error: comparison is always false due to limited range of data type [-Werror=type-limits]
177 |            if (doHex < 0) doHex = 0;
|                ~~~~~~^~~
/builddir/build/BUILD/xrootd-5.3.2/src/XrdSys/XrdSysTrace.cc: In member function 'XrdSysTrace& XrdSysTrace::operator<<(short int)':
/builddir/build/BUILD/xrootd-5.3.2/src/XrdSys/XrdSysTrace.cc:232:14: error: comparison is always false due to limited range of data type [-Werror=type-limits]
232 |    if (doHex < 0) doHex = 0;
|        ~~~~~~^~~
/builddir/build/BUILD/xrootd-5.3.2/src/XrdSys/XrdSysTrace.cc: In member function 'XrdSysTrace& XrdSysTrace::operator<<(int)':
/builddir/build/BUILD/xrootd-5.3.2/src/XrdSys/XrdSysTrace.cc:255:14: error: comparison is …
=> Fix build failure on platforms where char is unsigned (ARM, PPC and S390X)

src/XrdThrottle/XrdThrottleFile.cc
Fix for https://github.com/xrootd/xrootd/issues/1544
=> [XrdThrottle] do not initialise a string with a null pointer

src/XrdCrypto/XrdCryptoFactory.hh, src/XrdCrypto/XrdCryptosslAux.cc, src/XrdCrypto/XrdCryptosslAux.hh, src/XrdSecgsi/XrdSecProtocolgsi.cc, src/XrdSecgsi/XrdSecProtocolgsi.hh, src/XrdSecgsi/XrdSecgsiProxy.cc, src/XrdSecgsi/XrdSecgsitest.cc
Adding support for pure cert/key authentication.
Client controls this mode via XrdSecGSICREATEPROXY:
1. If XrdSecGSICREATEPROXY=1 (default), a proxy is auto-generated from the cert/key pair if one is not found.
2. If XrdSecGSICREATEPROXY=0, a proxy is used if present. Otherwise, the cert/key pair is used if present (no proxy).
This is mostly meant, on the server side, for pass-less authentication, possible when the key file is pass-less.
NB1: if the key-file is pass-less and XrdSecGSICREATEPROXY = 1 (default) authentication still works with the usual protocol, i.e. creating a proxy and using that for the handshake. Setting XrdSecGSICREATEPROXY = 0 avoids those additional steps.
NB2: Forward / backward compatibility is obtained by enabling the cert/pair mechanism only for versions …
=> Rebased version of PR#1493

src/XrdCms/XrdCmsRedirLocal.cc, src/XrdCms/XrdCmsRedirLocal.hh
Until now, the plug-in used oss.localroot set in the redirector, to calculate the new paths. This led to conflicts described in issue  #1278 . Adding a config option with a localroot onl for the plug-in, this issue is resolved.
The second commit increases the fault tolerance: Before this commit, if a client is redirected to the local filesystem, but does not find the file there, a redirection loop is started.
Example:
`
Open has returned with status [FATAL] Redirect limit has been reached
Error while opening at 192.168.122.200:1094: [FATAL] Redirect limit has been reached
Redirect trace-back:
0. Redirected from: root://192.168.122.200:1094//autoTest1 to: file://localhost/xrdmnt//autoTest1
1. Retrying: root://192.168.122.200:1094//autoTest1
2. Redirected from: …
=> [XrdCmsRedirLocal] Add localroot option for plug-in. Improve fault tolerance of RedirLocal plug-in

src/XrdApps/XrdPrep.cc
Fixes GNU/Hurd build
/<<PKGBUILDDIR>>/src/XrdApps/XrdPrep.cc: In function ‘int main(int, char**)’:
/<<PKGBUILDDIR>>/src/XrdApps/XrdPrep.cc:109:34: error: ‘MAXPATHLEN’ was not declared in this scope
109 |    static const int MaxPathLen = MAXPATHLEN+1;
|                                  ^~~~~~~~~~
/<<PKGBUILDDIR>>/src/XrdApps/XrdPrep.cc:213:24: error: size of array ‘fBuff’ is not an integral constant-expression
213 |        char *sP, fBuff[MaxPathLen];
|                        ^~~~~~~~~~
src/CMakeFiles/xrdprep.dir/build.make:78: recipe for target 'src/CMakeFiles/xrdprep.dir/XrdApps/XrdPrep.cc.o' failed
=> Add missing include

src/XrdNet/XrdNetPMarkCfg.cc
../xrootd-5.4.0/src/XrdNet/XrdNetPMarkCfg.cc: In static member function 'static XrdNetPMark* XrdNetPMarkCfg::Config(XrdSysError*, XrdScheduler*, XrdSysTrace*, bool&)':
../xrootd-5.4.0/src/XrdNet/XrdNetPMarkCfg.cc:271:16: error: comparison is always false due to limited range of data type [-Werror=type-limits]
271 |    if (useFFly < 0)
|        ~~~~~~~~^~~
../xrootd-5.4.0/src/XrdNet/XrdNetPMarkCfg.cc: In static member function 'static int XrdNetPMarkCfg::Parse(XrdSysError*, XrdOucStream&)':
../xrootd-5.4.0/src/XrdNet/XrdNetPMarkCfg.cc:1037:20: error: comparison is always false due to limited range of data type [-Werror=type-limits]
1037 |        if (useFFly < 0) useFFly = 1;
|            ~~~~~~~~^~~
=> Fix compilation when char is unsigned (armv7hl, aarch64, ppc64le, s390x)

src/XrdOuc/XrdOucUtils.cc
Fixes compilation errors on Debian kfreebsd:
~~~
../src/XrdOuc/XrdOucUtils.cc: In static member function ‘static char* XrdOucUtils::getFile(const char*, int&, int, bool)’:
../src/XrdOuc/XrdOucUtils.cc:474:45: error: ‘ENODATA’ was not declared in this scope
474 |    if (Stat.st_size == 0 && notempty) {rc = ENODATA; return 0;}
|                                             ^~~~~~~
~~~
=> Define ENODATA if not defined

src/XrdMacaroons/XrdMacaroonsHandler.cc, src/XrdSciTokens/XrdSciTokensAccess.cc
../xrootd-5.4.0/src/XrdSciTokens/XrdSciTokensAccess.cc: In member function 'bool XrdAccSciTokens::GenerateAcls(const string&, uint64_t&, {anonymous}::AccessRulesRaw&, std::string&, std::string&, std::string&, std::vector<{anonymous}::MapRule>&, std::vector<std::basic_string<char> >&)':
../xrootd-5.4.0/src/XrdSciTokens/XrdSciTokensAccess.cc:652:83: error: no matching function for call to 'regex_replace(std::string&, std::regex, const char [2])'
std::regex("//"), "/");
^
../xrootd-5.4.0/src/XrdSciTokens/XrdSciTokensAccess.cc:652:83: note: candidates are:
In file included from /usr/include/c++/4.8.2/regex:62:0,
from ../xrootd-5.4.0/src/XrdSciTokens/XrdSciTokensAccess.cc:18:
/usr/include/c++/4.8.2/bits/regex.h:2162:5: note: template<class _Out_iter, class _Bi_iter, class _Rx_traits, class …
=> Help older compiler find the right template.

src/XrdSciTokens/XrdSciTokensAccess.cc
@clundst found a segfault in xrootd scitokens, apparently related to iterator use. 
<details>
<summary>backtrace from 5.3.0-1.1.osg35up.el7 with jemalloc junk:true</summary>
```
#5  0x00007f53c4e800c8 in signalHandler (sig=11, info=0x7f53cc7decf0, uc=0x7f53cc7debc0) at /usr/src/debug/java-1.8.0-openjdk-1.8.0.292.b10-1.el7_9.x86_64/openjdk/hotspot/src/os/linux/vm/os_linux.cpp:4588
#6  <signal handler called>
#7  local_Rb_tree_increment (__x=0x5a5a5a5a5a5a5a5a, __x@entry=0x7f53bd80a440) at ../../../../../libstdc++-v3/src/c++98/tree.cc:65
#8  std::_Rb_tree_increment (__x=__x@entry=0x7f53bd80a440) at ../../../../../libstdc++-v3/src/c++98/tree.cc:85
#9  0x00007f53c2e3fe85 in operator++ (this=<synthetic pointer>) at /opt/rh/devtoolset-7/root/usr/include/c++/7/bits/stl_tree.h:295
#10 Check …
```
=> [XrdSciTokens] Modifying std::map invalidates iterator

src/XrdSciTokens/XrdSciTokensAccess.cc, src/XrdThrottle/XrdThrottleFile.cc
Hi @esindril !
Your question the other day about the token subject got me thinking and I was able to identify a use case where the subject was useful independent of the (authorization system): we can utilize it for the throttling plugin.
Mind you, I still think it's a bad idea to feed this to EOS... but with this it's at least available in the `token.subject` xattr for the incoming request.
Brian
=> Save token subject in the XrdSecEntity extended attribute API

src/XrdThrottle/XrdThrottle.hh, src/XrdThrottle/XrdThrottleFile.cc, src/XrdThrottle/XrdThrottleFileSystemConfig.cc, src/XrdThrottle/XrdThrottleManager.cc, src/XrdThrottle/XrdThrottleManager.hh, src/XrdThrottle/XrdThrottleTrace.hh
This adds two new concurrency limits in the throttle plugin:
1.  Maximum number of open files per unique entity (which might be a unique identifier from a token).
2. Maximum number of "active connections" per entity.
The intent is to provide some per-"user" limits on resource consumption.  (1) should be self-evident; open file handles are expensive for some filesystems and this prevents exhaustion by a single user.
(2) is less obvious.  I define an "active connection" to be a thread with at least one open file handle.  It's meant to approximate "open connections" as each connection currently costs an OS thread and these are definitely finite resources.  I see the throttle plugin as a reasonable place to do this because (a) it's self-contained (no changes outside the plugin) and (b) for …
=> Track maximum concurrency limits in throttle plugin

src/XrdCl/XrdClCopy.cc, src/XrdCms/XrdCmsUtils.cc
~~~
.../src/XrdCms/XrdCmsUtils.cc: In function 'XrdCmsUtils::ParseMan(XrdSysError*, XrdOucTList**, char*, char*, int*, bool)':
.../src/XrdCms/XrdCmsUtils.cc:226:43: error: pointer 'newMans_175' may be used after 'operator delete(void*, unsigned long)' [-Werror=use-after-free]
226 |          if (!plus || strcmp(hSpec, newP->text)) isBad = false;
|                                     ~~~~~~^~~~
.../src/XrdCms/XrdCmsUtils.cc:221:27: note: call to 'operator delete(void*, unsigned long)' here
221 |                    delete newP;
|                           ^~~~
.../src/XrdCl/XrdClCopy.cc: In function 'IndexRemote(XrdCl::FileSystem*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, unsigned short)':
.../src/XrdCl/XrdClCopy.cc:442:17: error: pointer used after …
=> Fix compiler warnings about pointers used after free:

cmake/FindOpenSSL.cmake
This patch is supposed to fix a duplication problem when linking against openssl static libs (see issue [#1581](https://github.com/xrootd/xrootd/issues/1581)).
If the libraries are static and the openssl version is recent enough it assumes that the required functions and symbols are available.
The default behaviour - linking wrt shared libs - should be unchanged.
=> Add support for static openssl libraries

src/XrdCl/XrdClEcHandler.hh, src/XrdCl/XrdClPlugInManager.cc, src/XrdCl/XrdClZipArchive.hh, src/XrdEc/XrdEcObjCfg.hh, src/XrdEc/XrdEcStrmWriter.cc
1. add pgread/pgwrite
2. avoid 'qdl' delay during read
3. avoid servers in ServerPending state during write
4. store a version number to an Xattr in order to identify (and ignore) old zip archived left by previous deletion
5. set chunk names inside a zip archive to "obj.1.0", etc (not tied to the file name) so that we can rename
6. Set env XRDCL_EC so that other code can act accordingly
7. bug fix
=> Update to XrdCl and XrdEC

src/Xrd/XrdBuffXL.cc, src/XrdNet/XrdNetUtils.cc, src/XrdOuc/XrdOucBuffer.cc, src/XrdOuc/XrdOucTable.hh, src/XrdPosix/XrdPosixAdmin.cc
~~~
In member function 'Init',
inlined from 'Init' at .../src/Xrd/XrdBuffXL.cc:64:6:
.../src/Xrd/XrdBuffXL.cc:90:30: warning: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
90 |    bucket = new BuckVec[lg2+1];
|                              ^
/usr/include/c++/12/new: In member function 'Init':
/usr/include/c++/12/new:128:26: note: in a call to allocation function 'operator new []' declared here
128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
|                          ^
.../src/XrdOuc/XrdOucBuffer.cc: In member function '__ct_base ':
.../src/XrdOuc/XrdOucBuffer.cc:79:30: warning: argument 1 value '18446744073709551615' exceeds maximum object size 9223372036854775807 …
=> Fix warnings about allocations exceeding maximum object size

src/XrdCrypto/XrdCryptosslCipher.cc, src/XrdCrypto/openssl3/XrdCryptosslCipher.cc
This should address the increased load issue discussed in #1556. I've _very lightly_ tested this change in production, and it seems OK. I'm planning more thorough tests tomorrow.
We'll also need to update `openssl3/XrdCryptosslCipher.cc` to match, but it should be fairly straightforward.
=> [XrdCrypto] Generate DH parameters on first call to XrdCryptosslCipher

.github/workflows/build.yml, bindings/python/setup_pypi.py, packaging/rhel/xrootd.spec.in, packaging/wheel/install.sh, packaging/wheel/publish.sh, packaging/wheel/setup.py
This is part one of two PRs that will address Issue #1579.
As `distutils` and Easy Install are deprecated
c.f.:
* https://setuptools.pypa.io/en/stable/deprecated/distutils-legacy.html
* https://setuptools.pypa.io/en/stable/deprecated/easy_install.html
it is preferable convert use  of `distutils` to either use existing CPython libraries or use `setuptool`'s versions of them, as advocated by the PyPA.
* [`distutils.sysconfig` -> CPython's `sysconfig`](https://discuss.python.org/t/understanding-site-packages-directories/12959/4)
* `distutils.setup` -> `setuptools.setup`
* `distutils.core.Extension` -> `setuptools.Extension`
* `distutils.spawn.find_executable` -> [`shutil.which`](https://docs.python.org/3/library/shutil.html#shutil.which) 
However, this PR only applies
* …
=> fix: Use `shutil.which` over `distutils.spawn.find_executable` when possible

.github/workflows/build.yml
Follow up PR to PR #1591 now that Python 3 testing is already in and understood.
As long as Python 2 is still supported by XRootD it should be explicitly tested in the CI. This GitHub Actions workflow job adds testing of the built CPython 2 bindings.
=> [CI] Add Python 2 bindings test job to GHA wokrflow

.github/workflows/build.yml, bindings/python/setup.py.in, packaging/wheel/setup.py
To avoid errors in modern versions of `pip`, ensure that the version name created for the Python bindings is sanitized to be compliant with [PEP 440](https://www.python.org/dev/peps/pep-0440/)
c.f.:
* https://www.python.org/dev/peps/pep-0440/
* https://github.com/pypa/pip/issues/8368
This essentially means that the version number needs to pass `pip._vendor.packaging.version.Version()`
Example:
```python
from pip._vendor.packaging.version import Version
Version("v20220128-34c8a39")  # pip._vendor.packaging.version.InvalidVersion: Invalid version: 'v20220128-34c8a39'
Version("2022.128")  # <Version('2022.128')>
Version("2022.128+a28a91c")  # <Version('2022.128+a28a91c')>
Version("6.0.0")  # <Version('6.0.0')>
=> fix: Sanitize Python version to be PEP 440 compliant

.github/workflows/build.yml, bindings/python/CMakeLists.txt, cmake/XRootDDefaults.cmake, packaging/rhel/xrootd.spec.in
* This is part two of two PRs that will address Issue #1579.
* Requires PR #1585 to go in first for atomicity, and then will rebase on top of it.
* Resolves #1579
- There might be a few more things to _really_ resolve this, but I think this is good enough for now.
---
As directly invoking `python setup.py` is considered deprecated behavior by the PyPA, use `python -m pip install` to install the Python bindings if the Python interpreter has a valid version of pip associated with it.
If there is a valid pip, build and install the Python bindings with `python -m pip install`.
If there is no valid pip, warn the user and give them instructions on how to get pip on their machine. Attempt to still install the Python bindings by falling back on the deprecated `python setup.py build` and `python …
=> fix: Install Python bindings with `pip` if available

.github/workflows/build.yml, packaging/debian/control, packaging/debian/python3-xrootd.install
* Add `python3-pip` and `python3-setuptools` to `packaging/debian/control` for `.deb` build to use.
* Add build jobs in the `ubuntu-latest` environment GHA provides through https://github.com/actions/virtual-environments.
- Resolves #1602
=> ci: Add cmake and .deb build jobs for GHA ubuntu-latest environment

src/XrdFrm/XrdFrmMonitor.cc, src/XrdXrootd/XrdXrootdMonitor.cc
```
.../src/XrdFrm/XrdFrmMonitor.cc: In function 'XrdFrmMonitor::Init(char const*, char const*, char const*)':
.../src/XrdFrm/XrdFrmMonitor.cc:158:12: warning: array subscript 'struct XrdXrootdMonMap[0]' is partly outside array bounds of 'unsigned char[1036]' [-Warray-bounds]
158 |    mP->hdr.pseq = 0;
|    ~~~~~~~~^~~~
.../src/XrdFrm/XrdFrmMonitor.cc:155:26: note: object of size [13, 1036] allocated by 'malloc'
155 |    idRec = (char *)malloc(idLen+1);
|                    ~~~~~~^~~~~~~~~
.../src/XrdFrm/XrdFrmMonitor.cc:159:8: warning: array subscript 'struct XrdXrootdMonMap[0]' is partly outside array bounds of 'unsigned char[1036]' [-Warray-bounds]
159 |    mP->dictid   = 0;
|    ~~~~^~~~~~
.../src/XrdFrm/XrdFrmMonitor.cc:155:26: note: object of size [13, 1036] allocated by 'malloc' …
```
=> Ignore -Warray-bounds warnings from stricter check in gcc 12.

docs/PreReleaseNotes.txt, src/XrdPss/XrdPssConfig.cc
=> Do not trigger DeepLocate with pss.origin is http(s)

cmake/XRootDOSDefs.cmake
This patch enable user/packager to override operating-system-related default values such as `CMAKE__INSTALL_BINDIR`.
With the use of `GNUInstallDirs` module, package maintainers of `Linux`, `kFreeBSD` and `GNU` can override those values through `-DCMAKE_INSTALL_BINDIR=my/custom/path`. However, for OSes such as `MacOSX`, `FreeBSD` and `Solaries`, those "default" values are hard-coded and unchangeable without modifying the source code. This has already cause problem to [the Nix package](https://github.com/NixOS/nixpkgs/pull/160102#issuecomment-1041113327).
In `GNUInstallDirs`, those values are set after the prior definition are explicitly checked, E.g.
```CMake
if(NOT DEFINED CMAKE_INSTALL_BINDIR)
set(CMAKE_INSTALL_BINDIR "bin" CACHE PATH "user executables (bin)")
endif()
```
which is quite …
=> [CMake] XRootDOSDefs: Use define_default on OS-specific default paths

bindings/python/setup.py.in, packaging/wheel/setup.py
Resolves #1621
Ensure release candidates are all sanitized to the PEP 440 form of `<major>.<minor>.<patch>rc<candidate>`.
Example:
```python
from pip._vendor.packaging.version import Version
Version("v5.4.1-rc2")  # <Version('5.4.1rc2')>
Version("v5.4.1.rc2")  # <Version('5.4.1rc2')>
Version("v5.4.1rc2")  # <Version('5.4.1rc2')>
```
=> [pip] Sanitize release candidate versions to PEP 440

src/XrdAcc/XrdAccAccess.cc, src/XrdSciTokens/XrdSciTokensAccess.cc
When a per-request mapping is made (such as with SciTokens), the mapped name is not put in the typical `Entity.name` but rather an extended attribute.  Only authorization plugins that have been explicitly updated to look for this attribute can be usefully chained after per-request mapping.
These changes allow the `acc` subsystem to be chained in a useful manner after a token plugin (such as SciTokens).
=> Make the `acc` subsystem aware of request-based name mapping.

src/XrdSecgsi/XrdSecgsiProxy.cc
Hi,
I propose to change the default to 2048. This solves the problem of the too short default hash digest length from SHA1, which causes proxies to be rejected by SHA2 servers.
Cheers,
Mario
=> Increase default bits from 512 to 2048

src/XrdMacaroons/XrdMacaroonsHandler.cc, src/XrdThrottle/XrdThrottleManager.cc, src/XrdTpc/XrdTpcStream.hh
There are three commits, each to a distinct file.  All involve using `vector::resize` instead of `reserve`, and `vector::size` instead of `capacity`, and the unmodified code produces a bounds-checking assertion failure in `vector::operator[]` when compiled with `-D_GLIBCXX_ASSERTIONS`.  A [smoke test](https://github.com/paulmillar/http-tpc-utils/blob/master/bin/smoke-test.sh) was applied to the first two commits to verify that they eliminate a problem.
The first (in `XrdMacaroonsHandler.cc`) specifically fixes xrootd/xrootd#1614.  Although already closed, I think this change would be more readable.
The second (in `XrdTpcStream.hh`) is in code that was not engaged/discovered during the smoke test until the first was fixed.
The third (in `XrdThrottleManager.cc`) was found just by a scan of …
=> Modify vector's size instead of capacity to avoid bounds-checking failures

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, src/XrdHttp/XrdHttpSecurity.cc
The GSI security protocol defaults to the "trymap" logic which, according to documentation, is "try to map the DN but if unsuccessful use the hash of the client’s DN as the user identifier (username)". With this change, the XrdHttpSecurity interface will follow the same logic.
Since some sites may have special setups which rely on the old mechanism, one can get the old behavior by setting the optional new `compatNameGeneration` configuration in the `http.gridmap` setting.  For example:
```
http.gridmap compatNameGeneration /etc/xrootd/grid-mapfile
```
Would restore the old behavior.
With this change, a user can effectively match the `nomap`, `trymap`, and `usemap` settings between the XRootD and HTTP protocols and the two protocols have the same default.  Without the change, only the …
=> Have the XrdHttp extraction logic match GSI.

src/XrdTpc/XrdTpcStream.hh
Sorry, I missed something in 5ea200480df332215235e13bb02035d460cd5a46.  The `vector::shrink_to_fit` call at [`XrdTpcStream.hh` line 133](https://github.com/xrootd/xrootd/blob/master/src/XrdTpc/XrdTpcStream.hh#L133) relies upon the vector size (which used to be always 0) being less than its capacity.  (It seems it's only invoked when ['low buffer occupancy'](https://github.com/xrootd/xrootd/blob/master/src/XrdTpc/XrdTpcStream.cc#L153-L160) is detected.)  Now the (size, capacity) will only ever be either (0, 0) or (`m_capacity`, `>=m_capacity`), instead of (0, 0) or (0, `m_capacity`), so `shrink_to_fit` won't be able to fully de-allocate.  I don't think it's a functional failure, but it could mean the allocation is retained for longer than expected.
By clearing the vector just after its …
=> Vector cleared after use so it can be shrunk.

src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh
This is the improvement that was requested in the issue #1566
=> [XrdTpc] Added CLOEXEC flag for curl file descriptors

.github/workflows/build.yml, .gitlab-ci.yml, genversion.sh, packaging/makesrpm.sh
`command -v` is a POSIX safe way to find an executable program. While `which` is very common, it still requires installation on many Linux operating systems, and so `command -v` can offer a more portable alternative with a very low amount of additional cognitive overhead on the maintainers.
Additionally, use a subshell, `$()`, over backticks for command substitution as `$()` is recommended for multiple reasons including readability.
c.f.:
* https://stackoverflow.com/a/4708569/8931942
* [Why is $(...) preferred over `...` (backticks)?](http://mywiki.wooledge.org/BashFAQ/082)
* [POSIX spec for Command Substitution](https://pubs.opengroup.org/onlinepubs/9699919799/xrat/V4_xcu_chap02.html#tag_23_02_06_03)
I made the decision to leave `which` in …
=> chore: Use `command -v` over `which` for portability

.github/workflows/build.yml
Resolves #1659 
Test the build process of XRootD and the Python bindings on the `macos-latest` virtual machine provided by GitHub Actions virtual environment. The necessary build dependencies are provided by the already installed XCode environment and through Homebrew installs.
This PR is similar in scope to PR #1610.
=> ci: Add macos-latest cmake job to GHA workflow build tests

src/XrdHttp/XrdHttpReq.cc
Hi,
This is the patch to use return code 405 for mkcol if the directory already exists as discussed in #1663.
Resolves #1663
Regards,
Simon
=> [XrdHttp] Use 405 for mkcol/mkdir EEXIST

src/XrdSciTokens/XrdSciTokensAccess.cc
Before this change, directory listing is impossible with a read claim,
leading to the confusing situation that trying to access files in a directory
may return 404 but listing the directory returns permission denied.
=> Also grant Readdir when token grants read permission.

src/XrdCrypto/openssl3/XrdCryptosslCipher.cc
This should address the problem described in #1662.
1. `EVP_PKEY_derive_set_peer` requires the peer's public certificate to have exactly the same DH parameters, hence we need to merge the `OSSL_PARAMs` containing the public key with the DH parameters:
https://github.com/xrootd/xrootd/blob/7a4871cd64f153b7a704415dcc6cb5ba67254285/src/XrdCrypto/openssl3/XrdCryptosslCipher.cc#L580-L586
2. `EVP_PKEY_derive` requires for the keylen argument to contain the length of key buffer (if not null):
https://www.openssl.org/docs/man1.0.2/man3/EVP_PKEY_derive.html
```
If key is not NULL then before the call the keylen parameter should contain the length of the key buffer, if the call is successful the shared secret is written to key and the amount of data written to keylen.
```
=> [XrdCrypto] openssl3: correctly initialize cipher with public key and DH parameters

bindings/python/src/PyXRootD.hh, bindings/python/src/PyXRootDFile.cc
Writing files with XRootD and Python 3.10 currently fails with:
```python
In [4]: with XRootD.client.File() as file:
...:     status, _ = file.open(f"{eos.url}{dest}", OpenFlags.NEW)
...:     assert status.ok, status
...:     status, _ = file.write(new_data)
...:     assert status.ok, status
...:
---------------------------------------------------------------------------
SystemError                               Traceback (most recent call last)
Input In [4], in <cell line: 1>()
2 status, _ = file.open(f"{eos.url}{dest}", OpenFlags.NEW)
3 assert status.ok, status
----> 4 status, _ = file.write(new_data)
5 assert status.ok, status
File ~/mambaforge/envs/logse-sqlite/lib/python3.10/site-packages/XRootD/client/file.py:190, in File.write(self, buffer, offset, size, timeout, callback)
187 …
```
=> Fix Python 3.10+ issues from PY_SSIZE_T_CLEAN not being set

src/XrdSys/XrdSysIOEventsPollKQ.icc, src/XrdSys/XrdSysIOEventsPollPoll.icc, src/XrdSys/XrdSysIOEventsPollPort.icc
Uses the same solution that was applied to the epoll implementation in https://github.com/xrootd/xrootd/commit/5ece48c16de3c6c1508fc84eea65d10333020854.
I've only tested on macOS but hopefully the same applies to `XrdSysIOEventsPollPoll` and `XrdSysIOEventsPollPort`.
Fixes #1673. See that issue for more details.
=> Don't abort if it looks like we're about to fork

.github/workflows/build.yml, packaging/wheel/install.sh
Resolves #1668
In PR #1585 a syntax error was introduced  as `shutil.which` is a method of the Python 'shutil' module and not a module, so the proper import is `from shutil import which` as regardless of the CPython version `import shutil.which` will result in a
```pytb
ModuleNotFoundError: No module named 'shutil.which'; 'shutil' is not a package
```
This error was causing all runs of `packaging/wheel/install.sh` to use the legacy behavior of `python setup.py install` regardless if `shutil.which` was available or not.
As all CPython versions that have `shutil.which` (Python 3.3+) are able to run `packaging/wheel/setup.py` then they will be able to take advantage of having pip be able to create a valid wheel during install time. In the event that a very old version of pip is used, an egg …
=> [FIX] Fix import syntax to enable shutil.which check

cmake/XRootDSystemCheck.cmake, src/XrdDaemons.cmake
This is required for using 64 bit atomics on some 32 bit architectures.
=> Check if we need libatomic to use atomic operations in the C++ code

src/XrdSciTokens/XrdSciTokensAccess.cc
This introduces configuration-file-controlled tracing of SciTokens-related messages and a number of detailed log messages.
As typical, this is controlled by a new config variable:
```
scitokens.trace [level] [level] ...
```
Where level can be one of `all`, `none`, `debug`, `info`, `warning`, or
`error`.
Roughly, the levels imply:
- Error: fatal issue in plugin configuration
- Warning: Potentially-problematic configuration or token that is invalid
- Info: Informational messages about the plugin.  Shouldn't have any logging per-request
- Debug: Verbose, per-request details about the tokens.
The default is error + warning; debug is not recommended for continuous production settings but is immensely helpful in solving problems.
=> Populate XrdSciTokens with more detailed log messages.

.github/workflows/build.yml
Following up @simonmichal's https://github.com/xrootd/xrootd/pull/1672#issuecomment-1109472205 this removes unnecessary sourcing of `devtoolset-7` in the sdist build jobs. With `devtoolset-7` no longer providing a compiler to the environment at detection time in `setup.py` also add `gcc-c++` to the list of packages to install with `yum`.
Also simplify installs (c.f. https://github.com/xrootd/xrootd/pull/1672#issuecomment-1108914342) by installing with
```
python3 -m pip --verbose install --upgrade ./dist/xrootd-*.tar.gz
```
(Note the use of `--upgrade` is only necessary on tags where there is properly formatted SemVer version info in the `xrootd.egg-info`. A dev version like '20220426.post7797547' doesn't need the --upgrade, but it is easier to just always use it.)
For better logging and …
=> [CI] Simplify sdist install jobs and logging

bindings/python/setup.py.in, packaging/rhel/xrootd.spec.in
Resolves #1698
In CPython 3.10 `distutils` was formally marked as deprecated and it will be removed from CPython in 3.12. To avoid complications, deprecate use of `distutils` moving forward in favor of using `setuptools` as recommended.
For Python 3.7+ (which should by default have `pip` `v22.0.0+` and `setuptools` `v57.5.0+`) use:
* `setuptools._distutils.core` over `distutils.core`
* CPython's `sysconfig` library over `distutils.sysconfig`
If `setuptools._distutils` (added in `setuptools` `v48.0.0`) is not available in the Python 3 environment, fall back to using `distutils.core` and `distutils.sysconfig`.
For Python < 3.7 (so Python 3.6 only for all intents and purposes) fall back to `distutils.sysconfig` in the event that `setuptools` is `v48.0.0+`.
Additional supporting advice given …
=> [Python] Deprecate distutils for setuptools for Python 3.7+

.github/workflows/build.yml, .gitlab-ci.yml
To avoid the Fedora build failure that is happening only in GitHub Actions jobs, add 
```
git config --global --add safe.directory "$GITHUB_WORKSPACE"
```
to the GitHub Actions workflow job to avoid the issues of https://github.com/actions/checkout/issues/760.
=> [CI] Avoid unsafe repository error from GitHub Actions

src/XrdAcc/XrdAccAccess.cc, src/XrdAcc/XrdAccAuthorize.hh, src/XrdApps/XrdAccTest.cc, src/XrdHttp/XrdHttpReq.cc, src/XrdMacaroons/XrdMacaroonsAuthz.cc, src/XrdOfs/XrdOfs.cc, src/XrdSciTokens/XrdSciTokensAccess.cc, src/XrdThrottle/XrdThrottleFile.cc, src/XrdXrootd/XrdXrootdXeq.cc
This PR introduces a lower-privileged versions of `AOP_Insert` and `AOP_Create` which do not permit overwriting / destroying existing data during `rename` and `open` operations, respectively.  Through the use of the `O_EXCL` flag in the filesystem, xrootd now refuses to overwrite data if a session has the lower-privileged version instead of the full-fledged authorization.
With this, the `UPLOAD` Macaroon authorization and `storage.create` SciToken authorization are correctly implemented.
Note one other fixup had to be included: for HTTP MOVE operations, we now append the token correctly to the destination as well as the source.
Finally, because https://github.com/xrootd/xrootd/pull/1644 iterates through the list of operations, I decided to apply this branch on top of #1644; please do not …
=> Separate out authorization to overwrite data

src/XrdClHttp/XrdClHttpPosix.cc
https://github.com/xrootd/xrootd/blob/master/src/XrdClHttp/CMakeLists.txt#L1 adds `${Davix_INCLUDE_DIRS}/davix` due to which xrootd failed to find `davix/auth/davixauth.hpp`.
=> Fix davix/auth path

genversion.sh, src/XrdOuc/XrdOucStream.cc, src/XrdPfc/XrdPfcFile.cc, src/XrdPosix/XrdPosixDir.hh, src/XrdSecsss/XrdSecProtocolsss.cc, src/XrdSys/XrdSysFAttrBsd.icc
This change fixes compilation errors at FreeBSD 13.1 (with `-DENABLE_KRB5=OFF`).
=> Fix compilation errors at FreeBSD.

.github/workflows/build.yml
Explicitly set `XRD_PYTHON_REQ_VERSION="2.7"` at CMake configure to allow for Python 2.7 builds until Python 2 support is dropped in XRootD `v5.5.0`.
c.f. Issue #1711
=> [CI] Set XRD_PYTHON_REQ_VERSION for Python 2.7 builds

src/XrdCl/XrdClAsyncSocketHandler.cc, src/XrdCl/XrdClStream.cc, src/XrdCl/XrdClStream.hh
Hi,
This patch is intended to fix a crash seen on EOS MGMs. The crash is consistent with the race between reset() and use of the unique_ptr rspreader and reqwriter. A trace obtained indicated a reset was happening in AsyncSocketHandler::OnReadTimeout() while the unique_ptr was being sued concurrently in AsyncMsgWriter::Write().
The race is understood to be started in AsyncSocketHandler::OnReadTimeout(), triggered by the pStream->OnReadTimeout call (XrdClAsyncSocketHandler.cc:698). On this timeout condition the XrdClStream may first Close() the AsyncSocketHandler. Close() calls pPoller->RemoveSocket(), which eventually calls XrdSys::IOEvents::Channel::Delete(), which will remove the socket from the IOEvents poller with XrdSys::IOEvents::Poller::Detach().
The above calls are done under the …
=> [XrdCl] Avoid race condition in AsyncSocketHander on use of reader/writer objects after link is re-enabled

src/XrdCl/XrdClFileStateHandler.cc
This is thought to solve a XrdCl hang: an XrdCl synchronous call waiting for the callback apparently indefinitely. (This issue has entry EOS-4323 the EOS tracker). The problem was seen to be associated with a network glitch on the service machines hanging a messaging thread which uses XrdCl.
The flow is believed to be that ReOpenFileAtServer() returns an error, e.g. due to DNS name lookup failure. RunRecover() then sets the FileStateHandler's pFileState = Error, but sets no error in pStatus. The Error state causes subsequent calls like FileStateHandler::Close() or Stat() etc. to fail by returning the status contained in pStatus. In this cases pStatus still contains an OK status. Thus the client waits forever for a response that never comes, as it was never submitted nor failed at …
=> [XrdCl] Set the error status if the re-connection fails early during recovery

src/XrdSys/XrdSysLogger.cc
The corresponding specification is [here](https://pubs.opengroup.org/onlinepubs/9699919799.2018edition/basedefs/termios.h.html).
=> Fix deprecated-header warning.

src/XrdCrypto/XrdCryptoLite_bf32.cc
Hello,
This is a proposed fix for the issue #1725; allowing sss to work on centos9s. See the issue for some more details about the reported problem.
Openssl v3 introduced "providers" and this patch loads the legacy provider so that the blowfish cipher can be used.
=> [XrdCrypto] bf32: Load "legacy" provider for blowfish in openssl v3

src/XrdCl/XrdClOperations.hh
Until now, the failed request resulted in the responsehandler being called immediately. 
This meant that no new thread was created and the reading mutex would be blocking forever (even when a pipeline is started as Async).
By replacing it with a job a new thread is created for the answer.
=> Create Job on failed Run method in XrdClOperations

src/XrdZip/XrdZipCDFH.hh
Added a maximum length parameter to the parsing of the CDFH to detect corruptions in the CDFH length parameters (e.g. filenameLength) and to avoid reading over the end of the file.
Default argument is zero to allow for compatibility. 
The CDFH "Parse" method passes the new constructor argument.
=> MaxSize in CDFH constructor

src/XrdZip/XrdZipLFH.hh
A maximum length is given to the constructor to detect corruption and prevent reading over the borders of the LFH.
In case the lengths read from the buffer are larger than the buffer itself, bad_data is thrown.
=> Length check in the LFH constructor

src/XrdCl/XrdClZipArchive.cc, src/XrdZip/XrdZipEOCD.hh
Check the EOCD length against the actual buffer size to detect corruption in the EOCD and to avoid reading over the end of the file. Default argument is still zero to allow for compatibility. 
In the XrdClZipArchive's OpenArchive method, the call to the EOCD constructor catches the bad_data error.
Additionally added a check of the "cdOffset" and "cdSize" attributes of the EOCD object against the archive size.
In case of failure, the OpenArchive operation is stopped and returns an error status.
=> MaxSize of the EOCD constructor and check against file size

src/XrdCl/XrdClXRootDMsgHandler.cc
Hello,
This is part of a set of 3 PRs for a set of changes to avoid various problems seen while investigating some EOS crashes or issues. There may well be discussion over these PRs.
This PR changes the location where the XRootDMsgHandler "timeout fence" is set in the case of pgread responses.
The motivation for the change is avoiding a crash seen during some tests - I'll attach a description of a test and a trace below.
The change moves setting the fence for non-pgwrite kxr_status messages (i.e. pgread) from InspectStatusRsp() to Examine(). This avoid a race where the MessageHandger could be removed + deleted in the time between these two methods called, via AsyncMsgReader.  A consequence is that the fence is set even in the case the pgread response consists of only a single …
=> [XrdCl] Avoid that pgread responses could be timedout while being processed

src/XrdCl/XrdClZipArchive.hh, src/XrdEc/XrdEcReader.cc, src/XrdEc/XrdEcReader.hh, tests/XrdEcTests/MicroTest.cc
Erasure Coding Vector Read implementation and unit test. Maps requests from file space to erasure coded "stripe space" and sends Vector Read requests to each required host.
Copies the answers back to the buffers provided by the user, either provided as one buffer for all data or as separate buffers for each element in the vector.
=> EC Vector Read

src/XrdSciTokens/XrdSciTokensAccess.cc
In what appears to be a refactor gone wrong, the `username` variable is moved to itself.  On RHEL7's compiler, this appears to be a no-op.  In RHEL8 (probably correctly) it clears out the string, un-setting the username completely.
@simonmichal - please also backport to the 5.5.x branch.
=> Fix self-move.

src/XrdTls/XrdTlsContext.cc
If that SSL Context was used to generate a Session, it will only decrease the reference counter, not delete it
=> [XrdTlsContext] Free the SSL Context when a new one is going to be used to generate the session

src/XrdHttp/XrdHttpProtocol.cc, src/XrdTls/XrdTlsContext.cc, src/XrdTls/XrdTlsContext.hh, src/XrdXrootd/XrdXrootdConfig.cc
A boolean flag has been added to the constructor and the Clone() method of the XrdTlsContext class. If set to true, the TLS context created or cloned will run the CRLRefresh thread after having been succesfully initialized.
=> [XrdTls] The start of the CRLRefresh thread is now triggered in the constructor of the XrdTlsContext class

src/XrdTls/XrdTlsSocket.cc
If we do not do that, next time a XROOTD client using the link that got an SSL error will see a SSL Socket error and will have to retry
=> [XrdTlsSocket] Shutdown the socket if a SSL error happens when trying to accept a connection

src/Xrd/XrdConfig.cc, src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, src/XrdTls/XrdTlsContext.cc, src/XrdTls/XrdTlsContext.hh
This refresh parameter did not work at all even before my previous changes.
I made it work for the refresh thread of the XrdTlsContext of HTTP and XRootD.
=> [XrdTls] The tlsca 'refresh' directive in the configuration file is now taken into account for both XrootD and HTTP TLS context

src/XrdHttp/XrdHttpExtHandler.cc, src/XrdHttp/XrdHttpReq.cc
Hi Andy,
During normal EOS operations, we noticed that one storage node crashed in the XrdHttpExtHandler.cc:93 line.
@smithdh (many thanks again!) could reproduce the issue by starting an EOS FST and submitting, via netcat: 
```
nc -Cv localhost 11000
Ncat: Version 7.50 ( https://nmap.org/ncat )
Ncat: Connected to ::1:11000.
GET // HTTP/1.1
```
Notice the first line starting with a space. This space, at the beginning of the first line would prevent the `XrdHttpReq::parseFirstLine()` method to call the `XrdHttpReq::parseResource()` one.
Once the constructor of an `XrdHttpExtReq` is called, the line `headers["xrd-http-fullresource"] = req->resourceplusopaque.c_str();` will segfault as the resource was not parsed. Indeed, the `resourceplusopaque` XrdOucString has not been asigned and its the …
=> [XrdHttp + XrdHttpExtHandler] Fixes a segmentation fault happening when a client sends a first line starting with a space

src/XrdTpc/XrdTpcState.cc, src/XrdTpc/XrdTpcState.hh, src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh
Implemented by doing a HEAD request on the Source server's file path and getting the content-length out of it. 
This solves the issue #1754
=> [XrdHttpTPC] TPC-Pull: passing the source file size information to the OFS layer via opaque parameter "oss.asize"

src/XrdMacaroons/XrdMacaroons.cc, src/XrdMacaroons/XrdMacaroonsAuthz.cc, src/XrdMacaroons/XrdMacaroonsAuthz.hh, src/XrdMacaroons/export-lib-symbols
In order to use ZTN with a token library, the library must provide a XrdSciTokensHelper object.  This implements the interface inside the Macaroons::Authz object, allowing ZTN authentication to be utilized with a macaroon-based token.
This can be enabled with the following configuration directive:
```
sec.protocol -tokenlib libXrdMacaroons-5.so
```
=> Implement XrdSciTokensHelper interface for macaroons.

cmake/XRootDSystemCheck.cmake, src/XrdServer.cmake
- Check all sizes (8, 16, 32, 64)
- Check increment (operator++)
Change inspired by a similar patch recently added to Debian's ceph package. Fixes xrootd build on Debian riscv64.
=> Make the check for the need for libatomic more thorough

docs/PreReleaseNotes.txt, src/XrdOss/XrdOssApi.cc
This is a change so that XrdOssSys::Mkdir returns -EEXIST (rather than the positive value); the function should return a negative number in case there is an error.
=> [Server] Make sure Mkdir returns a negative code for an EEXIST error

cmake/XRootDDefaults.cmake
Fixes: ff67c2a0, Closes: #1804
=> [CMake] Make switches for server-only options dependent on XRCL_ONLY=FALSE

src/XrdTpc/XrdTpcTPC.cc
Hi @abh3 ,
Now the problem is fixed. I tried to do an  HTTP TPC PULL request against an EOS instance at CERN, and it works now !
Cheers,
Cedric
=> [XrdHttpTPC] Fixes the HTTP TPC PULL transfer issue when authentication is necessary to perform a transfer

src/Xrd/XrdLinkXeq.cc
While looking into another problem I noticed an apparently not-handled case in XrdLinkXeq::SendIOV when it resumes a write after an incomplete writev: For instance in the case of iocnt=2, if the writev returns a short number of bytes from the first iov, iov[0], then remainder of iov[0] is sent by write(), and then iov[1] is sent by writev() [all as intended]; but then an attempt would be made to write() the contents of iov[2]. This should either give an error like ("bad address") for the link, or possibly send some trailing nonsense data to the client.
In fact I don't think this was related to the problem I had been looking at, and I didn't find any indication this is happening. e.g. even if I look at a busy server I don't notice any "bad address" link errors. So maybe this is rather rare …
=> [Xrd] Fix a short writev recovery case

src/XrdCl/XrdClXRootDTransport.cc
The expected way for XRootDTransport::GetBody to work with kXR_status reposes is that on the first call (with repeated calls in case of suRetry) it only the response header, not including the data. But there is a case where it could read all of the data - which I think is part of the problem of issue #1808. This PR should restore the expected behaviour.
=> [XrdCl] Be sure to only read the header of kXR_status messages at first

src/XrdCl/XrdClURL.cc
A Channel's ChannelInfo contains an instance of a SIDManager which is a reference counted instance keyed by a channel id. SIDMgrPool::GetSIDMgr() accepts a URL, from which it calculates the channel id and returns the appropriate instance. Currently GetSIDMgr is passed the channel id directly when setting up the ChannelInfo. There is a problem that some URLs produce a channel id which cannot be re-parsed to a URL and back to the channel id again.
e.g. the url
root://machine:1194//big5?xrd.k5ccname=/foo
has channel id:
root://machine:1194?xrd.k5ccname=/foo
but instantiating a URL with the above and requesting its channel id gives
://
(Some channel id can be parsed in this way, but e.g. those with special opaque key-values can not). This patch changes the value passed to GetSIDMgr to the url …
=> [XrdCl] Ensure URL::GetChannelId returns an Id which can be parsed again as a url

src/XrdOssCsi/XrdOssCsiTagstoreFile.hh
This PR fixes a missing header error on MacOS when building with GCC.
Confirmed to fix the build on 10.6.8 with `gcc12`.
Clang builds on latest MacOS versions are all good too: https://github.com/macports/macports-ports/pull/15807 (checks pass).
Code borrowed from: https://gerrit.pixelexperience.org/plugins/gitiles/external_libtextclassifier/+/b23e2125be90bbf6124e9cd5684fc93026c5ec4d/util/base/endian.h
=> xrootd: fix missing byteswap.h error on MacOS build with gcc

src/XrdApps/XrdCpConfig.cc
Before:
```
xrdcp -f --cksum adler32 "root://eosams02.cern.ch//eos/ams/Data/AMS02/2011A/RawData/1308783516?eos.ruid=0" /var/tmp/dump
[1.195GB/1.195GB][100%][==================================================][102MB/s]    
Run: [ERROR] CheckSum error
=================================================================
==30521==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 24 byte(s) in 1 object(s) allocated from:
#0 0x7f537cff336f in operator new(unsigned long) (/usr/lib64/libasan.so.5+0x10e36f)
#1 0x7f537cac208d in XrdCksCalcadler32::New() /eos-xrootd-code/src/./XrdCks/XrdCksCalcadler32.hh:95
SUMMARY: AddressSanitizer: 24 byte(s) leaked in 1 allocation(s).
```
After the fix:
```
xrdcp -f --cksum adler32 "root://eosams02.cern.ch//eos/ams/Data/AMS02/2011A/RawData/1308783516?eos.rui …
```
=> [XrdApps] Fix small memory leak

bindings/python/setup.py.in
Resolves #1830
Drop all usage of `setuptools._distutils` in favor of pure `setuptools`. This effectively solves the problems that were present in the attempt in PR #1585 and PR #1700. With this, it is now possible to go further and drop direct usage of `distutils` in favor of `setuptools`. This effectively happens with the removal of `setuptools._distutils` as
```python
try:
from setuptools import setup, Extension
...
```
should always pass, and so this just makes this explicitly clear by removing the `try/except` block.
=> feat: Use setuptools over setuptools._distutils.core

bindings/python/CMakeLists.txt
My previous debugging of the problem was wrong, staged installations (with `DESTDIR` set don't work with the old patch, it only worked when I was using a branch where the version of XRootD was different than what I had installed, so pip didn't complain).
Issue: #1768
=> Show install command being run by pip and fail when pip install fails

.github/workflows/build.yml
Fixes for failures seen in my fork of xrootd. Funnily enough, these were only failing in the [fork](https://github.com/amadio/xrootd/actions/runs/3601016323), for the same [hash](https://github.com/xrootd/xrootd/actions/runs/3600561342) as master.
=> Small fixes for GitHub Actions

src/XrdSciTokens/README.md, src/XrdSciTokens/XrdSciTokensAccess.cc
The default INI reader will concat duplicate section+name settings with a '\n' separator.  The new OverrideINIReader will simply take the last value in the INI configuration file.
For example:
```
[Issuer https://chtc.cs.wisc.edu/icecube]
issuer = https://chtc.cs.wisc.edu/icecube
base_path = /icecube/path1
[Issuer https://chtc.cs.wisc.edu/icecube]
issuer = https://chtc.cs.wisc.edu/icecube
base_path = /icecube/path2
```
Will result in a configuration with `base_path` set to `/icecube/path2`
Replaces #1859
=> Adding the OverrideINIReader for SciTokens

src/XrdOuc/XrdOucPgrwUtils.cc
=> Fix for issue 1864

src/XrdTls/XrdTlsContext.cc
=> XrdTlsContext: Recreate session cache in the Clone() method

src/XrdOssCsi/XrdOssCsiPages.hh
~~~
/builddir/build/BUILD/xrootd-5.5.1/src/XrdOssCsi/XrdOssCsiPages.hh:95:22: error: field 'fn_' has incomplete type 'const std::string' {aka 'const std::__cxx11::basic_string<char>'}
95 |    const std::string fn_;
|                      ^~~
In file included from /usr/include/c++/13/iosfwd:41,
from /usr/include/c++/13/bits/shared_ptr.h:52,
from /usr/include/c++/13/condition_variable:45,
from /builddir/build/BUILD/xrootd-5.5.1/src/XrdOssCsi/XrdOssCsiRanges.hh:38,
from /builddir/build/BUILD/xrootd-5.5.1/src/XrdOssCsi/XrdOssCsiRanges.cc:32:
/usr/include/c++/13/bits/stringfwd.h:72:11: note: declaration of 'std::string' {aka 'class std::__cxx11::basic_string<char>'}
72 |     class basic_string;
|           ^~~~~~~~~~~~
/builddir/build/BUILD/xrootd-5.5.1/src/XrdOssCsi/XrdOssCsiPages.hh:96:22: …
=> Add missing include causing build failure with gcc 13

src/XrdPosix/XrdPosixAdmin.cc
~~~
/builddir/build/BUILD/xrootd-5.5.1/src/XrdPosix/XrdPosixAdmin.cc: In member function 'FanOut': /builddir/build/BUILD/xrootd-5.5.1/src/XrdPosix/XrdPosixAdmin.cc:69:27: error: argument 1 value '4294967295' exceeds maximum object size 2147483647 [-Werror=alloc-size-larger-than=]
69 |    uVec = new XrdCl::URL[i];
|                           ^
/usr/include/c++/13/new:128:26: note: in a call to allocation function 'operator new []' declared here
128 | _GLIBCXX_NODISCARD void* operator new[](std::size_t) _GLIBCXX_THROW (std::bad_alloc)
|                          ^
~~~
Failure happens with gcc 13 on 32 bit systems.
=> Fix build failure due to possible large memory allocation

src/XrdVoms/XrdVomsMapfile.cc
We've run into an issue where the FQAN didn't have a "role" at all, it was just `/<VO name>`; this patch handles that situation.
=> Add a default value for "role" which should handle VOMS attributes where role is missing entirely

src/XrdCl/XrdClAsyncMsgReader.hh, src/XrdCl/XrdClPostMasterInterfaces.hh, src/XrdCl/XrdClXRootDMsgHandler.cc, src/XrdCl/XrdClXRootDMsgHandler.hh, src/XrdCl/XrdClXRootDTransport.cc, src/XrdCl/XrdClXRootDTransport.hh
Move kXR_status response handling to `AsyncMsgReader`.
=> [XrdCl] Refactor kXR_status response handling.

src/XrdXrootd/XrdXrootdXeq.cc
This is a change to address #1898; similar to the proposed fix attached in that issue discussion.
=> [Server] Avoid a race condition during deferred file close

.github/workflows/build.yml, cmake/XRootDOSDefs.cmake, docs/PreReleaseNotes.txt, docs/ReleaseNotes.txt, packaging/rhel/xrootd.spec.in, src/Xrd/XrdConfig.hh, src/Xrd/XrdPoll.hh, src/XrdAcc/XrdAccGroups.cc, src/XrdCl/XrdClFileStateHandler.hh, src/XrdCl/XrdClMonitor.hh, src/XrdCl/XrdClXRootDMsgHandler.cc, src/XrdCms/XrdCmsCluster.cc, src/XrdNet/XrdNetMsg.cc, src/XrdNet/XrdNetSecurity.cc, src/XrdOfs/XrdOfsHandle.cc, src/XrdOssCsi/XrdOssCsiTagstoreFile.hh, src/XrdOuc/XrdOucBackTrace.cc, src/XrdPosix/XrdPosix.cc, src/XrdPosix/XrdPosixFile.hh, src/XrdPosix/XrdPosixLinkage.hh, src/XrdPosix/XrdPosixPreload.cc, src/XrdSys/XrdSysPlatform.hh, src/XrdSys/XrdSysPthread.hh, src/XrdTls/XrdTlsTempCA.cc, src/XrdVoms/XrdVomsMapfile.cc
Based on work from and replaces pull request #1632.
=> Support for musl libc and uclibc

src/XrdPfc/XrdPfcFile.cc
When direct reads ("bypass mode") are in use, the code was failing to increment the number of bytes serviced in the read request.  When there were no errors, that means the overall read operation returned 0 instead of the bytes read.
This resulted in 100% failure rate for HTTP requests when direct read mode was activated.
This was tested by disabling prefetch and then always forcing direct reads via this simple patch:
```
--- a/src/XrdPfc/XrdPfcFile.cc
+++ b/src/XrdPfc/XrdPfcFile.cc
@@ -804,7 +804,7 @@ int File::ReadOpusCoalescere(IO *io, const XrdOucIOVec *readV, int readVnum,
read_req = new ReadRequest(io, rh);
// Is there room for one more RAM Block?
-            Block *b = PrepareBlockRequest(block_idx, io, read_req, false);
+            Block *b = nullptr; // = …
```
=> Fix direct read for PFC

src/XrdHttp/XrdHttpReq.cc
This PR (a) advertises the server supports byte range requests and (b) fixes the byte range request when resuming a download.
This allows libraries which can resume interrupted partial downloads to function with the xrootd server.
=> XrdHttp: Fix byte range requests

src/XrdSecztn/XrdSecProtocolztn.cc
As proposed an even simpler solution to disable token validation in XrdSecztn by using "-tokenlib none".
=> [XrdSecztn] Allow option '-tokenlib none' to disable token validation

src/XrdHttp/XrdHttpExtHandler.cc, src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh
HTTP provides a response to include a "trailer" in addition to the better-known "header".  If a user sets the following headers in the request:
```
X-Transfer-Status: true
TE: trailers
Transfer-Encoding: chunked
```
Then the response will used chunked encoding and indicate, on the last returned chunk, whether an error has occurred.
Clients aware of these headers can now receive an error message from XRootD if there's an IO error in the middle of the response.  This is expected to be useful in XCache use cases where failure mid-response is somewhat more common.
=> Allow XRootD to return trailers indicating failure

src/XrdSecztn/XrdSecProtocolztn.cc
As available in kerberos,gsi and sss I need to have a way to define in a multithreaded application the location of a token using CGI since environment variables don't work here. I have added the same mechanism supported by XrdCl to specify a tokenfile location in the URL, in this case you can say something like 
```
xrdcp foo root://....?xrd.ztn=/tmp/mytokenfile
```
=> [XrdSecztn] Allow to point to a token file using CGI '?xrd.ztn=tokenfile

src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh, src/XrdPfc/XrdPfcConfiguration.cc, src/XrdPfc/XrdPfcIOFile.cc, src/XrdPfc/XrdPfcIOFile.hh
When in caching proxy mode, have the HTTP response populate the standardized `Age` field so the client knows the approximate age of the object in cache.
@osschar
=> Report cache object age for caching proxy mode

src/XrdSys/XrdSysE2T.cc
On Linux platforms, the "authentication denied" error is mapped to the EBADE errno (as EAUTH doesn't exist).  That results in authentication errors in XrdPss to generate the "invalid exchange" error message (this is because XrdPss takes the errno from XrdPosix and XrdPosix returns EBADE/EAUTH).
Rather than start tinkering with alternate errno's for this case, simply map EBADE's error message to "authentication denied".
Before:
```
Server responded with an error: [3030] Unable to open /user/ligo/test_access/access_ligo; invalid exchange
```
After:
```
Server responded with an error: [3030] Unable to open /user/ligo/test_access/access_ligo; authentication denied
```
This misleading error message was found when working on #1915
=> Override error message for EAUTH

cmake/XRootDDefaults.cmake, packaging/rhel/xrootd.spec.in, src/CMakeLists.txt, src/XrdSciTokens.cmake
This partially reverts commit 984efbc72bdad86b43923569f4dfa707b7a287a2. Actually, libXrdSecztn does not depend on scitokenscpp, we can build it on the client side even when `-DENABLE_SCITOKENS=FALSE`.
@abh, I believe this is what you meant initially that we should do, right?
=> Adjust build rules to not depend on scitokenscpp to build libXrdSecztn

src/XrdApps/XrdClRecordPlugin/XrdClReplay.cc
introduced by introduction of buffer-pool for buffer allocation
=> [XrdApps] xrdreplay: fix SEGVs when verifying or printing replays

src/XrdCl/XrdClStream.cc, src/XrdCl/XrdClStream.hh
This is a possible fix for issue #1942
=> [XrdCl] Do not reuse sessionId when a new Stream object is made

src/XrdCrypto/XrdCryptoAux.cc, src/XrdCrypto/XrdCryptoX509.cc, src/XrdCrypto/XrdCryptosslAux.cc, src/XrdCrypto/XrdCryptosslgsiAux.cc
To fix issue #1955 and #985, concerning authentication failures for certificates/proxies with notbefore/after dates during the changeover hour of daylight saving time.
=> [XrdCrypto] Fix utility function XrdCryptosslASN1toUTC to return in UTC

src/XrdCrypto/XrdCryptosslAux.cc
Allow for GeneralizedTime (> year 2049) in certificates.
Fix also a bug in renormalizing the Year from UTCTime parsing.
=> Possible fix for the time parsing related issue (#1969)

.github/workflows/build.yml, src/XrdHttp/XrdHttpReq.cc
=> [XrdHttp] Clear digest header between requests

src/XrdSciTokens/README.md, src/XrdSciTokens/XrdSciTokensAccess.cc
Some token issuers, such as LIGOs, put the desired username in a claim besides the `sub` claim.  This provides flexibility so they can use the `uid` claim for mapping purposes instead of `sub`.
=> Implement ability to have the token username as a separate claim

src/XrdApps/XrdClProxyPlugin/ProxyPrefixFile.hh
Hello. To fix #1993, a missing specialisation for PgRead is added to ProxyPrefixFile (in the XrdClProxyPlugin).
This patch also adds a few other missing method overrides. i.e.
(i) Added missing override of PgRead, Write (1 already present, 2 other overloads added), PgWrite, VectorWrite, WriteV.
(ii) Did not add override for Read(6 argument version); present in the base (XrdCl::FilePlugIn) but not called from XrdClFile. Method appears unused, possibly could be removed in release 6. (The XrdClPlugInInterface.hh is public so can't change before then).
(iii) Likely we're missing ReadV, but this is not present in the base. The ReadV() interface was added after release of xrootd5, so maybe ReadV can be added to XrdClPlugInInterface for release 6.
(iv) Added override specifier on declarator of …
=> [XrdApps] Let XrdClProxyPlugin work with PgRead

src/XrdXrootd/XrdXrootdFile.cc
This is a fix for issue #1995. (Fixes #1995)
=> [Server] Allow XrdXrootdFile::Serialize() to used to wait more than once

src/XrdCl/XrdClChannel.cc
This is (hopefully) a fix for issue #1883
=> [XrdCl] Avoid possibility of Channel unregistering the wrong task

src/XrdXrootd/XrdXrootdFile.cc
This is a proposed fix for a problem seen with EOS; I suppose it's probably only possible with xrootd servers configured with plugins so that they use the delayed close feature (i.e. when the Ofs file close() can return SFS_STARTED).
I haven't opened an issue ticket for now (to describing what was seen, or attempts to reproduce the problem), but I could do so later if we want, but for now I won't. Essentially it seems the wrong file was closed or bytes were read from the wrong file.
This PR aims to correct the file handle number returned by XrdXrootdFileTable::Add() in case a heldSpot in the external table gets reused.
=> Correct the fh returned when reusing a handle from external table

src/XrdCl/XrdClOperations.cc, src/XrdCl/XrdClOperations.hh, src/XrdCl/XrdClUtils.cc, src/XrdCl/XrdClUtils.hh, src/XrdCl/XrdClZipArchive.cc
Intended to fix #2004. Initially in draft.
=> Fix problem creating ZIP archive with lots of entries

src/XrdHttp/XrdHttpExtHandler.cc
A SEGV was seen with a server with an http.exthandler configured. Sample trace from eos build of xrootd, v5.5.5:
```
#0  0x00007f30bc76a8c1 in __strlen_sse2_pminub () from /lib64/libc.so.6
#1  0x00007f30b81e6824 in std::char_traits<char>::length (__s=0x0)
at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/char_traits.h:322
#2  std::string::assign (__s=0x0, this=0x7f300bcb03f8)
at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/basic_string.h:4333
#3  std::string::operator= (__s=0x0, this=0x7f300bcb03f8)
at /opt/rh/devtoolset-8/root/usr/include/c++/8/bits/basic_string.h:3656
#4  XrdHttpExtReq::XrdHttpExtReq (this=<optimized out>, req=<optimized out>, pr=<optimized out>)
at /usr/src/debug/xrootd-5.5.9/src/XrdHttp/XrdHttpExtHandler.cc:92
#5  0x00007f30b81e110e in XrdHttpReq::ProcessHTTPReq …
```
=> [HttpExtHandler] Avoid SEGV incase request has object for opaque data but no content

src/XrdHttp/XrdHttpReq.cc
This commit updates the handling of HTTP headers to conform to HTTP standards and improve support for chunked transfer encoding and status trailers.
Previously, the server incorrectly expected to receive the "Transfer-Encoding: chunked" header in HTTP requests. However, it has been realized that the "Transfer-Encoding" header is reserved for HTTP responses and should not be anticipated in an HTTP request.
We've now corrected this behavior by removing the check for the "Transfer-Encoding" header in the incoming request. Instead, we now set the internal variable `m_transfer_encoding_chunked` when the client includes the custom header "X-Transfer-Status: true". This change aligns with the original intention, indicating that the client is prepared to receive a response using chunked transfer …
=> Update HTTP Header Handling for Chunked Encoding and Status Trailer

src/XrdTls/XrdTlsTempCA.cc
The latest updates to glibc headers adds __nonnull to the fclose()
Declaration in old version:
extern int fclose (FILE *__stream);
Declaration in new version:
extern int fclose (FILE *__stream) __nonnull ((1));
This change causes a compilation error in xrootd:
~~~
/builddir/build/BUILD/xrootd-5.5.5/src/XrdTls/XrdTlsTempCA.cc:54:48: error: ignoring attributes on template argument 'int (*)(FILE*)' [-Werror=ignored-attributes]
54 | typedef std::unique_ptr<FILE, decltype(&fclose)> file_smart_ptr;
|                                                ^
~~~
This commit rewrites the code so the error is not triggered.
=> Fix build failure with latest glibc

src/XrdHttp/XrdHttpProtocol.cc
Before this fix, no performance markers were sent to the client after a HTTP TPC transfer was started, there were weird numbers instead:
```
> COPY /tmp/BIGFILE_10GB HTTP/1.1
> User-Agent: curl/7.29.0
> Host: machine.cern.ch:1096
> Accept: */*
> Destination: https://machine.cern.ch:2001/tmp/BIGFILE_10GB_COPY
>
< HTTP/1.1 201 Created
< Connection: Keep-Alive
< Server: XrootD/v5.2.0-99-osghotfix...687
< Content-Type: text/plain
< Transfer-Encoding: chunked
< 
9b
9c
9c
32
0
```
After the fix, the perf markers are back:
```
> COPY /tmp/BIGFILE_10GB HTTP/1.1
> User-Agent: curl/7.29.0
> Host: machine.cern.ch:1096
> Accept: */*
> Destination: https://machine.cern.ch:2001/tmp/BIGFILE_10GB_COPY
> 
< HTTP/1.1 201 Created
< Connection: Keep-Alive
< Server: XrootD/v5.2.0-99-osghotfix...687
< …
```
=> XrdHttp: Corrected regression where no performance markers were sent to the client during a HTTP TPC transfer

src/XProtocol/XProtocol.hh, src/XrdHttp/XrdHttpReq.cc
The mapping between errno error codes and XRoot protocol error code has also been changed. ENOTEMPTY is mapped to kXR_ItExists
=> XrdHttp: The deletion of a non-empty directory returns a 405 error code instead of 500

src/XrdHttp/XrdHttpReq.cc
Fixes https://github.com/xrootd/xrootd/issues/2018.
=> [XrdHttp] A GET with 'Want-Digest' header request issued on a non-existing file will return a 404 error instead of 500

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpReq.cc
Fixes issue https://github.com/xrootd/xrootd/issues/2003
=> [XrdHttp] A bad request error is returned in the case a client provides too many range requests

packaging/common/cmsd@.service, packaging/common/frm_purged@.service, packaging/common/frm_xfrd@.service, packaging/common/xrootd@.service
This is a first attempt to implement stronger security settings in systemd service files. The sandboxing settings added with this commit are commented out until they can receive more testing, as discussed in issue #2033.
=> Add sandboxing settings to systemd service files.

docs/man/xrdcp.1, src/XrdCl/XrdClConstants.hh, src/XrdOuc/XrdOucPsx.cc, src/XrdPss/XrdPssConfig.cc, src/XrdSsi/XrdSsiClient.cc
This value has been chosen as default based on benchmarks that demonstrated that this is the minimum required number of threads to be able to saturate a link of 100Gbps.
Note: I have a small concern about clients launched by the server starting up way too many threads if enough of them are launched together after this patch. We should ensure this change will not cause problems for EOS, or make sure to set the number of event loops back to the old value in the environment in EOS instances before upgrading.
=> Increase default number of parallel event loops to 10

src/XrdCl/XrdClSIDManager.cc, src/XrdCl/XrdClSIDManager.hh, src/XrdCl/XrdClXRootDTransport.cc
To address issue #2042. (Fixes #2042).
=> [XrdCl] Fix potential stream timeout when a new request is sent to an idle stream

src/XrdCl/XrdClPostMaster.cc
This change is avoid the possibility of accessing pChannelMap (a std::map) during PostMaster::QueryTransport, while that map is modified by another thread, e.g. by one executing PostMaster::Send. A crash due to this was seen in a test, but is probably rare.
=> [XrdCl] Avoid race in postmaster QueryTransport

src/XrdCrypto/XrdCryptoFactory.cc
This change is to avoid race in accessing some global structures during XrdCryptoFactory::GetCryptoFactory. This did cause some authentication failures during a heavily multithreaded test, which was starting many concurrent gsi connections, and with ParallelEvtLoop>1. It is probably a rare problem.
=> [XrdCrypto] Avoid race in GetCryptoFactory

src/XrdSciTokens/XrdSciTokensAccess.cc
When setting up mapping rules, if the user feature was utilized, a logic error would cause the rule to be ignored.
Fixes #2056
=> Fix logic error in user mapping

src/XrdHttp/XrdHttpReq.cc
This commit reintroduces a header parser for `Transfer-Encoding: chunked` to maintain compatibility with the EGI Nagios probe. This issue was first mentioned in #2058.
Fixes: [d96b2b70487e159b47c24925abcfa00f975ec3d6](https://github.com/xrootd/xrootd/pull/2009/commits/d96b2b70487e159b47c24925abcfa00f975ec3d6), [#2009](https://github.com/xrootd/xrootd/pull/2009)
=> [XrdHttp] Add back parsing of Transfer-Encoding header

src/XrdCrypto/XrdCryptosslX509Crl.cc, src/XrdCrypto/XrdCryptosslX509Crl.hh, src/XrdTls/XrdTlsTempCA.cc
=> XrdTls: XrdTlsTempCA - CRLs containing critical extensions are inserted at the end of the bundled CRL file

src/XrdTls/XrdTlsTempCA.cc
This PR is coming from the PR https://github.com/xrootd/xrootd/pull/2073.
The Maintenance thread creates bundle CA and CRL files. Before this modification, the output files created by the maintenance were open and closed for each CA and CRL read. It is not the case anymore. There is only one open at the beginning of the processing and one close at the end.
=> XrdTls: XrdTlsTempCA - Refactored CASet and CRLSet to open the output file only once before the processing

src/Xrd/XrdScheduler.cc
During a test I was starting an xcache that happened to be configured to use OssCsi (e.g. with config option "pfc.cschk net tls cache"). Server crashed at startup with:
```
#0  0x00007ffff7876e99 in XrdScheduler::Start() () from /lib64/libXrdUtils.so.3
#1  0x00007fffee922336 in XrdOssCsi::Init(XrdSysLogger*, char const*, char const*, XrdOucEnv*) ()
from /lib64/libXrdOssCsi-5.so
#2  0x00007fffee922491 in XrdOssAddStorageSystem2 () from /lib64/libXrdOssCsi-5.so
#3  0x00007ffff7b5d450 in XrdOfsConfigPI::AddLibOss(XrdOucEnv*) () from /lib64/libXrdServer.so.3
#4  0x00007ffff7b5f20c in XrdOfsConfigPI::Load(int, XrdOucEnv*) () from /lib64/libXrdServer.so.3
#5  0x00007fffef17ea42 in XrdPfc::Cache::Config(char const*, char const*) () from /lib64/libXrdPfc-5.so
#6  0x00007fffef175b39 in …
```
=> [Xrd] Add initialiser in one of the XrdScheduler constructors

src/XrdHttp.cmake, src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, src/XrdHttp/XrdHttpReadRangeHandler.cc, src/XrdHttp/XrdHttpReadRangeHandler.hh, src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh, src/XrdHttp/XrdHttpUtils.hh, tests/XrdHttpTests/XrdHttpTests.cc
This change was mostly extracted from a larger pull request that included other features, #1957. The current change aims to be a minimal refactor in preparation for other work in the same area of the code.
( The followup work should be a fix for #1976 )
=> [XrdHttp] Refactoring the read issuing for GET and fix issues 1976, 2076

bindings/python/docs/source/conf.py, bindings/python/docs/source/install.rst
The include statement in rst includes the included file verbatim and therefore assumes that the included file is also in rst format. If it is a different format, like e.g. md, there are many syntax errors and warnings.
Use mdinclude when including the README.md file during the documentation build.
=> .md is not .rst

src/XrdHttp/XrdHttpReq.cc
Small change to using the minimum of either the used buffer size or the first 13 characters of a chunk to read the chunk length.
=> [XrdHttp] Fix max to min when reading chunk length

src/XrdHttp/XrdHttpExtHandler.cc, src/XrdHttp/XrdHttpExtHandler.hh, src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh, src/XrdTpc.cmake, src/XrdTpc/PMarkManager.cc, src/XrdTpc/PMarkManager.hh, src/XrdTpc/XrdTpcMultistream.cc, src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh
Hi @abh3 ,
I think this functionality is progressing well.
I've managed to have some packet marking emitted with HTTP TPC transfers PUSH and PULL single and multi (PULL) streams.
Now, by looking at the JSON of the firefly, I'm not sure this is working 100%.
If I do a PULL single stream `curl -v --capath /etc/grid-security/certificates -L -X COPY  -H "Source: $DST" -H "SciTag: 144" "$SRC"` for example, here are the JSON fireflies that is sent by the pulling server at the beginning and the end of the transfer:
```json
{"version":1,"flow-lifecycle":{"state":"start","current-time":"2023-10-19T16:06:25.224773+00:00","start-time":"2023-10-19T16:06:25.224773+00:00"},"usage":{"received":0,"sent":136},"netlink":{"rtt":0.061},"context":{"experiment-id":2,"activity-id":16,"application":"http-tpc"},"f …
```
=> Implemented HTTP TPC Packet Marking

CMakeLists.txt, packaging/debian/libxrootd-dev.install, packaging/rhel/xrootd.spec.in
The installed cmake files are now generated and contain architecture dependent information. Installing them in datadir (/usr/share) now results in conflicts if packages for more than one architecture is installed in parallel. Move the installed cmake files to libdir (/usr/lib(64)?, /usr/lib/<architecture>).
Found by Debian's MultiArch hinter.
=> Installed CMake files are architecture dependent

src/XProtocol/XProtocol.cc, src/XProtocol/XProtocol.hh, src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpReq.cc, src/XrdPfc/XrdPfc.cc, src/XrdPfc/XrdPfc.hh, src/XrdPfc/XrdPfcConfiguration.cc, src/XrdPfc/XrdPfcFSctl.cc, src/XrdPss/XrdPss.cc
This is a new implementation of  #1954 using XrdPfcFsctl object in XrdPssFile::Open()
Note: 
A stderr code ETIME is returned when cache does not exist. The ETIMEDOUT code would be interpreted as delay error in XrdOfs::Emsg().
=> Implement only-if-cached cache control using XrdPfcFsctl

.github/workflows/CI.yml, src/Xrd/XrdLinkMatch.hh, src/Xrd/XrdTcpMonPin.hh, src/XrdCks/XrdCksAssist.hh, src/XrdCl/CMakeLists.txt, src/XrdCl/XrdClArg.hh, src/XrdCl/XrdClCtx.hh, src/XrdCl/XrdClFinalOperation.hh, src/XrdEc/CMakeLists.txt, src/XrdHeaders.cmake, src/XrdOuc/XrdOucPList.hh, src/XrdOuc/XrdOucPinObject.hh, src/XrdPosix/XrdPosixMap.hh, src/XrdPosix/XrdPosixXrootdPath.hh, src/XrdSec/XrdSecEntityPin.hh, src/XrdSfs/XrdSfsGPFile.hh, src/XrdZip/XrdZipCDFH.hh, src/XrdZip/XrdZipDataDescriptor.hh, src/XrdZip/XrdZipExtra.hh, src/XrdZip/XrdZipUtils.hh, tests/check-headers.sh
@apeters1971 Reported to me that some headers that he needed to develop Zip support on EOS were not installed by XRootD, so this pull request adds a script that checks that each installed public and private XRootD header can be included individually without errors. The subsequent commits are fixes for the errors reported by this script. The intention is to identify which headers may have missing includes, missing forward declarations, or missing header dependencies, that is, headers from XRootD which it includes, but were not installed by the install target.
=> Fix header dependencies and missing includes/declarations

src/XrdEc/XrdEcReader.cc
```
.../src/XrdEc/XrdEcReader.cc:934:72: error: ‘info’ may be used uninitialized [-Werror=maybe-uninitialized]
934 |                                 blockMap[blkid]->stripes[strpid].resize( info ->GetSize() );
|                                                                        ^
.../src/XrdEc/XrdEcReader.cc:932:42: note: ‘info’ was declared here
932 |                         XrdCl::StatInfo* info;
|                                          ^
```
=> Fix maybe-uninitialized warning

tests/XRootD/smoke.sh, tests/XrdEc/MicroTest.cc, tests/XrdEcTests/MicroTest.cc
Many features in xrootd require file system support for extended file attributes. Tests that run tests on these features fail if the file system does not support them. The /tmp directory in many Linux installations is using a tmpfs partition. The tmpfs file system does not support extended file attributes, so some tests that use /tmp to store files fail.
This commit changes some affected tests so that they create the temporary directory containing the test files in the current working directory instead of /tmp.
Example of failure:
```
17/34 Test #20: XrdEc::AlignedWriteTest ...................................................***Failed    0.07 sec
You have selected:
Selected tests/
Selected tests/MicroTest::AlignedWriteTest
Running:
.F
MicroTest.cc:506:Assertion
Test name: …
```
=> Avoid /tmp when running some tests

src/XrdSciTokens/XrdSciTokensAccess.cc
Hello,
I noticed a segv; it seems to have been seen already by @bbockelm in #1986 (the trace in the second comment). In that ticket it was thought to be due to the same cause as the trace in the first comment. (Trace in first comment fixed by change in XrdHttpProtocol.cc https://github.com/xrootd/xrootd/commit/b3c667300c30709c1d929ff1fcdb2f2bc2d90ca2 / https://github.com/xrootd/xrootd/commit/14834e6d50f437e6dc33eff9c315fd985b317d6d).
Instead the crash in second comment of #1986 appears to be due similar problem in SciTokens. I've attached a patch. Brian, do you think you be able to review (or try to reproduce your original crash with/without this?)
Thank you!
(Trace from the crash I saw is below)
```
Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffeb773700 …
```
=> [SciTokens] Initialize SecEntity.addrInfo to avoid SEGV

src/XrdCl/XrdClLocalFileHandler.cc
As discussed in https://github.com/xrootd/xrootd/pull/2129#issuecomment-1822270037
If extended attributes are not supported xattr->Get() returns -ENOTSUP. When this small negative value is cast to a size_t in the call to new on the following line it becomes a very large integer and the request to allocate this enormous memory block fails with a std::bad_alloc exception.
This commit adds a check on the returned size and returns an error if it is negative avoiding triggering the std::bad_alloc exception.
=> Fail gracefully in case of unsupported extended file attributes

src/XrdTls/XrdTlsContext.cc
Outside most grid contexts, we need to present the certificate chain in the TLS handshake for the verification path through the intermediate CA to the root.
This commit switches over to the corresponding OpenSSL function call.
Fixes the ability to use most CAB CAs with XRootD.
If, for some reason, the prior behavior is desired, the host certificate file can be limited to contain only the host certificate.  I don't expected this to cause any backward compatibility issues as certificates issued by CAs needing this functionality were already broken.
Fixes #2126
=> Switch from using a cert file to a cert chain file

tests/XrdCephTests/CephParsingTest.cc, tests/XrdCl/XrdClFileCopyTest.cc, tests/XrdCl/XrdClFileSystemTest.cc, tests/XrdCl/XrdClFileTest.cc, tests/XrdCl/XrdClLocalFileHandlerTest.cc, tests/XrdCl/XrdClOperationsWorkflowTest.cc, tests/XrdCl/XrdClPoller.cc, tests/XrdCl/XrdClPostMasterTest.cc, tests/XrdCl/XrdClSocket.cc, tests/XrdCl/XrdClThreadingTest.cc, tests/XrdCl/XrdClUtilsTest.cc, tests/XrdCl/XrdClZip.cc, tests/XrdEc/MicroTest.cc
EXPECT_EQ( A, B ) provides more useful diagnostics than EXPECT_TRUE ( A == B ).
EXPECT_NE( A, B ) provides more useful diagnostics than EXPECT_TRUE ( A != B ).
=> Get more useful diagnostics in case of test failures

tests/XrdCl/XrdClLocalFileHandlerTest.cc
This change was accidentally reverted in a later commit.
This commit reverts the accidental revert.
=> Redo accidentally reverted change

src/XrdHttp/XrdHttpReq.cc, src/XrdNet/XrdNetPMark.cc, src/XrdNet/XrdNetPMark.hh, src/XrdNet/XrdNetPMarkCfg.cc
Hi @abh3 ,
I took a bit of time to work on adapting the packet marking to comply with the specification where the `scitag.flow` has to have values between 65 and 65535.
I did two commits. The first one is changing the min and max values that a scitag can have and that modifies the `XrdHttp` part to check the validity of the scitag value given by the user.
The second one also touches the configuration of the scitag configuration from a JSON file (taking into account min and max values). I also modified the validation of the PMark handle where a scitag=0 will only be valid for HTTP-TPC (according to the specs). For other protocols, the scitag given by the user will have to be between 65 and 65535, otherwise the traffic will not be tagged.
Thanks for your review!
Cheers,
Cedric
=> [XrdNet and XrdHttp] Scitag min and max value change

src/XProtocol/XProtocol.cc, src/XrdCl/XrdClXRootDMsgHandler.cc, src/XrdZip/XrdZipCDFH.hh, src/XrdZip/XrdZipEOCD.hh, src/XrdZip/XrdZipZIP64EOCD.hh, src/XrdZip/XrdZipZIP64EOCDL.hh
Do not dereference unaligned pointers.
Fixes: #2131
=> Avoid bus errors

src/XrdSys/XrdSysPlatform.hh
Here are some additional includes for Hurd and BSD.
Is it supposed to be compilable on windows? I have not tried to do anything inside the "#ifdef WIN32".
=> Add #include <byteswap.h> for BSD and GNU/Hurd

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh
After the initial login to the xrootd bridge (and after parsing the first request's headers), perform a `kXR_set` for the monitoring info.  The `User-Agent` header is sent as the info.
This is only done for the first request of a connection.  It is assumed that all subsequent connections belong to the same user agent.
=> Send User-Agent as the monitor info

src/XrdSecgsi/XrdSecgsitest.cc
```
/builddir/build/BUILD/xrootd-5.6.4/src/XrdSecgsi/XrdSecgsitest.cc: In function ‘pdots(char const*, bool)’:
/builddir/build/BUILD/xrootd-5.6.4/src/XrdSecgsi/XrdSecgsitest.cc:90:15: error: ‘%s’ directive argument is null [-Werror=format-overflow=]
90 |    printf("|| %s ", t);
|               ^~
```
=> Fix compilation error reported with gcc 14

src/XrdPosix/XrdPosixConfig.cc
The documentation says "increasing values produce more detail".  However, `DebugLevel 1` was mapped to "Info" and `DebugLevel 3` was mapped to "Error".
With this, `pss.setopt DebugLevel N` has the following meanings:
- 0: None
- 1: Error
- 2: Warning
- 3: Info
- 4: Debug
- 5: Dump
Previously, 1 and 3 were swapped.
=> Fix ordering of the debug levels

src/XrdSciTokens/XrdSciTokensAccess.cc
If a token has a broad scope and all the listed restricted paths are more specific, then try to generate ACLs that include the restricted paths.
Example: suppose we have a token with scope `storage.read:/` but restricted paths `/foo` and `/bar`.  Currently, we will reject the scope and give the token no permissions.  With this commit, we will generate acls of `read:/foo` and `read:/bar`.  So, as long as the access being attempted is within the restricted path, we can permit it.
Fixes #2132
=> Attempt to use restricted paths even when scope is more generic

src/XrdSciTokens/XrdSciTokensAccess.cc
stat permissions are implicitly required for storage systems for create, modify  and delete operations. Currently tokens with purely create and modify permissions would fail with permission denied on stat on attempts to perform those operations
=> add stat permissions to create, modify and write

src/XrdApps/XrdCpConfig.cc, src/XrdApps/XrdCpFile.cc, src/XrdApps/XrdCpFile.hh, src/XrdPss/XrdPssUtils.cc
In https://github.com/PelicanPlatform/xrdcl-pelican, we are developing a XrdCl plugin that can talk to the infrastructure for a new project, christening the URL scheme `pelican://`.
This commit adds the new schema so it can be utilized from both xrdcp (primarily for testing) and XCache.
=> Add support for pelican:// protocol

src/XrdTpc/XrdTpcTPC.cc
Solves https://github.com/xrootd/xrootd/issues/2186
=> [XrdTpcTPC] Send a 400 - invalid request - response when a user requests more than 100 streams for the HTTP-TPC PULL transfer

src/XrdSciTokens/XrdSciTokensAccess.cc
On 
https://github.com/xrootd/xrootd/pull/2184,
@bbockelm 's suggested change was accidentally reverted during the line break rebase. 
Sorry for the mistake
=> missed commit on mkdir permission more restricted on superfolder

src/XrdApps/Xrdadler32.cc, src/XrdBwm/XrdBwmLogger.cc, src/XrdHttp/XrdHttpReq.cc, src/XrdPfc/XrdPfcConfiguration.cc, src/XrdPosix/XrdPosixPreload32.cc, src/XrdSecsss/XrdSecsssKT.cc, src/XrdXrootd/XrdXrootdPrepare.cc, src/XrdXrootd/XrdXrootdProtocol.cc
Debian has enabled 64 bit time_t for most of their 32 bit architectures. This PR fixes some issues to support this.
=> Fixes for 64 bit time_t on 32 bit systems

src/XrdSciTokens/README.md, src/XrdSciTokens/XrdSciTokensAccess.cc
This is the follow-up to #2122.
On a per-issuer basis, decide if the mapping information is only to be done after authorization passes or if the mapping information should be kept and passed to the subsequent plugin.
Tests performed:
1.  Scitoken containing correct scopes is authorized in default setting.
2. Scitoken containing group information passes group information to the next plugin in default setting.
3. Scitoken that is mapped in mapfile passes in default setting to next plugin.
4. Scitoken that is mapped in mapfile but has no scopes is ignored when authorization_strategy is set to `capability`
5. Scitoken containing group information and incorrect scopes (no capability-based mapping) is passed to next plugin.
Note there's no config changes in the main xrootd config file but an …
=> Flexible SciTokens authorization strategy (v2)

src/XrdSciTokens/README.md, src/XrdSciTokens/XrdSciTokensAccess.cc
This implements the ability to have the groups claim in the token as a separate variable `groups_claim` to be set in the config, analogous to the username claim in #1978 . If `groups_claim` is not set in the config, it defaults back to the previously hard coded `"wlcg.groups"`.
=> Implement ability to have the token groups as a separate claim

src/XrdCrypto/XrdCryptosslAux.cc, src/XrdCrypto/XrdCryptosslRSA.cc, src/XrdCrypto/XrdCryptosslX509.cc
With openssl3 the EVP_PKEY_check() may be more computationally expensive than with previous openssl versions. Currently XrdCl can call this check multiple times for the same key, e.g. when copying constructing an XrdCryptosslRSA object. This patch is to avoid making repeated, but similar, calls to EVP_PKEY_check().
=> [XrdCrypto] Avoid some repated calls of EVP_PKEY_check on the same key

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, src/XrdTpc/XrdTpcConfigure.cc
The XrootD server administrator can now configure HTTP handlers without having configured TLS.
They can do so by adding "notls" after the path of the library. Example: `http.exthandler xrdtpc libXrdHttpTPC.so notls`
By default, HTTP external handlers can only be loaded if TLS is enabled.
Fixes #2099
=> [XrdHttp] External handlers can be loaded without TLS

src/XrdNet/XrdNetPMarkFF.cc, src/XrdNet/XrdNetUtils.cc, src/XrdNet/XrdNetUtils.hh, src/XrdTpc/XrdTpcMultistream.cc, src/XrdTpc/XrdTpcPMarkManager.cc, src/XrdTpc/XrdTpcPMarkManager.hh, src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh
This allows to improve HTTP-TPC transfers packet marking precision. If the packet marking is enabled and the client submitted a request with a SciTag header, then the connection of the socket will be done within a timeout of 5 seconds. The TPC transfer will fail if the socket could not be connected.
Currently, the timeout is 5 seconds, hardcoded. I can put that in a variable for sure if needed. I have no clue of what a reasonable timeout for a connection could be. I'm open to suggestions :)
=> [XrdTpcTPC] PMark - Connect curl socket at socket creation

src/XrdHttp/XrdHttpProtocol.cc
When we detect the end of header in the client request ("\r\n"), we will actually continue to read data from the buffer if there are still some to read.
The case when a client submits a HTTP request like `\r\nGET ...` is also covered.
Fixes #1964
=> [XrdHttp] Improved first-line and header parsing

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpReq.cc
I've reverted the previous commit creating a regression and just added a check that ensures each header line provided by the client terminates with `\r\n`. If that is the case, a 400 Bad request error is replied with an error message saying that the headers are malformed.
=> 2273 regression in header parsing

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, src/XrdHttp/XrdHttpReq.cc, src/XrdMacaroons/XrdMacaroonsHandler.cc, src/XrdTpc/XrdTpcState.cc, src/XrdTpc/XrdTpcTPC.cc
Fixes #2259
Did a separate PR, please feel free to reject the previous one :)
There's a new option that one can set in the server config file `http.keepheadercase yes`. If it is set, the headers coming from the client that are **not** lower-case will be inserted as-is in the `allheaders` map in addition to their lower-case version.
=> [XrdHttp/TPC/Macaroons] Client header parsing is now case-insensitive

src/XrdThrottle/XrdThrottleManager.cc, src/XrdThrottle/XrdThrottleManager.hh
When examining some plots of the new g-stream data, we were surprised to see the aggregate I/O time was non-monotonic (by definition, the sum of all time since start should always be monotonic!).
Two bugs were discovered:
- Incorrect handling of the timespec normalization.
- Incorrect clock used for the timer.  Switched to `CLOCK_MONOTONIC`.
Once the second item was handled, the code only uses POSIX functions so enabling Mac OS X (my main development platform) was trivial and I adjusted the defines accordingly.
I would suggest considering the patch for backport to a current release series if a subsequent release is planned.
=> Fix timing on the throttle plugin

src/XrdTpc/XrdTpcMultistream.cc, src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh
All the errors returned to the client now start with "failure:". If the failure is due to a curl error, the error message will contain "HTTP library failure=X" where X is the error reported by libcurl. In addition, all failures indicate the local and the remote resources involved in the TPC transfer that failed.
=> [XrdTpcTPC] Improved curl error reporting to the client

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpReq.cc, src/XrdOuc/XrdOucUtils.cc, src/XrdOuc/XrdOucUtils.hh, tests/CMakeLists.txt, tests/XrdOucTests/CMakeLists.txt, tests/XrdOucTests/XrdOucUtilsTests.cc
Fixes #2222
Unit tests were added, one can see what the effect of the obfuscation is. I basically obfuscate 'Authorization', 'TransferHeaderAuthorization' headers and hdr2cgi 'authz='.
=> XrdHttp: obfuscate token authz leaking to the logs

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, src/XrdTpc.cmake, src/XrdTpc/XrdTpcConfigure.cc, src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh, src/XrdTpc/XrdTpcUtils.cc, src/XrdTpc/XrdTpcUtils.hh, tests/CMakeLists.txt, tests/XrdTpcTests/CMakeLists.txt, tests/XrdTpcTests/XrdTpcTests.cc
The administrator can now use this option in order to allow some client HTTP headers to be passed to the OFS layer as opaque information. It works exactly the same way as the http.header2cgi configuration. E.g: the active server of a HTTP/TPC PULL transfer receives the header 'ArchiveMetadata' and 'tpc.header2cgi ArchiveMetadata archivemetadata' is configured. If a client submits a 'ArchiveMetadata: test' header with their request, the opaque archivemetadata=test will be provided to the XrdSfsFile open() function.
The implementation was done as follow:
- Put the HTTP http.header2cgi parsing logic to a public static function of the XrdHttpProtocol class (`parseHeader2CGI()`)
- Add a hdr2cgimap attribute to the TPCHandler
- Call this function in both `http.header2cgi` and `tpc.header2cgi` …
=> [XrdTpcTPC] Added tpc.header2cgi configuration

src/XrdCl/XrdClClassicCopyJob.cc
```
/builddir/build/BUILD/xrootd-5.7.0/src/XrdCl/XrdClClassicCopyJob.cc:722:35: error: ‘virtual XrdCl::XRootDStatus {anonymous}::XRootDSource::GetXAttr(std::vector<std::tuple<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > >&)’ was hidden [-Werror=overloaded-virtual=]
722 |       virtual XrdCl::XRootDStatus GetXAttr( std::vector<XrdCl::xattr_t> &xattrs )
|                                   ^~~~~~~~
/builddir/build/BUILD/xrootd-5.7.0/src/XrdCl/XrdClClassicCopyJob.cc:1153:35: note:   by ‘virtual XrdCl::XRootDStatus {anonymous}::XRootDSourceZip::GetXAttr(std::vector<XrdCl::XAttr>&)’
1153 |       virtual XrdCl::XRootDStatus GetXAttr( std::vector<XrdCl::XAttr> &xattrs )
| …
```
=> [XrdCl] Fix hidden overloaded virtual compilation error

src/XrdHttp/XrdHttpReq.cc
Leave connection open after redirection if keepalive is enabled
At present, XRootD immediately closes HTTP connections when replying with a redirection, while still indicating keep-alive support in the reply. This is causing occasional problems for some HTTP clients, as they try to immediately reuse the connection, before the connection closure has been processed.
This change resolves the issue in local testing, but a thoughtful review would be appreciated to ensure connection reuse won't add other issues.
=> [XrdHttp] Apply keepalive when redirecting HTTP clients

src/XProtocol/XProtocol.hh, src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpReq.cc
Map various connection-related errors in XrdCl in XCache all the way through to the HTTP layer.
This allows a failure to connect to the origin to be represented with the correct status code ("Bad Gateway"); currently, a down origin results in a 500 ("Internal Server Error") which is misleading for users.
=> Add support for "Bad Gateway" HTTP status code

src/XrdPosix/XrdPosixXrootd.cc
If the file-open failed to finalize (this code path is hit in XCache when a non-existent file is attempted to be opened), then the `fp` object leaked.
This eventually fills up the file descriptor table in XrdPosix after 1M file-not-found responses from the cache, a denial of service until the xrootd server is restarted.
Fixes #2302 
@amadio - I'd suggest this is a reasonable backport to any active release branches.
=> Do not leak file pointer on open error

src/XrdCl/XrdClAsyncDiscardReader.hh, src/XrdCl/XrdClAsyncMsgWriter.hh, src/XrdCl/XrdClAsyncRawReader.hh, src/XrdCl/XrdClClassicCopyJob.cc, src/XrdCl/XrdClCopy.cc, src/XrdCl/XrdClFS.cc, src/XrdCl/XrdClFileStateHandler.cc, src/XrdCl/XrdClFileSystem.cc, src/XrdCl/XrdClMessage.hh, src/XrdCl/XrdClMessageUtils.cc, src/XrdCl/XrdClSocket.cc, src/XrdCl/XrdClStream.cc, src/XrdCl/XrdClTPFallBackCopyJob.cc, src/XrdCl/XrdClThirdPartyCopyJob.cc, src/XrdCl/XrdClURL.cc, src/XrdCl/XrdClURL.hh, src/XrdCl/XrdClUtils.cc, src/XrdCl/XrdClXRootDMsgHandler.cc, src/XrdCl/XrdClXRootDMsgHandler.hh, src/XrdClHttp/XrdClHttpFileSystemPlugIn.cc, src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpReq.cc, src/XrdOuc/XrdOucUtils.cc, src/XrdOuc/XrdOucUtils.hh, src/XrdPfc/XrdPfc.cc, src/XrdPfc/XrdPfcTrace.hh, src/XrdPosix/XrdPosixAdmin.hh, tests/XrdOucTests/XrdOucUtilsTests.cc
Fixes #2296
I added new attributes/member functions to obfuscate the URL/description only once in a lifetime of the URL/Request object. Those functions GetDescription() and GetPath() were used everywhere in the XrdCl logging code.
They were replaced by GetObfuscatedDescription() and GetObfuscatedPath().
I also changed the way I obfuscate --> I now use regexes which simplify a lot the code. Unit tests were adapted accordingly with an addition of test cases.
=> [XrdCl, XrdHttp] Obfuscated more token authz in logging

src/XrdOuc/XrdOucUtils.cc, src/XrdOuc/XrdOucUtils.hh
@amadio discovered that the XrdEc tests were 10 times slower than usual. This slowness came from the fact that for each call to XrdOucUtils::obfuscateAuth(...) 2 std::regex were instanciated. The instanciation of those two std::regex objects is expensive as there is a compilation logic to ensure the regex is correct. Those 2 regexes are now constructed only once in the lifetime of the XRootD process by creating a static std::vector<std::regex>.
=> [XrdOucUtils] Speed-up authz obfuscation

src/Xrd/XrdConfig.cc
Found by lintian:
I: xrootd-server: spelling-error-in-binary permision permission [usr/bin/cmsd]
I: xrootd-server: spelling-error-in-binary permision permission [usr/bin/xrootd]
=> [Server] Correct spelling (permision → permission)

src/XrdSys/XrdSysE2T.cc
Seen on hppa Linux where EBADE is 160.
```
In function ‘int {anonymous}::initErrTable()’,
inlined from ‘void __static_initialization_and_destruction_0()’ at /<<PKGBUILDDIR>>/src/XrdSys/XrdSysE2T.cc:92:28,
inlined from ‘(static initializers for /<<PKGBUILDDIR>>/src/XrdSys/XrdSysE2T.cc)’ at /<<PKGBUILDDIR>>/src/XrdSys/XrdSysE2T.cc:128:1:
/<<PKGBUILDDIR>>/src/XrdSys/XrdSysE2T.cc:70:26: warning: array subscript 160 is above array bounds of ‘const char* [144]’ [-Warray-bounds=]
70 |    if (Errno2String[EBADE]) {
|        ~~~~~~~~~~~~~~~~~~^
/<<PKGBUILDDIR>>/src/XrdSys/XrdSysE2T.cc: In function ‘(static initializers for /<<PKGBUILDDIR>>/src/XrdSys/XrdSysE2T.cc)’:
/<<PKGBUILDDIR>>/src/XrdSys/XrdSysE2T.cc:48:28: note: while referencing ‘{anonymous}::Errno2String’
48 |        const char* …
```
=> Protect against array index out of bounds

src/XrdSut/XrdSutCache.hh
The XrdSutCacheArg_t type is used to pass arguments of different types. The type used must be wide enough to fit the widest of the types passed. One of the types passed is time_t, which can be 64 bits wide also on 32-bit systems. So a long, which is 32 bits wide on a 32-bit system is not sufficient.
This commit changes the type to long long.
Fixes: #2272
=> Change type in XrdSutCacheArg_t to long long

tests/XRootD/fuse.sh
Calling `openssl rand` with 0 as the argument is an error:
```
$ openssl rand -base64 0
rand: Use -help for summary.
$ echo $?
1
```
=> Avoid test failures when $RANDOM returns a multiple of 1024

Doxyfile
The files generated by doxygen whose file names contain the string unnamedN where N is a number are not generated using predictable names.
This happens when running doxygen using multiple threads.
Set NUM_PROC_THREADS=1 to work around this issue.
See: https://github.com/doxygen/doxygen/issues/11138
=> Reproducible doxygen output

bindings/python/src/PyXRootDFile.cc
In a previous commit the timeout variables were changed from uint16_t to time_t. Since time_t can be 64 bits the Python bindings need to use unsigned long long.
Related: #2236, #2237
=> time_t can be 64 bit

src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh
This is a first attempt at "fixing" #2299.  Instead of invoking a filesystem `stat`, then opening the path, it changes the GET code to _always_ try the 'open' first.
If the open fails with an `kXR_isDirectory` (i.e., `EISDIR`), then the code falls back to doing a directory listing.
At the minimum, this will halve the number of `stat` requests the underlying storage will see as `stat` is done twice per request if the requests are sent sequentially.  At best, it'll eliminate nearly all `stat`s under high concurrency given the OFS will collapse the open files into a single handle and some OSS's will cache the results of the first `fstat`.
This state machine for GET is notoriously tricky so I'd appreciate a review by @ccaffy or @smithdh.  Tests done by hand:
- Download full file.
- Download …
=> Avoid calling 'stat' on HTTP GET

src/XrdHttp/XrdHttpProtocol.cc
If one does a GET /path/to/file.txt?authz=... the authz will be obfuscated in the logline "Parsing first line:"
=> [XrdHttp] Obfuscated potential token leaking during first line parsing

src/XrdPfc/XrdPfc.cc, src/XrdPfc/XrdPfc.hh, src/XrdPfc/XrdPfcConfiguration.cc, src/XrdPfc/XrdPfcFile.cc, src/XrdPfc/XrdPfcFile.hh, src/XrdPfc/XrdPfcIOFile.cc, src/XrdPfc/XrdPfcIOFile.hh
`PFC` part of addressing #2349.
1. the branch is on xroot.git so it's potentially easier to manipulate by @abh3  and @amadio.
2. the PR is agianst master -- it is targeting 5.7.2.
- For most parts, uses stat of the data file for reporting.
- st_size is always set to the full size of the remote file. This is either obtained from cinfo file or from xattr variable created when the file is initially placed into cache (this is a new optimization).
- st_atim is set to 0 when the file is not considered to be fully cached, as determined by the pfc.onlyifcached config settings.
1. XrdPfc::Cache::Stat() now always returns 0 (success) or an -errno
code. Specification in XrdOucCahce::Stat() says it should return > 0 (ie, 1)
if the operation is to be forwarded to the federation. It is questionable if …
=> [Pfc] Stat call: fix behavior and improve performance, part of #2349

src/XrdSeckrb5/XrdSecProtocolkrb5.cc
Fixes the following potential crash:
```sh    
Core was generated by `/usr/bin/xrootd -l /var/log/xrootd/xrootd.log -c /etc/xrootd/xrootd-krb5.cfg -k'.
Program terminated with signal SIGSEGV, Segmentation fault.
*0  0x00007f16f2cc52e2 in XrdSecProtocolkrb5::Authenticate (this=0x7f16d8000b90, parms=0x7f16f0423418, error=0x7f16f0423440)
at xrootd-5.7.2/src/XrdSeckrb5/XrdSecProtocolkrb5.cc:514
514                              (krb5_const_principal)Ticket->enc_part2->client,
[Current thread is 1 (Thread 0x7f16f04246c0 (LWP 2274325))]
(gdb) bt
0  0x00007f16f2cc52e2 in XrdSecProtocolkrb5::Authenticate (this=0x7f16d8000b90, parms=0x7f16f0423418, error=0x7f16f0423440)
at xrootd-5.7.2/src/XrdSeckrb5/XrdSecProtocolkrb5.cc:514
1  0x00007f16f35d092f in XrdXrootdProtocol::do_Auth …
```
=> [Seckrb5] Avoid null pointer dereference

src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh, tests/XRootD/http.cfg, tests/XRootD/http.sh, tests/XRootD/test.sh
If the client declares the expected size of the uploaded object, then pass this information on to the OSS layer via the `oss.asize` CGI.
This is relevant for the S3 backend as the S3 protocol requires object sizes to be declared ahead of time.  If XRootD doesn't provide this information, then the S3 OSS backend has to buffer the uploaded object to know the final size, costing both in overall throughput and memory usage.
=> [XrdHttp] Set oss.asize if object size is known

src/Xrd/XrdLinkCtl.cc, src/Xrd/XrdLinkCtl.hh, src/XrdSut/XrdSutPFile.cc
```
In file included from /usr/include/features.h:524,
from /usr/include/c++/15/x86_64-redhat-linux/bits/os_defines.h:39,
from /usr/include/c++/15/x86_64-redhat-linux/bits/c++config.h:2622,
from /usr/include/c++/15/cstdio:46,
from /builddir/build/BUILD/xrootd-5.7.2-build/xrootd-5.7.2/src/XrdSut/XrdSutPFile.cc:29:
In function ‘read’,
inlined from ‘XrdSutPFile::ReadInd(int, XrdSutPFEntInd&)’ at /builddir/build/BUILD/xrootd-5.7.2-build/xrootd-5.7.2/src/XrdSut/XrdSutPFile.cc:1525:24:
/usr/include/bits/unistd.h:32:10: error: ‘*read’ specified size 18446744073709551614 exceeds maximum object size 9223372036854775807 [-Werror=stringop-overflow=]
32 |   return __glibc_fortify (read, __nbytes, sizeof (char),
|          ^~~~~~~~~~~~~~~
/usr/include/bits/unistd-decl.h: In member function …
```
=> Fix compilation errors with GCC 15

src/XrdOfs/XrdOfsFSctl_PI.hh
Withouth this correction, `-Wall -Werror` builds on Mac fail when importing the headers with the following message:
```
/xrootd/build/release_dir/include/xrootd/XrdSfs/XrdSfsInterface.hh:161:1: error: 'XrdSfsFSctl' defined as a struct here but previously declared as a class; this is valid, but may result in linker errors under the Microsoft C++ ABI [-Werror,-Wmismatched-tags]
struct XrdSfsFSctl //!< SFS_FSCTL_PLUGIN/PLUGIO/PLUGXC parms
^
/xrootd/build/release_dir/include/xrootd/XrdOfs/XrdOfsFSctl_PI.hh:44:1: note: did you mean struct here?
```
I think aligning the actual declaration and the forward declaration is a reasonable thing to do here.
=> Correct forward declaration of XrdSfsFSctl

src/XrdCl/XrdClAsyncVectorReader.hh, src/XrdCl/XrdClClassicCopyJob.cc, src/XrdCl/XrdClCopyProcess.cc, src/XrdCl/XrdClFileStateHandler.cc, src/XrdCl/XrdClFileSystem.cc, src/XrdCl/XrdClJobManager.cc, src/XrdCl/XrdClLocalFileHandler.cc, src/XrdCl/XrdClLog.hh, src/XrdCl/XrdClPollerBuiltIn.cc, src/XrdCl/XrdClStream.cc, src/XrdCl/XrdClUtils.cc, src/XrdCl/XrdClXRootDMsgHandler.cc, src/XrdCl/XrdClXRootDTransport.cc, src/XrdCl/XrdClZipArchive.cc, src/XrdClHttp/XrdClHttpFilePlugIn.cc, src/XrdEc/XrdEcReader.cc, src/XrdMacaroons/XrdMacaroonsHandler.cc, src/XrdPfc/XrdPfc.cc, tests/XrdCl/XrdClFileTest.cc
The format for some size_t variables were recently changed from %d to %llu. This fixed a problem on 64 bit architectures, since there size_t is 64 bits wide and %d is the format for a 32 bit type and %llu is the format for a 64 bit type. However, this change introduced a regression on 32 bit architectures where size_t is 32 bits wide.
This change caused some of the tests to fail with a segmentation fault on the Debian armhf architecture:
The following tests FAILED:
108 - XRootD::noauth::test (Failed)
111 - XRootD::host::test (Failed)
114 - XRootD::unix::test (Failed)
117 - XRootD::sss::test (Failed)
120 - XRootD::http::test (Failed)
This first commit adds a type cast so that the new format works for all architectures.
It is possible to get warnings from the compilers for bad format …
=> Add type checking to format strings used in the client library logging routines and fix the errors that it triggers

src/XrdPfc/XrdPfc.cc
When looking up the map of active files, the returned value is a a `nullptr` if the file-open is ongoing.  Check for this case and only try to use the file object if it is non-null.
Without this check, the XrdPfc module will trigger a segfault when trying to increase the reference count for a null object.
The places affected by the nullptr already have appropriate fallback code in place if the filename isn't on the active list at all -- we now use that code instead of crashing.
=> [XrdPfc] Check for a null pointer dereference

src/XrdPosix/XrdPosix.hh, src/XrdPosix/XrdPosixExtern.hh
The current header files of XrdPosix do not properly work when used in a C context. Compiling this reproducer:
```
#include <stdio.h>
#include <XrdPosix/XrdPosix.hh>
int main(){
}
```
With clang this fails because the code tries to include cstdio instead of stdio.h in C context. After fixing this, it works with clang but not with gcc. There are 2 more issues:
- with gcc 11 and newer the code fails to compile when dirent.h is included. This can be fixed by re-arranging the code properly
- Some of the types defined in XrdPosixExtern.hh conflict with the system defaults, e.g. long long should be __off64_t or int functions are actually size_t. Newer compiler versions complain about this. The patch adapts the function definitions accordingly.
=> Fix XrdPosix headers when called in C context

docs/INSTALL.md
Having the build directory path as `xroot/build` in `INSTALL.md` keeps it consistent with next steps described in `TESTING.md`.
https://github.com/xrootd/xrootd/blob/df5006ca1725979cc2e992d34b936d336e1c63ca/docs/TESTING.md?plain=1#L28
=> [Docs] Update installation instructions to use consistent build directory path

src/XrdHttp/XrdHttpReq.cc, tests/XRootD/http.sh
Apache, when generating a HTML listing of a local directory, will suffix directory names with a trailing slash.  This PR tweaks the XRootD directory listing to do the same and adds a corresponding integration test.
Beyond matching common practice, the HTTP fsspec plugin in the Python ecosystem uses the trailing slash as a heuristic to indicate a directory.  With this change, Python users should be able to recursively list directories in XRootD.  While not strictly required, this makes a significant improvement for the lives of Python users.
=> [XrdHttp] Add trailing slash to directories in listing

.github/workflows/CI.yml, docker/Dockerfile.alpine, src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpUtils.cc, tests/cluster/man1.cfg, tests/cluster/man2.cfg, tests/cluster/metaman.cfg, tests/cluster/srv1.cfg, tests/cluster/srv2.cfg, tests/cluster/srv3.cfg, tests/cluster/srv4.cfg, tests/cluster/test.sh
The resource string is unquoted when the request is handled but in case of a redirect the resource should be quoted again otherwise the client will be redirected with a different path than the initial one.
=> [XrdHttp] Quote the resource when handling a redirect

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, tests/XRootD/http.cfg, tests/XRootD/http.sh
(This patch is more of a RFI -- I think all the infrastructure is in place that I can add a unit test before marking it as not a draft)
In Pelican, we want to allow users from browsers to be able to access XRootD servers (including through redirections).  However, to do this, we need to add a few extra headers to all `GET` and `OPTIONS` requests to permit redirections across sites (we hit various CORS safeguards that are reasonable for a generic webapp -- but needed for a data federation).
The existing plugin mechanism isn't sufficient because we don't want to _replace_ the XRootD handling of the requests (such as a `GET`) but rather augment it with a few static headers.
This PR adds a new configuration option, `http.staticheader`, that permits such a header to be set.  The config option …
=> [XrdHttp] Allow static headers to be specified for browsers

src/XrdPosix/XrdPosixLinkage.cc, src/XrdPosix/XrdPosixLinkage.hh, src/XrdPosix/XrdPosixPreload.cc
When trying to use XrdPosix on Apple, the code is not able to find system calls like open64. This patch assumes that Apple is always 64bit and maps these functions to the "regular" system calls. Using  XRDPOSIX_REPORT=1 reports two more missing functions, namely acl() and Lgetxattr() which cannot be found. These are disabled by this patch when running on this platform. With this fix in xrootd, the next version of CERNLIB can be xrootd enabled as well on Apple.
=> Fixes for XrdPosix on Apple 

src/XrdTpc.cmake
Small improvement I noticed for XrdTpc while cleaning up other sources:
We define a minimum CMake version such that we're guaranteed to have the `CURL::libcurl` target; use that to match CMake's current philosophy.
=> [XrdTpc] Modernize libcurl linkage

src/Xrd/XrdPollPoll.icc, tests/CMakeLists.txt, tests/XRootD/http.cfg, tests/XRootD/http.sh, tests/XRootD/test.sh, tests/stress/CMakeLists.txt, tests/stress/curl_stress.cc
This implements a simple HTTP-based stress test that, on my laptop, fails 100% of the time.  All it does is try an increasing number of concurrent HTTP uploads.
By "stress tests", it tends to fail at 10 concurrent transfers _provided_ this line is set:
```
if (idx != 2) curl_easy_setopt(handle.get(), CURLOPT_FORBID_REUSE, 1L);
```
If, instead, that line is:
```
curl_easy_setopt(handle.get(), CURLOPT_FORBID_REUSE, 1L);
```
then I've never gotten the stress test to fail, even with more than 100 concurrent transfers.  Note -- `CURLOPT_FORBID_REUSE`, when set, causes a new TCP socket to be created for each transfer.  By turning it off, there's multiple requests on a single TCP socket.
I believe this is due to the fact that HTTP is such a simple protocol the poller only fires once per socket …
=> MacOS stress test

xrootd.spec
See the last paragraph in this comment:
https://github.com/xrootd/xrootd/issues/2433#issuecomment-2741703886
With this tweak using the file in the tar ball works.
=> Workaround for %pre being evaluated before sources are unpacked in %prep

src/XrdPss/XrdPssCks.cc, src/XrdPss/XrdPssCks.hh
When debugging the proxy with crc32c enabled and using token auth, I hit two issues fixed by this PR:
1.  `crc32c` is not in the hardcoded list of known algorithms.  Probably due to the fact `crc32c` support is newer than the PSS checksum support?
2. XrdPss drops the authorization token when it creates the forwarded request.  Unlike other calls to construct a URL, it disabled the appending of the environment CGI.
- A side-effect of this was it also dropped the `cks.type` parameter for non-xrootd URLs (e.g., `https://` or `pelican://`) because `cks.type` was only explicitly forwarded for xroot-protocol-based origins.
On the upside, with this, I'm able to get checksums to pass-through from the cache to a Pelican-based origin!
=> [XrdPss] Fix proxy when using tokens and crc32c

src/XrdTpc/XrdTpcState.cc, src/XrdTpc/XrdTpcState.hh, src/XrdTpc/XrdTpcTPC.cc
On older versions of libcurl (at least 7.x), PUTs unconditionally triggered the use of `Expect: 100-continue`.
We've observed that newer versions of libcurl no longer force this behavior -- but also have bugs when it's not present!  Upstream issue is reported at https://github.com/curl/curl/issues/17004.
Pragmatically, until libcurl is fixed -- and we can assume the fix is deployed everywhere -- we will need to go back to the older behavior as seen on AlmaLinux 9 and similar.
Credit to @dynamic-entropy for uncovering the issue, narrowing it down, and coming up with the approach for the fix.  I just added some comments :)
Fixes: https://github.com/xrootd/xrootd/issues/2470
=> [XrdTpc] Force use of `Expect: 100-continue` header

src/XrdPfc.cmake
~~Follow recommendation from https://cmake.org/cmake/help/latest/command/install.html and make the destination path relative.~~
Use `CMAKE_INSTALL_INCLUDEDIR` instead of hardcoded `include/` suffix.
Context: [updating XRootD from 5.7.1 to 5.8.0 on nixpkgs](https://github.com/NixOS/nixpkgs/pull/397667).
[This patch](https://github.com/xrootd/xrootd/pull/2436/files#diff-7b25d5f1cdc3ff8d39ffeb84e4285b93dcdce7bb4ed29217eed6d2702b26994dR107-R120) is causing our build to fail when installing the package:
```
Moving /nix/store/3zw12avd4c3h07a0rpl35jvqhv0gfx6l-xrootd-5.8.0-bin/bin/xrootd-config to /nix/store/6vnmipw8p1hc6cmkrsq9v1ay7j6iycq2-xrootd-5.8.0-dev/bin/xrootd-config
Running phase: fixupPhase
@nix { "action": "setPhase", "phase": "fixupPhase" }
Moving …
```
=> [XrdPfc] fix cmake install rule

src/XrdThrottle/XrdThrottle.hh, src/XrdThrottle/XrdThrottleFileSystem.cc, src/XrdThrottle/XrdThrottleFileSystemConfig.cc
XrdHttp relies on a flag set by XrdXrootd indicating that the file being stat'd is cached. In turn, the stat flag is only set if the SFS layer claims to have the "cache" feature.
It turns out that the XrdThrottle class treated the `Features()` function as if it was an overrided virtual when instead it was a non-virtual method in the base class with the following implementation:
```
uint64_t       Features() {return FeatureSet;}
```
where `FeatureSet` is a protected member.
So, the features reported when the throttle is installed are just some defaults, not the actual features of the object it wraps.
The impact of the bug is the `Age` header is never set for caches with the throttle installed.  It was picked up by the Pelican integration tests when an upgrade to v5.8.0 was attempted.
The …
=> [XrdThrottle] Fix Throttle bug causing incorrect HTTP response

tests/XRootD/CMakeLists.txt, tests/XRootD/cache.cfg, tests/XRootD/cache.sh
This adds a simple integration test that downloads a file from a XCache server through another fixture as an origin, then verifies the file is unchanged.
@amadio - the approach is as what we discussed earlier today ... added explicit dependency between fixtures but did not rework how the CMakeLists.txt is working.
=> [XrdPfc] Add simple integration test for the PFC

src/XrdHttp/XrdHttpProtocol.cc
Add missing status codes to XrdHttpProtocol to capture all codes returned by XrdHttpReq
Fixes: #2484
=> Add missing default HTTP status messages

tests/XRootD/scitokens.sh
The test binaries are in ${CMAKE_BINARY_DIR}/bin which is already in PATH.
=> Drop unnecessary change of PATH

src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh, tests/CMakeLists.txt, tests/XRootD/common.cfg, tests/XRootD/http.sh, tests/XRootD/test.sh, tests/XrdOssTests/CMakeLists.txt, tests/XrdOssTests/xrdoss_tests.cc
When using `X-Transfer-Status`, there were three subtle HTTP protocol
errors:
- The trailer contained a `\n` which is not a permitted character. This caused clients to view the last CRLF as leftover data on
an idle TCP channel.
- A trailer was sent but no `Trailer` header was sent in the response.
- When the server said that the connection would be kept alive but an error occurred, it closed the TCP connection unexpectedly on the client.  The server now keeps the TCP connection open if keepalive is enabled, provided the HTTP response was sent cleanly.
To prevent regressions, this adds the first unit test that injects read failures mid-transfer.
=> [XrdHttp] Fix HTTP protocol errors on failure

src/XrdHttp/CMakeLists.txt, src/XrdHttp/XrdHttpHeaderUtils.cc, src/XrdHttp/XrdHttpHeaderUtils.hh, src/XrdOuc/XrdOucUtils.cc, src/XrdOuc/XrdOucUtils.hh, tests/XrdHttpTests/XrdHttpTests.cc
This makes header parsing located in one place in addition to allow unit testing for header parsing.
As an example, the Repr-Digest header parsing has been implemented.
This is a preparation for future header parsing refactoring and new header parsing addition (https://github.com/xrootd/xrootd/issues/2541). It would be nice to have it in master so that I can refer to this code on my future developments.
=> [XrdHttp] Added header utils class for header parsing

tests/scitokens/XrdScitokensCreateJwks.cc
OSSL_PARAM_get_octet_string() retrieves an OCTET string from the parameter pointed to by p. The OCTETs are either stored into *val with a length limit of max_len or, in the case when *val is NULL, memory is allocated and max_len is ignored. *used_len is populated with the number of OCTETs stored. If val is NULL then the OCTETS are not stored, but *used_len is still populated. If memory is allocated by this function, it must be freed by the caller.
```
110: ==71089==ERROR: LeakSanitizer: detected memory leaks
110:
110: Direct leak of 65 byte(s) in 1 object(s) allocated from:
110:     #0 0xffff940e3fa0 in malloc (/lib64/libasan.so.8+0xe3fa0) (BuildId: 8a06fba3c3703d6d4fc1517732173e023d50b811)
110:     #1 0xffff93b70cc8 in CRYPTO_malloc (/lib64/libcrypto.so.3+0x170cc8) (BuildId: …
```
=> Fix memory leak in scitokens test reported by address sanitizer

src/XrdOuc/XrdOucTable.hh
Previously, when the last entry in the table was deleted, there was a check of the `N+1` entry.  This could potentially cause a segfault if the end of the table is the end of a page.
A segfault was triggered when running under ASAN with a high concurrency of jobs requesting checksums.
Fixes #2534
=> Avoid reference beyond end of table

src/XrdOssCsi/XrdOssCsi.cc, src/XrdOssCsi/XrdOssCsiPagesUnaligned.cc
Hi,
These are two bug fixs for OssCsi: (as two commits),
(1) Use std::less when comparing two pointers (in this situation the total ordering of pointers is used to give a locking order)
(2) When using nofill option do not cause tag files to potentially be sparse as a side effect.
The first does not appear to cause any problem, using operator<() or std::less produced similar code in the builds I tried. But I believe it's not correct according to the standard. (Actually was previusly using operator<() of a std::shared_ptr, which, may be defined. But commit adds comment as well, to point out ordering issue)
The second may have been seen to cause a rare problem in some old development tests (on rh7) I was reviewing.
=> Couple of Csi bug fixes

src/XrdOuc/XrdOucGatherConf.cc
Constructor unconditionally allocates the `gcP` pointer; destructor must free the space.
Leak detected via dependant plugin built with ASAN.
=> [XrdOuc] Fix memory leak

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, src/XrdTls/XrdTlsContext.cc, src/XrdTls/XrdTlsContext.hh, tests/XRootD/CMakeLists.txt, tests/XRootD/httpclientauth.authdb, tests/XRootD/httpnoclient.cfg, tests/XRootD/httpnoclient.sh, tests/XRootD/scitokens.authdb, tests/XRootD/scitokens.sh
When users visit XRootD-based HTTP servers in the browser, they get a pop-up request for selecting a client certificate.  This is fairly disruptive for users not working in X.509-based environments -- and completely unnecessary if X.509 authentication is not in use!
This PR adds two new options, `tlsclientauth` and `tlsrequiredprefix`, that control when the HTTPS server may request a client certificate.  Note that this only makes sense for the HTTPS protocol and hence isn't part of the generic XrdTls configuration.
<hr>
`http.tlsclientauth [on|off|defer]`
Controls the use of client certificate authentication *only* for the HTTPS protocol.  When *on* (default), the HTTPS protocol server will always request a client certificate from the client.  When *off*, it will never request a …
=> Defer or disable TLS client authentication

src/XrdThrottle/CMakeLists.txt, src/XrdThrottle/XrdOssThrottleFile.cc, src/XrdThrottle/XrdThrottle.hh, src/XrdThrottle/XrdThrottleConfig.cc, src/XrdThrottle/XrdThrottleConfig.hh, src/XrdThrottle/XrdThrottleFile.cc, src/XrdThrottle/XrdThrottleFileSystemConfig.cc, src/XrdThrottle/XrdThrottleManager.cc, src/XrdThrottle/XrdThrottleManager.hh
This is an extensive reworking of the throttle plugin containing the following changes:
- Overhaul the concurrency throttle to be "multiuser-aware".  Each user's (as identified from the `XrdSecEntity`) load is tracked separately.  When a new I/O operation can be started, the user's likelihood of being woken up is proportional to how close they are to their fairshare average.
- Users who are under their fairshare are not delayed by the throttle.  This provides a smooth experience to a user even when a server is overloaded by another user.
- The plugin can be loaded as an OSS; this is required to get user information for fairshare calculation (as the user name is extracted by the OFS when authorizing using tokens).  When run in OSS mode, the "loadshed" functionality (redirecting users to a …
=> Overhaul the throttle plugin

src/XrdSsi/XrdSsiFileReq.cc, src/XrdSsi/XrdSsiFileReq.hh, src/XrdSsi/XrdSsiFileSess.cc, src/XrdSsi/XrdSsiFileSess.hh, src/XrdSsi/XrdSsiRRTable.hh
Initial (rather large) patch aiming to fix #2479, #2481 considered to be due to use of XrdSsiFileReq after free/recycle; typically triggered when client is canceling requests.
=> [Ssi] Track SsiFileReq use to avoid use after free #2479 #2481

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh
By default, the bridge will retry operations internally until the maximum delay is hit and then return an error.  By default, the maximum delay is 3600 seconds; this is well beyond the timeouts of a typical HTTP client.
This makes the delay configurable for HTTP with the following:
```
http.maxdelay <seconds>
```
as in
```
http.maxdelay 10
```
It also tunes down the default delay to 30s.
Note: the response time can still be greater than 30s; this just limits how long the bridge will process "wait" responses for.
=> Make HTTP's maximum open delay configurable

src/CMakeLists.txt, src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh, src/XrdHttpCors/CMakeLists.txt, src/XrdHttpCors/README.md, src/XrdHttpCors/XrdHttpCors.hh, src/XrdHttpCors/XrdHttpCorsHandler.cc, src/XrdHttpCors/XrdHttpCorsHandler.hh, src/XrdVersionPlugin.hh, tests/XRootD/http.cfg, tests/XRootD/http.sh, tests/XrdHttpTests/CMakeLists.txt, tests/XrdHttpTests/XrdHttpTests.cc, xrootd.spec
This is draft and not properly tested. Despite having unit tests, I plan to add system test as well!
Please have a look so I can get early feedback and correct things once I'm back.
Thanks,
Cheers,
Cedric
This is the config file:
```
http.cors libXrdCors.so
cors.origin https://test.cern.ch
cors.origin https://test2.cern.ch https://test.ch
```
This is the effect on a PUT request:
```
> PUT /tmp/fic.txt_dest? HTTP/1.1
> Host: xrootd.cern.ch:1096
> User-Agent: curl/7.76.1
> Accept: */*
> Repr-Digest: adler=:RXJyb3IK=:, sha256=:test:
> Origin: https://test.cern.ch
> Content-Length: 5242880
> Expect: 100-continue
> 
< HTTP/1.1 100 Continue
< Connection: Close
< Server: XrootD/v5.7.1-22-g82a3fc0e8
< Access-Control-Allow-Origin: https://test.cern.ch
```
=> 2541 cors plugin implementation

src/XrdOssStats/README.md, src/XrdOssStats/XrdOssStatsFileSystem.cc, src/XrdOssStats/XrdOssStatsFileSystem.hh, src/XrdPfc/XrdPfc.cc, src/XrdPfc/XrdPfc.hh, src/XrdPfc/XrdPfcConfiguration.cc
XrdOssStats currently doesn't work when loaded by the PFC:
- The PFC passes an empty environment which excludes the `oss.gStream*` (and any other object pointers in the environment; just for the stats plugin the gStream is critical).
- XrdOssStats ignores the `runmode` causing the different statistics to be sent with the same header.
=> [XrdPfc] Fix XrdOssStats when running under the PFC
