src/XrdCeph/XrdCephOssFile.cc, src/XrdCeph/XrdCephPosix.cc
- bad seeking leading to truncated files
- bad handling of O_TRUNC on file creation
- bad handling of O_EXCL on file creation
=> fixes triggered by RAL tests

src/XrdFileCache/XrdFileCacheFactory.cc
These are fixes  slc5 and solaris comapilation errors from PR #209
=> pfc: Fix compilation errors from PR #209

src/XrdCeph/XrdCephOss.cc, src/XrdCeph/XrdCephPosix.cc
listing of files was broken and has now been fixed
=> Fixes around ls in XrdCeph

src/XProtocol/YProtocol.hh
"orivate" should be "private".
=> Correct typo in comment

src/XrdFileCache/XrdFileCachePrefetch.cc
Observed with xrdcp ran without -f option and an existing local file. Fixes #239.
=> pfc: release lock when a file is closed before the prefetch thread is stared

src/XrdFileCache/README, src/XrdFileCache/XrdFileCache.cc
Update README to configuration changes in release 4.1.
=> pfc: Update README file

src/XrdPss/XrdPss.cc
=> Revert "Do not forward the 'tried=' CGI within the proxy interface."

src/XrdCeph.cmake, src/XrdCeph/XrdCephPosix.cc
=> ceph related compilation fixes for CC7

src/XrdCeph.cmake
Fix for undefined symbols in XrdCephPosix library.
=> Fix for undefined symbols

src/XrdFileCache.cmake, src/XrdFileCache/XrdFileCache.cc, src/XrdFileCache/XrdFileCache.hh, src/XrdFileCache/XrdFileCacheFile.cc, src/XrdFileCache/XrdFileCacheIOEntireFile.cc, src/XrdFileCache/XrdFileCacheIOFileBlock.cc, src/XrdFileCache/XrdFileCacheVRead.cc
The Cache:Create() method is obsolete  XrdOucCacheV2. 
The change is related to  c00a774.
=> pfc: Merge Factory class to Cache class.

src/XrdFileCache/XrdFileCache.cc, src/XrdFileCache/XrdFileCache.hh, src/XrdFileCache/XrdFileCacheConfiguration.cc, src/XrdFileCache/XrdFileCacheFile.cc, src/XrdFileCache/XrdFileCacheFile.hh, src/XrdFileCache/XrdFileCacheIO.hh, src/XrdFileCache/XrdFileCacheIOEntireFile.cc, src/XrdFileCache/XrdFileCacheIOEntireFile.hh, src/XrdFileCache/XrdFileCacheIOFileBlock.cc, src/XrdFileCache/XrdFileCacheIOFileBlock.hh, src/XrdFileCache/XrdFileCacheVRead.cc, src/XrdPss/XrdPssConfig.cc
With this change file cache reads can be asynchronous.
=> pfc: Move file cache to XrdOucCache2 interface

src/XrdFileCache/XrdFileCache.cc, src/XrdFileCache/XrdFileCache.hh, src/XrdFileCache/XrdFileCacheFile.cc, src/XrdFileCache/XrdFileCacheFile.hh, src/XrdFileCache/XrdFileCacheIO.hh, src/XrdFileCache/XrdFileCacheIOEntireFile.cc, src/XrdFileCache/XrdFileCacheIOEntireFile.hh, src/XrdFileCache/XrdFileCacheIOFileBlock.cc, src/XrdFileCache/XrdFileCacheIOFileBlock.hh, src/XrdFileCache/XrdFileCacheInfo.cc, src/XrdFileCache/XrdFileCacheInfo.hh, src/XrdFileCache/XrdFileCachePrint.cc, src/XrdFileCache/XrdFileCacheVRead.cc, src/XrdPosix/XrdPosixObjGaurd.hh
Open remote client only when necessary: 
* at open time when file does not exists on disk
* on Read request, where the requested range is missing on disk
=> pfc: Implement deferred open

src/XrdFileCache/XrdFileCacheFile.cc
This fixes a problem where up to 100 last-read blocks (since the last automatic sync) would not be marked as available in the cache info file.
=> Make sure info about blocks since the last sync is also written out.

src/XrdFileCache/XrdFileCacheConfiguration.cc
Use similar formatting as other xrootd plugins.
=> pfc-V2: Improve configuration status printout

src/XrdCeph/XrdCephPosix.cc
Mostly important : fixed memroy corruption (and core dumps) when reading files
=> latest fixes on the ceph plugin

src/XrdFileCache/README, src/XrdFileCache/XrdFileCache.cc, src/XrdFileCache/XrdFileCache.hh, src/XrdFileCache/XrdFileCacheConfiguration.cc, src/XrdFileCache/XrdFileCacheFile.cc, src/XrdFileCache/XrdFileCacheFile.hh, src/XrdFileCache/XrdFileCacheIO.hh, src/XrdFileCache/XrdFileCacheIOEntireFile.cc, src/XrdFileCache/XrdFileCacheIOFileBlock.cc, src/XrdFileCache/XrdFileCacheInfo.cc, src/XrdFileCache/XrdFileCacheInfo.hh, src/XrdFileCache/XrdFileCachePrint.cc, src/XrdFileCache/XrdFileCachePurge.cc, src/XrdFileCache/XrdFileCacheTrace.hh, src/XrdFileCache/XrdFileCacheVRead.cc
* replace XrdOucTrace with XrdCl::Log
* debug levels set in config file with pfc.trace option
=> pfc-V2: use XrdOucTrace for logging

src/XrdFileCache/XrdFileCache.cc, src/XrdFileCache/XrdFileCacheFile.cc, src/XrdFileCache/XrdFileCacheFile.hh, src/XrdFileCache/XrdFileCacheIO.cc, src/XrdFileCache/XrdFileCacheIO.hh, src/XrdFileCache/XrdFileCacheIOEntireFile.cc, src/XrdFileCache/XrdFileCacheIOEntireFile.hh, src/XrdFileCache/XrdFileCacheIOFileBlock.cc, src/XrdFileCache/XrdFileCacheTrace.hh, src/XrdFileCache/XrdFileCacheVRead.cc
This change solves warning "XrdPosix: Unexpected PrepIO calls".
=> pfc-V2: Propagate change of input source from XrdFileCache::IO to XrdFileCache::File

src/XrdFileCache.cmake
This change should be included in #376
=> pfc-V2: Add missing source to XrdFileCache.cmake

src/XrdFileCache/XrdFileCache.cc, src/XrdFileCache/XrdFileCacheIO.cc, src/XrdFileCache/XrdFileCacheIO.hh, src/XrdFileCache/XrdFileCacheTrace.hh, src/XrdPosix/XrdPosixPrepIO.cc
Report from:
* XrdFileCache::Cache::Attach()
* XrdFileCache::IO::Update
=> XrdPfc: Print data server in info trace

src/XrdHttp/XrdHttpProtocol.cc
Plus remove stale comments and blank lines
=> Allow unauthenticated https clients

src/XrdCeph/XrdCephPosix.cc
Cluster were only initialized upon striper creation, leading to seg faults in case a non striping command was used first (e.g. statfs).
This was preventing cmsd to start as it is calling statfs
=> Fixed initialization of Ceph clusters when stripers are not used

src/XrdCl/XrdClMessageUtils.hh
This is the code change discussed in #404
=> Protect against spurious wakeups in SyncResponseHandler.

src/XrdFileCache/XrdFileCacheFile.cc
Fix invalid iterator in ioActive() debug print.
=> pfc: Fix ioActive() debug print

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpReq.cc
in particular about the short name
=> Fill the XrdSecEntity struct according to the last discussions,

src/XrdCeph/XrdCephOss.cc, src/XrdCeph/XrdCephOss.hh, src/XrdCeph/XrdCephPosix.cc
Whenever the green light comes from RAL, these should be merged.
=> several fixes required by RAL

packaging/rhel/xrootd.spec.in, src/XrdFileCache/XrdFileCacheConfiguration.cc, src/XrdHeaders.cmake
* install headers needed for decision plugin development
* package them with the server-devel rpm
* allow several space separated arguments to be passes to the decision plugin
=> [XrdFileCache] ease development of decision plugins

src/XrdCeph/XrdCephPosix.cc
This should only be merged on top of #505 
[XrdCeph] Fixed some resource leak when Posix_Open fails
File descriptor were allocated (this is not a leak per se, just a counter increasing) and stored into maps where they would never be deleted in case of error.
Now maps are cleaned up in case of errors
=> Fd leak fix

.travis.yml
Given the positive reaction in #502, here's a PR with a Travis CI configuration file.
This PR is WIP while I figure out how to get as much as possible building on Travis (different compilers, Python versions, platforms, …). So, lots of little tests commits, then I'll rebase once things look good.
=> WIP: Add Travis CI configuration

bindings/python/libs/client/__init__.py, bindings/python/libs/client/copyprocess.py, bindings/python/libs/client/file.py, bindings/python/libs/client/filesystem.py, bindings/python/libs/client/flags.py, bindings/python/libs/client/responses.py, bindings/python/libs/client/url.py, bindings/python/libs/client/utils.py, bindings/python/setup.py.in, bindings/python/src/ChunkIterator.hh, bindings/python/src/PyXRootD.hh, bindings/python/src/PyXRootDCopyProcess.hh, bindings/python/src/PyXRootDFile.cc, bindings/python/src/PyXRootDFile.hh, bindings/python/src/PyXRootDFileSystem.cc, bindings/python/src/PyXRootDFileSystem.hh, bindings/python/src/PyXRootDModule.cc, bindings/python/src/PyXRootDURL.cc, bindings/python/src/PyXRootDURL.hh, bindings/python/src/Utils.cc
This PR adds Python 3 support to the Python bindings.
The changes are relatively minor, but I haven't been able to run the Python tests. Are there instructions for doing so? There's an `env.py` file that it looks like I should source somehow, and I think I should have a server running on `localhost`, but I don't know where to start. Any help would be appreciated!
=> Support Python3

src/XrdHeaders.cmake, src/XrdHttp.cmake, src/XrdHttp/XrdHttpExtHandler.cc, src/XrdHttp/XrdHttpExtHandler.hh, src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh, src/XrdHttp/XrdHttpUtils.cc
Make XrdHTTP able to forward HTTP requests to an external, optional plugin (conceptually similar to CGI). 
Various stability fixes and improvements.
=> Make XrdHTTP able to forward HTTP requests to an external, optional plugin (conceptually similar to CGI). Various stability fixes and improvements.

.gitlab-ci.yml
Corrected and tested clean up.
=> [CI] correct artifact clean up scripts

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh, src/XrdHttp/XrdHttpUtils.cc
From recent github discussions
=> Recent minifixes to XrdHttp

src/XrdCl/XrdClUtils.hh, src/XrdCl/XrdClXRootDTransport.cc
We need this for the shared eos fuse mount, which is running
as root. It eliminates the possibility of a race condition between
the time credentials are checked by eosd, and the time they are
actually read by XrdCl.
=> [XrdCl] Add option to read credentials under different fsuid/fsgid

src/XrdCeph/XrdCephOss.cc, src/XrdCeph/XrdCephOssDir.cc, src/XrdCeph/XrdCephOssFile.cc, src/XrdCeph/XrdCephXAttr.cc, src/XrdCl/XrdClLocalFileHandler.cc
Here are fixes for compilation errors I encountered when compiling xrootd 4.8.2.
=> Fix compile errors

src/XrdFileCache/XrdFileCacheFile.cc, src/XrdFileCache/XrdFileCacheIOFileBlock.cc, src/XrdFileCache/XrdFileCacheStats.hh, src/XrdFileCache/XrdFileCacheVRead.cc
=> [Pfc] Make sure per file access stats are synchronized properly.

src/XrdCrypto/XrdCryptosslgsiAux.cc
=> cryptossl: add protection against missing extension

.gitlab-ci.yml
=> [CI] ubuntu bionic build and packaging

src/XrdOfs/XrdOfsConfigPI.cc, src/XrdOfs/XrdOfsConfigPI.hh
=> Prevent double-parsing of parameters for ofs.ckslib.

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpReq.cc
=> In the case of token-based http redirection, pass all the missing XrdSecEntity fields

src/XrdHttp/XrdHttpReq.cc
=> Make MOVE able to deal with spaces in the filenames

docs/PreReleaseNotes.txt, src/XrdFileCache.cmake, src/XrdFileCache/XrdFileCache.cc, src/XrdFileCache/XrdFileCache.hh, src/XrdFileCache/XrdFileCacheCommand.cc, src/XrdFileCache/XrdFileCacheConfiguration.cc, src/XrdFileCache/XrdFileCacheFile.cc, src/XrdFileCache/XrdFileCacheInfo.cc, src/XrdFileCache/XrdFileCacheInfo.hh, src/XrdFileCache/XrdFileCachePrint.cc, src/XrdFileCache/XrdFileCachePurge.cc, src/XrdFileCache/XrdFileCacheTrace.hh
Purge algorithm can now also consider space used by cached files and age of files. The main purpose is to allow several xcache instances to share the same set of disks.
=> Pfc purge v2

src/XrdSecgsi/XrdSecProtocolgsi.cc
The previous PR was merged to quickly ...
=> secgsi: additional fixes for the no-padding case

cmake/FindOpenSSL.cmake, src/XrdCrypto/XrdCryptosslCipher.cc, src/XrdCrypto/XrdCryptosslCipher.hh, src/XrdCrypto/XrdCryptosslFactory.cc
Also fixes a compilation issue on SLC6
=> Consolidate padding support detection

src/XrdCl/XrdClXRootDTransport.cc, src/XrdSecgsi/XrdSecProtocolgsi.cc
1. Printout leftover in XrdSecProtocolgsi (screws up prompt)
2. Small mem leak in XrdCl (less urgent, perhaps)
=> Urgent fixes for

src/XrdCrypto/XrdCryptoCipher.cc, src/XrdCrypto/XrdCryptosslCipher.cc, src/XrdSecgsi/XrdSecProtocolgsi.cc, src/XrdSut/XrdSutBuffer.cc, src/XrdSut/XrdSutBuffer.hh
To avoid wrong assumptions.
Also improves dumping of buffers content during debug.
=> Secgsi: communicate the length of the IV

src/XrdCl/XrdClParallelOperation.hh, tests/XrdClTests/OperationsWorkflowTest.cc
=> fix signness and tests

src/XrdFileCache/XrdFileCache.hh, src/XrdFileCache/XrdFileCacheFile.cc, src/XrdFileCache/XrdFileCacheFile.hh
Fix memory leak - block was not freed when writing to disk failed.
=> [XCache] Fix memory leak

src/XrdFileCache/XrdFileCacheConfiguration.cc
=> [XCache] Set trace to max of config file and environment values.

src/XrdTpc/XrdTpcTPC.cc
The `authz` query parameter, if included in the request, needs to be copied over to the `Authorization` header and removed from the request itself.  This prevents the `authz` value (potentially quite long) from being propagated to the filename.
Fixes #988
=> Do not include `authz` header in the filename.

src/XrdHttp/XrdHttpReq.cc
Digest name issues reported by @olifre.
@simonmichal - Should be included in 4.10, if possible.
=> Fix digest names returned to clients.

src/CMakeLists.txt, utils/cms_monPerf
simplified script for usage by cms.perf directive
=> add utils/cms_monPerf for cms.perf usage

src/XrdHttp/XrdHttpUtils.cc
=> Fix escape code for \r

src/XrdHttp/XrdHttpProtocol.cc
Fix the "100 Continue" response
Fixes #1120
=> Fix the "100 Continue" response

src/XrdTpc/XrdTpcTPC.cc
This request enables the XrdTpc plugin to handle opaque info before and after the interaction with the OFS layer. All this is needed for EOS to work with XrdTpc and macaroons.
=> Allow XrdTpc to handle opaque info

src/XrdXrootd/XrdXrootdConfig.cc
This pull request fixes the xrd_config docs segsz parameter and replaces it to segsize.
=> Fixed wrong segsz parameter

src/XrdHttp/XrdHttpProtocol.cc
Some XrdHTTP little fixes and improvements
=> Some XrdHTTP little fixes and improvements

src/XrdTpc/XrdTpcState.cc
Older versions of `libcurl` (such as the one found on RHEL6) do not define `CURLINFO_PRIMARY_PORT`.  Add a simple version-test macro and do not provide this specific new functionality on such a host.
=> Avoid old versions of libcurl that do not support CURLINFO_PRIMARY_PORT

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpReq.cc
Additional protection linked to https://github.com/xrootd/xrootd/issues/1176
=> Added protection against a NULL bridge instance

packaging/common/xrootd-clustered.cfg, packaging/common/xrootd-filecache-clustered.cfg, packaging/common/xrootd-filecache-standalone.cfg, packaging/common/xrootd-http.cfg, packaging/common/xrootd-standalone.cfg, packaging/common/xrootd.logrotate
Quite many of them in some cases...
=> Remove space at end of line in config files

bindings/python/libs/client/finalize.py
Fixes an issue where if files are not closed before the Python interpreter exits `XRootD.client` causes the Python interpreter to deadlock.
This can be reproduced in both XRootD 4.12.3 and 5.0.0. If there is any intention to make further releases for the 4.x series it would be nice to have this back ported.
You can find some more details about this below and in: https://github.com/scikit-hep/uproot/issues/504
1. Create a file called `xrootd_bug.py` containing:
```python
import XRootD.client
f = XRootD.client.File()
f.open('root://eospublic.cern.ch//eos/opendata/lhcb/AntimatterMatters2017/data/B2HHH_MagnetDown.root')
```
2. Run `python xrootd_bug.py`
This is caused by the `atexit` function shutting down the worker thread pool:
https://github.com/xrootd/xrootd/blob/912673bfbc75ff0d9f66155671 …
=> Prevent deadlock in Python bindings from XRootD.client.finalize.finalize

src/XrdPfc/XrdPfc.cc
Please merge this fix to v5 stable. I had to keep this patch for my 5.0.2 build.
=> Fix 32 bit compilation

src/XrdOfs/XrdOfsConfigPI.cc, src/XrdOss/XrdOssApi.cc
=> Remove junk bytes

src/XrdSys/XrdSysPthread.hh
=> 1 ms = 1000000 ns

src/XrdSciTokens/src/XrdAccSciTokens.cc
Caught in testing in github issue #1353
=> Remove unique_ptr and correct ObjAdd function parameters

src/XrdSciTokens/XrdSciTokensAccess.cc
This is also requires a change in xrootd-multiuser, which is proposed in https://github.com/opensciencegrid/xrootd-multiuser/pull/17
@abh3 Please review and criticize.  This is meant as the first pass.  I lightly tested this that it authorizes things correctly.
=> Refactor how attributes are passed to chained auth plugins with SciTokens

src/XrdTpc/XrdTpcState.cc
=> XrdTpc: Do not call Write() on flush.

src/XrdTpc/XrdTpcMultistream.cc
=> XrdTpc: Avoid using invalid object in multi-stream.

src/XrdMacaroons/XrdMacaroons.cc
In case the XrdMacaroons library is chained with another library (for example XrdSciTokens) and loading the second library fails for whatever reason e.g configuration is wrong, then the XrdMacaroons library will happily continue holding a nullptr for the chained library. This can lead to some misleading error messages.
=> XrdMacaroons: Handle case when loading a chained authz library fails.

src/XrdXrootd/XrdXrootdXeqAio.cc
Make sure stalled aio get written with the right offset and length.
=> [Server] Make sure stalled aio get written with the right offset and length

src/XrdCrypto/openssl3/XrdCryptosslAux.cc, src/XrdCrypto/openssl3/XrdCryptosslCipher.cc, src/XrdCrypto/openssl3/XrdCryptosslRSA.cc, src/XrdTls/openssl3/XrdTlsContext.cc
Fixes for openssl 3
- Some debugging
- Add missing commits from the old vesrion
=> Openssl3 fixes

docs/PreReleaseNotes.txt, src/XrdCl/XrdClEcHandler.cc, src/XrdCl/XrdClEcHandler.hh, src/XrdFfs/XrdFfsXrootdfs.cc
This helps balancing the storage space usage.
=> In EC choose servers for writing based on free space 

src/XrdSciTokens/XrdSciTokensAccess.cc
The ZTN protocol now attaches the token used to authorize the xrootd protocol session as a credential in the security entity.  This change subsequently utilizes that credential as a session token, authorizing individual requests if no better token is available.
=> Allow the SciToken plugin to consume based on ZTN tokens.

src/XrdSciTokens/XrdSciTokensAccess.cc
Simple fix for a memory corruption bug.
=> [XrdSciTokens] Fix memory corruption

src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh, src/XrdOss/XrdOssCreate.cc
=> Allow usage of full URI in the request 

src/XrdCrypto/XrdCryptosslAux.cc
Possible solution to xrootd#1681. I've not yet tested it, so submitting as a draft. If it seems like a valid option, I'm happy to get it built and tested. @bbockelm
=> [XrdCrypto] Modify XrdCryptosslNameOneLine to allow commas in DNs

src/XrdCl/XrdClAsyncMsgReader.hh, src/XrdCl/XrdClStream.cc
Hello,
This is part of a set of 3 PRs for a set of changes to avoid various problems seen while investigating some EOS crashes or issues. There may well be discussion over these PRs!
This PR primarily tries to avoid de-synconisation of the reading of (valid) streams from the server when a request times out. There is
(i) An addition to AsyncMsgReader::Read such that is a kXR_status message is detected, but there is no MsgHandler for the streamid, the correct number of bytes is still read from the network, so that subsequent messages can be received. The situation can happen during a timeout, where e.g. a pgread response is received but the request has timed-out.
(i - a) to allow (i) Stream::InspectStatusRsp() was modified so that the caller can differentiate the situation where there is no …
=> [XrdCl] Avoid situation where client does not read all of a network message

src/XrdCl/XrdClXRootDMsgHandler.cc
Hello,
This is part of a set of 3 PRs for a set of changes to avoid various problems seen while investigating some EOS crashes or issues. There may well be discussion over these PRs!
Currently a SID (stream ID) may be
(i) marked as timed-out.
(ii) Later (usually quite soon) it may be marked as timed-out again.
It may also be released, either after (i) but before (ii) or after (ii).
If the release happens before (ii) the current SID Manager keeps the free SID marked as timed-out. Later it can be alloced again to a request, but when the response to the request is received the response handler doesn't get called with the usual result, as would be the case with a timed out request - but there is not failure or time-out notification sent either. One result seen in some tests is that the …
=> [XrdCl] Avoid race by using TimeOutSID in single place

src/XrdAcc/XrdAccAccess.cc, src/XrdOfs/XrdOfs.cc
This is a new copy of #1763 - only difference is it's based on the master branch and not the stable-5.5.x.
=> Fix overwrite return code (master branch version)

bindings/python/libs/client/copyprocess.py, bindings/python/src/PyXRootDCopyProcess.cc, src/XrdApps/XrdCpConfig.cc, src/XrdApps/XrdCpConfig.hh, src/XrdCl/XrdClClassicCopyJob.cc, src/XrdCl/XrdClCopy.cc, src/XrdCl/XrdClCopyProcess.cc, tests/XrdClTests/FileCopyTest.cc
=> fix typo s/Threashold/Threshold/

src/XrdClHttp/CMakeLists.txt
=> [XrdClHttp] Link against XrdUtils for XrdOucCRC::Calc32C symbol

src/XrdSciTokens/XrdSciTokensAccess.cc
=> Correct the calling of SciTokens Config Parser

README, docs/ReleaseNotes.txt, src/XrdCl/XrdClClassicCopyJob.cc, src/XrdCl/XrdClZipArchive.cc, src/XrdMacaroons/XrdMacaroonsAuthz.cc, src/XrdOssCsi/XrdOssCsiPages.hh, src/XrdOuc/XrdOucPgrwUtils.cc, src/XrdPosix/XrdPosixAdmin.cc, src/XrdPss/XrdPss.cc, src/XrdSciTokens/README.md, src/XrdSciTokens/XrdSciTokensAccess.cc, src/XrdSecgsi/XrdSecProtocolgsi.cc, src/XrdTls/XrdTlsContext.cc, src/XrdTpc/XrdTpcTPC.cc, src/XrdVoms/XrdVomsMapfile.cc
These are cherry-picks from `master` into `stable-5.5.x`. Please ack before I create the new tag tomorrow.
=> Stable release 5.5.2, release candidate 2

src/XrdXrootd/XrdXrootdConfig.cc
=> XrdHttp: Supports non-natively supported checksum in the case a user provides a checksum computation program

src/XrdTls/XrdTlsSocket.cc
To fix a problem observed while investigating issue #1952. (Hopefully this is the cause of that issue).
Fixes #1952.
=> [XrdTls] Reset socket error condition flag during Init

src/XrdCl/XrdClAsyncSocketHandler.cc, src/XrdCl/XrdClAsyncSocketHandler.hh, src/XrdCl/XrdClStream.cc, src/XrdCl/XrdClStream.hh
This is a (second try) fix for issue #1934. (Closes #1934)
=> [XrdCl] Add return codes for error checking in the network Event handler

bindings/python/src/ChunkIterator.hh, bindings/python/src/Conversions.hh, bindings/python/src/PyXRootDFile.cc
Fixes: #2038, introduced by a1cd57f08845dd71556219966af9381eace19be8.
=> [Python] Fix regression introduced when fixing issue #2010

src/Xrd/XrdConfig.cc
On Linux systems, the latest xrootd release `abort()`s during initialisation if the `RLIMIT_NOFILE` (ulimit -n) isn't the max, but is still high, and a default isn't set via the new `maxfd strict` directive.
For instance, on a default docker environment on CentOS Stream 9, the default limit is set to `1073741816`, while the epoll limit is way less than that (it's `INT_MAX / sizeof(struct epoll_event)`, which on that system was `178956970`). 
In the Linux Poller implementation, surpassing this limit causes `EINVAL` to be returned in the first call to `epoll_wait()` as the `maxevents` parameter will be too high. The error output will look like below:
```
Config maximum number of connections restricted to 1073741816
230724 12:21:09 453 Xrd_Config: sendfile enabled.
230724 12:21:09 453 …
```
=> Implement Linux epoll maxfd limit

src/XrdCms/XrdCmsBlackList.cc, src/XrdCms/XrdCmsBlackList.hh
I suppose this is what you meant, right @abh3?
Fixes: #2092
=> Try to load blacklist even if some entries are invalid

src/XrdCl/XrdClFS.cc, tests/XRootD/smoke.sh
=> [XrdCl] Give error return code if xrdfs rm fails to delete any file. Closes #2097

src/XrdHttp/XrdHttpReq.cc
The bugfix change was from using `prot->BufAvailable()` to `prot->BufUsed()`.  I also added sanity checks around the size of the chunk and a few trace statement to help with any future problems.
Chunked encoded PUT are formatted with a length before each chunk. Fix the parsing to only parse the buffer that has been filled. Additionally, add a sanity check on the size of a chunk in order to protect against malformed of malicious sized chunks.
Also, added additional trace statements to help when the chunk is rejected.
=> [XrdHttp] Fix parsing of chunked PUT lengths

src/XrdSciTokens/XrdSciTokensAccess.cc
I'm working on setting up some end-to-end integration tests including the SciTokens library.
When hosting the issuer's public keys on the XRootD server itself, we need to have a validated HTTPS connection from the libcurl handle used internally by the `scitokens-cpp` library.
The `scitokens-cpp` library currently can only use the system CAs, which makes it impossible to utilize the integration test's generated CA.  We need to pass along the CA file used by xrootd.
Pairs with https://github.com/scitokens/scitokens-cpp/pull/132
=> Pass through currently-configured CA file to the SciTokens library

src/XrdCl/XrdClSocket.cc, tests/XrdCl/XrdClURL.cc, tests/XrdClTests/LocalFileHandlerTest.cc
This PR fixes a number of issues found when compiling and running the test suite.
See the commit messages for details.
=> Test issues

src/XrdHttp/XrdHttpProtocol.cc
This change is to fix issue #2114.
=> [HTTP] Initialize SecEntity.addrInfo in fresh protocol object; Fixes #2114

debian/control, src/XrdOssCsi/XrdOssCsiTagstoreFile.hh, src/XrdPosix/XrdPosixPreload32.cc, src/XrdSys/XrdSysPlatform.hh, src/XrdZip/XrdZipLFH.hh, src/XrdZip/XrdZipUtils.hh
The newly added tests for XrdZip revealed endian problems.
This PR addresses these issues.
=> [XrdZip] Support Big Endian

src/XrdTpc/XrdTpcPMarkManager.cc
Fixes the issue https://github.com/xrootd/xrootd/issues/2161
=> [XrdTpcTPC] PMarkManager - corrected a segfault that may happen in the creation of the first packet marking handle

src/XrdCrypto/XrdCryptosslCipher.cc
This patch is to reduce some of the increased CPU time reported in issue #2162.
Increased CPU usage was seen on alma9 (which uses openssl 3.0.7), when using xrootd and gsi. The extra cpu usage is seen by the client using gsi authentication when setting up a xrootd connection to a server. For example (see #2162), 0.15s with openssl 1.0.2k compared with 1.9s with openssl 3.0.7.
This patch reduces the time increase by conditionally skipping the Diffie-Hellman parameter check. The timings reported in the ticket indicate this reduces runtime from ~1.9s to ~0.24s. (This is still longer than the reference runtime with openssl 1.0.2k). The remaining extra time is not thought to be due to DH checks, so for the sake of keeping this PR compact and help review & discussion, this patch only changes …
=> [GSI] Skip check of our standard DH parameters

src/XrdTpc/XrdTpcPMarkManager.cc
The initial implementation of the scitags for HTTP TPC transfers worked well "on my dev machine". But that's only by luck... Once I've deployed this in a test EOS cluster with storage servers not located on the same machine, I did not see any packet markers, but instead error messages like "Transport endpoint is not connected".
I therefore deduced that this was due to the fact that curl's callback on the socket open is not called when the socket is connected, but only when the socket is opened. The socket may or may not be connected despite having been opened.
The change that I propose is to actually simply retry to do the packet marking at a later stage, ensuring the transfer has started.
=> [XrdTpcTPC] PMark - handle the cases where the PMark handle cannot be created because the socket is not yet connected

src/XrdSecsss/XrdSecsssEnt.cc
=> [XrdSecsss] Fix possible buffer overrun when serialising creds. Closes #2143

src/XrdTpc/XrdTpcConfigure.cc, src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh
Committer: Diego Davila <davila.foyo@gmail.com>
=> add config val tpc.sense to force the Destination IP address on a HTTP-TPC

src/XrdCeph/XrdCephPosix.cc, src/XrdCl/XrdClPlugInManager.cc, src/XrdXrootd/XrdXrootdMonitor.cc, test.cmake
This pull request is for testing this functionality.
=> Fix BASE_REF/HEAD_REF for pull requests when publishing on CDash

src/XrdOss/XrdOssApi.cc, src/XrdOss/XrdOssStat.cc
Here are the two small changes I needed to make to get rsscmd support working.  I tested this in v5.6.8.
=> Fix rsscmd support

tests/XrdCl/XrdClFileCopyTest.cc, tests/XrdCl/XrdClPoller.cc, tests/XrdCl/XrdClSocket.cc
Be a bit more consistent with port numbers.
=> Minor test fixes

src/XrdHttp/XrdHttpReq.cc
=> [XrdHttp] Reset HTTP request scitag during reset

src/XrdHttp/XrdHttpExtHandler.cc, src/XrdHttp/XrdHttpExtHandler.hh, src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpProtocol.hh, src/XrdTpc/XrdTpcConfigure.cc, src/XrdTpc/XrdTpcState.cc, src/XrdTpc/XrdTpcState.hh, src/XrdTpc/XrdTpcTPC.cc
Solves issue #2228
Initial simple and basic PR. I don't know if we want to implement the same thing as in https://github.com/xrootd/xrootd/commit/4ef0f2f388f877d0715ffc345afe1b988398749b .
=> [XrdTpcTPC] Add new option to allow for unrestricted redirection

tests/XRootD/smoke.sh, tests/XrdCl/GTestXrdHelpers.hh, tests/XrdCl/XrdClFile.cc, tests/XrdCl/XrdClFileCopyTest.cc, tests/XrdCl/XrdClFileSystemTest.cc, tests/XrdCl/XrdClFileTest.cc, tests/XrdCl/XrdClLocalFileHandlerTest.cc, tests/XrdCl/XrdClOperationsWorkflowTest.cc, tests/XrdCl/XrdClPoller.cc, tests/XrdCl/XrdClPostMasterTest.cc, tests/XrdCl/XrdClSocket.cc, tests/XrdCl/XrdClThreadingTest.cc, tests/XrdCl/XrdClUtilsTest.cc, tests/XrdCl/XrdClZip.cc, tests/XrdEc/XrdEcTests.cc, tests/cluster/setup.sh, tests/cluster/test.sh
This PR fixes some glitches and inconsistencies in the tests.
=> Test fixes

src/XrdCl/XrdClThirdPartyCopyJob.cc, src/XrdSecgsi/XrdSecProtocolgsi.cc, src/XrdSecgsi/XrdSecProtocolgsi.hh
This is a draft patch for #2292
=> SecProtocolgsi: Local copy of url supplied proxy location

src/XrdPfc/XrdPfcFile.cc, src/XrdPfc/XrdPfcFile.hh
=> [XrdPfc] Make sure direct vread requests conform to protocol limits.

src/XrdHttp/XrdHttpReq.cc, src/XrdNet/XrdNetPMark.hh, src/XrdNet/XrdNetPMarkCfg.cc, src/XrdNet/XrdNetPMarkFF.cc, src/XrdTpc/XrdTpcPMarkManager.cc, src/XrdTpc/XrdTpcPMarkManager.hh, src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh
Includes @abh3 PMark implementation adaptation + HTTP + HTTP-TPC PMark modification
=> 2322 scitag source destination

src/XrdHttp/XrdHttpReq.cc, src/XrdOuc/XrdOucUtils.cc, src/XrdPosix/XrdPosixFile.cc, src/XrdPosix/XrdPosixPrepIO.cc, src/XrdPosix/XrdPosixXrootd.cc, src/XrdPss/XrdPss.cc, src/XrdPss/XrdPssCks.cc, src/XrdPss/XrdPssTrace.hh, tests/XrdOucTests/XrdOucUtilsTests.cc
=> [XrdHttp, XrdPosix, XrdPss] Obfuscated more authz in the logging

src/XrdXrootd/XrdXrootdTransit.cc
Each time we process successfully from the redrive thread, we should decrement the status counter.
Otherwise, after multiple requests, the attempt to `Run` from XrdHttp will fail.  This was observed to cause failures in closing files 100% of the time when the open was delayed, causing failures in the XrdHttp response.
This additionally adds logging on failures for submitting the run.
Fixes #2360
=> Reset runStatus state when in the redrive thread

tests/XRootD/http.sh, tests/XRootD/test.sh
More HTTP tests including GET, GET with Range-requests, HEAD with multiple checksum. Aim is to gradually add coverage to HTTP use-cases.
=> [Tests] Added more HTTP tests for CI

src/XrdXrootd/XrdXrootdXeq.cc
=> [XrdXrootdProtocol] do_WriteSpan() - Add written bytes in file statistics

src/XrdHttp/XrdHttpReq.cc, tests/CMakeLists.txt, tests/XRootD/CMakeLists.txt, tests/XRootD/scitokens-module.cfg, tests/XRootD/scitokens.authdb, tests/XRootD/scitokens.cfg, tests/XRootD/scitokens.sh, tests/scitokens/CMakeLists.txt, tests/scitokens/XrdScitokensCreateJwks.cc, tests/scitokens/XrdScitokensCreateToken.cc, tests/scitokens/one-openid-configuration, tests/scitokens/setup.sh, tests/scitokens/teardown.sh, tests/scitokens/two-openid-configuration
This adds an initial, simple unit test for XrdSciTokens authentication.
The goal isn't to be comprehensive but to lay down a baseline that can be used for future changes.
=> [XrdSciTokens] Unit test coverage for token-based authorization

src/XrdTpc/XrdTpcTPC.cc, src/XrdTpc/XrdTpcTPC.hh, src/XrdTpc/XrdTpcUtils.cc, src/XrdTpc/XrdTpcUtils.hh, tests/XrdTpcTests/XrdTpcTests.cc
=> [XrdTpcTPC] Added oss.task=httptpc opaque query to the file open URL

src/XrdCl/XrdClURL.cc
This is a draft, aiming to fix some test failures, usually on alpine and mac os.
=> [Cl] Also recognise IPv4 mapped addresses

src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpReq.hh
=> [XrdHttp] Added 'Age' header file cache HEAD and GET response

tests/TPCTests/test.sh
Mac OS X's bash does not support associative arrays.  By going to more primitive indexed arrays (which are admittedly less pretty), we can enable the TPC test on Mac OS X, broadening the overall test coverage.
=> [XrdTpc] Remove use of newer bash constructs in test

src/XrdHttp/XrdHttpProtocol.cc, src/XrdHttp/XrdHttpReq.cc, src/XrdHttp/XrdHttpUtils.cc, src/XrdHttp/XrdHttpUtils.hh, src/XrdHttpTpc/XrdHttpTpcTPC.cc, tests/XrdHttpTests/XrdHttpTests.cc
Fixes #2491 
Please do not merge as it is not tested fully yet. But first-sight comments are welcome!
=> [XrdHttp/TPC] URL encoding/decoding handles '=' sign

src/XrdCeph/XrdCephOssBufferedFile.cc, src/XrdCeph/XrdCephPosix.cc, src/XrdFfs/XrdFfsPosix.cc, src/XrdFfs/XrdFfsWcache.cc, src/XrdFfs/XrdFfsXrootdfs.cc, src/XrdOss/XrdOssApi.cc, src/XrdOuc/XrdOucMsubs.cc, src/XrdPosix/XrdPosix.cc, src/XrdPosix/XrdPosixXrootd.cc, src/XrdPss/XrdPss.cc
After the issue found in #2508, I found a number of similar issues in other places.
=> More portable, less hard-coding

src/XrdCl/XrdClXRootDMsgHandler.cc
Fixes lost response when an error occurs before the resend of a requeued request. e.g. a requeued message can happen when the client has been redirected or told to wait and resend a request later by kxr_wait. An error before resend could be that the stream connect is lost or the request times out before the resend. Introduced in #2365.
=> [Cl] Reset state when resending a message. Fixes: 3a957083

src/XrdPfc/XrdPfcFile.cc
As soon as the block is freed, it may cause the file to be marked as "inactive" (and thus eligible for deletion).
If a file sync is desired, then we must delay decreasing the block's reference count until after the sync is scheduled to ensure it is still alive when the sync scheduling increases the reference count on the file.
This change eliminates a use-after-free segfault observed on my local stress test which would trigger about 50% of the time (10 clients reading unique 3-byte files in a caching setup would crash after 20-30 seconds).
=> [XrdPfc] Ensure a reference to the file is kept when scheduling a sync

src/XrdCl/XrdClFile.cc, src/XrdCl/XrdClFile.hh, src/XrdCl/XrdClFileStateHandler.cc, src/XrdCl/XrdClFileStateHandler.hh, src/XrdCl/XrdClFileSystem.hh, src/XrdCl/XrdClPlugInInterface.hh
=> [XrdCl] Additional Fcntl interface to propagate query code parameter.

src/XrdHttp/XrdHttpProtocol.cc
Unlike XrdTlsSocket, the HTTP protocol did a one-sided TLS shutdown. This saved network a round-trip but at the cost of correctness: if the server shut down the connection after its response while the client was still sending data then the client may recieve a TCP reset prior to reading out the response.
This exact behavior was observed in unit tests and the correct approach is outlined in latest HTTP 1.1 RFC:
https://datatracker.ietf.org/doc/html/rfc9112#name-tls-connection-closure
Basically, we now do the same as `XrdTlsSocket` and perform a bidirectional TLS shutdown.
This takes care of the HTTPS portion of https://github.com/xrootd/xrootd/issues/2564.
=> Do a clean TLS shutdown for HTTPS
